import type { Question } from "../../types";

/**
 * Exercise-based questions drawn from the actual code examples handed out
 * each week (asteroid game, ServiceLoader demos, payment DI demos, Spring
 * demos, RabbitMQ/SOAP/gRPC/saga/testing projects). Each question carries
 * its real week number, so they merge into the per-week practice quizzes.
 */
const questions: Question[] = [
  // ===== Week 7 — Maven, multi-module builds, composition vs inheritance =====
  {
    week: 7,
    topic: "Parent POM packaging",
    question: "In the course's multi-module asteroid game, the top-level pom.xml lists the modules game-commons, game-entities, game-systems and game-runner. Which packaging type must this parent pom.xml declare?",
    options: ["jar, because every Maven project ultimately produces a JAR", "war, because it aggregates several modules into one deployable", "pom, because the parent is an aggregator that produces no code artifact itself", "module, the dedicated packaging type for multi-module builds"],
    answer: 2,
    explanation: "A parent/aggregator POM uses packaging 'pom': it only coordinates the build of its child modules and carries shared configuration, producing no JAR of its own. 'jar' is the default for code-producing modules, which is why each child module declares packaging jar instead.",
    source: "exercise-based",
  },
  {
    week: 7,
    topic: "mvn install and inter-module dependencies",
    question: "In a multi-module Maven project, module game-runner depends on game-commons (groupId sdu.cbs, version 1.0-SNAPSHOT). A teammate builds only game-runner on a fresh machine and Maven cannot resolve game-commons. What does running mvn install from the parent project fix?",
    options: ["It builds all modules in dependency order and copies each module's artifact into the local repository (~/.m2), where other builds can resolve it", "It uploads all module artifacts to Maven Central so any machine can download them", "It merges all modules into a single JAR so no inter-module dependencies remain", "It edits the child pom.xml files to replace module dependencies with absolute file paths"],
    answer: 0,
    explanation: "The install phase places each built artifact in the local repository (~/.m2/repository), which is where Maven looks up dependencies; running it from the parent builds the whole reactor in the right order. Deploying to a remote repository like Central is the separate 'deploy' phase, not 'install'.",
    source: "exercise-based",
  },
  {
    week: 7,
    topic: "Composition over inheritance",
    question: "The course showed two versions of an asteroid game. In one, an Asteroid is built in its constructor by calling addComponent for a PositionComponent, a VelocityComponent and a CollisionComponent; in the other, SmallAsteroid extends Asteroid which extends an abstract GameObject. What design principle does the first version demonstrate?",
    options: ["Encapsulation: components hide the asteroid's position from other classes", "Composition over inheritance: behavior and data are assembled from reusable parts instead of inherited from a rigid class hierarchy", "Polymorphism: each component overrides methods of the GameObject superclass", "Dependency inversion: the asteroid depends on the game loop rather than the other way around"],
    answer: 1,
    explanation: "Assembling an entity from independent component objects is composition over inheritance: any combination of capabilities (position, velocity, health, collision) can be mixed without creating new subclasses. The components do not override anything, so this is not polymorphism through a class hierarchy.",
    source: "exercise-based",
  },
  {
    week: 7,
    topic: "Inheritance hierarchy drawbacks",
    question: "In the inheritance-based asteroid game, the hierarchy is GameObject -> Asteroid -> SmallAsteroid/LargeAsteroid and GameObject -> Spaceship -> PlayerSpaceship, with fields like x, y and velocity declared protected in the base class. Which problem of this design did the course highlight, compared to the component-based version?",
    options: ["The protected fields make the program run slower than private fields would", "Java forbids more than two levels of inheritance, so the design will not compile", "Subclasses cannot override methods declared abstract in GameObject", "New combinations of capabilities (e.g., an entity needing both health and asteroid-like movement) force new subclasses and duplicated code, because behavior is locked into the hierarchy"],
    answer: 3,
    explanation: "With single inheritance, every new mix of capabilities requires another subclass, leading to class explosion and duplication, and protected fields tightly couple subclasses to the base class's internals. The performance and compilation claims are simply false: Java allows deep hierarchies and protected fields have no speed cost.",
    source: "exercise-based",
  },
  {
    week: 7,
    topic: "Entity-component design",
    question: "In the component-based asteroid game, the GameObject class contains only a Map from component class to component instance, with generic addComponent(Class, T) and getComponent(Class) methods, while MovementSystem and CollisionSystem contain the update and collision logic. What architectural idea does this separation illustrate?",
    options: ["Entities are lightweight containers of data components, and behavior lives in separate systems that operate on those components", "Entities must be immutable so that systems can safely share them between threads", "Systems are singletons that own all game state, and entities are just identifiers", "Each entity implements one system interface so the compiler can verify game logic"],
    answer: 0,
    explanation: "This is the entity-component(-system) style: GameObject is a generic container of data components, and systems like MovementSystem update PositionComponent from VelocityComponent without knowing which entity type they belong to. Behavior is decoupled from the entity hierarchy, which is exactly what the inheritance version lacked.",
    source: "exercise-based",
  },
  {
    week: 7,
    topic: "POM inheritance in child modules",
    question: "A child module's pom.xml in the course's multi-module calculator declares a parent block (groupId com.example, artifactId multi-module-calculator, version 1.0-SNAPSHOT) and then only its own artifactId, calculator-app. Why can it omit its own groupId and version?",
    options: ["Maven assigns a random groupId and version at build time for child modules", "Child modules never have a groupId or version; only artifactId identifies them", "They are inherited from the parent POM, so the child only needs to state what differs: its artifactId", "The values are read from the directory name of the module on disk"],
    answer: 2,
    explanation: "A child POM inherits groupId, version, and shared configuration (properties, pluginManagement, dependencyManagement) from its declared parent, so it only needs its own artifactId. The full coordinates still exist; they are just resolved through inheritance rather than repeated in every module.",
    source: "exercise-based",
  },
  {
    week: 7,
    topic: "Component thinking and module boundaries",
    question: "The course's 'component thinking' Maven example splits an age-calculator application into separate modules: one containing only the component interface, one with the implementation, and an application module that depends on the interface. What is the main benefit of putting the interface in its own Maven module?",
    options: ["It makes the final JAR smaller because interfaces compile to no bytecode", "Clients depend only on the stable contract, so implementations can be swapped or rebuilt without recompiling the clients against new code", "Maven requires interfaces and classes to be in different modules", "It allows the interface to be instantiated directly with the new keyword"],
    answer: 1,
    explanation: "Separating the contract from the implementation means the application module compiles only against the interface artifact, so any implementation honoring that contract can be substituted — the essence of component-based design (provided vs. required interfaces). Maven imposes no such rule itself, and interfaces still compile to bytecode.",
    source: "exercise-based",
  },

  // ===== Week 9 — ServiceLoader, Service Locator, JPMS =====
  {
    week: 9,
    topic: "META-INF/services registration",
    question: "In the course's ServiceLoader dictionary example, the provider JAR contains a file under META-INF/services that registers GeneralDictionary as an implementation of the dictionary.spi.Dictionary interface. How must this registration file be set up?",
    options: ["The file is named GeneralDictionary and contains the text dictionary.spi.Dictionary", "The file is named dictionary.spi.Dictionary (the fully qualified interface name) and contains the line dictionary.GeneralDictionary (the fully qualified implementation class)", "The file is named services.xml and lists interface-to-class mappings in XML", "The file may have any name as long as it sits in META-INF/services and contains both class names"],
    answer: 1,
    explanation: "The classpath-based ServiceLoader convention is: file name = fully qualified name of the service interface, file content = fully qualified names of the provider classes, one per line. Reversing the two (option A) is the classic mistake; ServiceLoader would then never find the provider.",
    source: "exercise-based",
  },
  {
    week: 9,
    topic: "Multiple service providers",
    question: "In the dictionary demo, both GeneralDictionary (defines 'book', 'editor') and ExtendedDictionary (defines 'xml', 'REST') are registered as providers of the same Dictionary service and both JARs are on the classpath. The lookup code iterates the ServiceLoader and returns the first non-null definition. What happens when the user looks up 'xml'?",
    options: ["ServiceLoader throws an error because two providers implement the same interface", "Only the first provider found is ever loaded, so 'xml' is never resolved", "ServiceLoader merges both dictionaries into a single map automatically", "The iterator yields every registered provider in turn; GeneralDictionary returns null for 'xml', so iteration continues and ExtendedDictionary supplies the definition"],
    answer: 3,
    explanation: "ServiceLoader is designed for multiple providers: its iterator discovers and yields all registered implementations, and it is the client's job to decide how to use them (here: try each until one knows the word). Having several providers is normal, not an error.",
    source: "exercise-based",
  },
  {
    week: 9,
    topic: "ServiceLoader lazy loading",
    question: "Consider the statement loader = ServiceLoader.load(Dictionary.class) as used in the course's DictionaryService. When are the provider classes actually instantiated?",
    options: ["Lazily: load() only sets up the loader, and each provider is located and instantiated as the iterator reaches it", "Eagerly: load() immediately scans the classpath and constructs every provider", "At JVM startup, before main() runs", "Only when the provider's static initializer is explicitly invoked by the client"],
    answer: 0,
    explanation: "ServiceLoader.load() is cheap; discovery and instantiation happen lazily during iteration, which is why a misconfigured provider surfaces as a ServiceConfigurationError while iterating rather than at load time. This lazy behavior is also why the demo wraps the iteration, not the load call, in a try/catch for ServiceConfigurationError.",
    source: "exercise-based",
  },
  {
    week: 9,
    topic: "Service Locator vs Dependency Injection",
    question: "The course's ServiceLocator demo uses a class with a static map of named services, and clients call ServiceLocator.getService(\"email\") to obtain a MessagingService. How does this Service Locator pattern fundamentally differ from dependency injection?",
    options: ["A service locator can only return singletons, while DI always creates new instances", "Service Locator requires an external framework like Spring, while DI works with plain Java", "With a locator the client actively pulls dependencies from a central registry it must know about; with DI an external party pushes dependencies into the client, which stays unaware of any registry", "There is no difference; Service Locator is simply the older name for dependency injection"],
    answer: 2,
    explanation: "The defining difference is the direction of control: the locator is queried by the client (which therefore depends on the locator and hides its real dependencies behind string keys), whereas DI hands dependencies to the client from outside, making them explicit and easier to test. Neither pattern inherently dictates singletons or requires a framework.",
    source: "exercise-based",
  },
  {
    week: 9,
    topic: "JPMS provides ... with",
    question: "In the JPMS version of the dictionary example, the dictionary.danish module supplies an implementation of the dictionary.api.Dictionary service. Which module-info.java declaration correctly registers it?",
    options: ["module dictionary.danish { exports dictionary.danish; uses dictionary.api.Dictionary; }", "module dictionary.danish { requires dictionary.api; provides dictionary.api.Dictionary with dictionary.danish.DanishDictionary; }", "module dictionary.danish { requires dictionary.api; implements dictionary.api.Dictionary; }", "module dictionary.danish { provides dictionary.danish.DanishDictionary with dictionary.api.Dictionary; }"],
    answer: 1,
    explanation: "A provider module must require the module that owns the service interface and declare 'provides <service interface> with <implementation class>'. 'uses' belongs in the consumer module, 'implements' is not a module-info keyword, and option D reverses the interface and implementation.",
    source: "exercise-based",
  },
  {
    week: 9,
    topic: "JPMS uses declaration",
    question: "In the modular dictionary app, the consumer module declares: requires dictionary.api; uses dictionary.api.Dictionary; and then calls ServiceLoader.load(Dictionary.class). What is the purpose of the 'uses' directive?",
    options: ["It re-exports the dictionary.api package to downstream modules", "It forces the app to bundle at least one Dictionary implementation at compile time", "It makes the Dictionary interface accessible; without it the import would not compile", "It tells the module system that this module consumes the Dictionary service, allowing ServiceLoader to bind any provider modules at runtime"],
    answer: 3,
    explanation: "'uses' declares service consumption so the module system can wire this module to modules that declare 'provides' for the same interface; ServiceLoader.load would find nothing (or fail) without it. Compile-time access to the interface type comes from 'requires dictionary.api', not from 'uses', and no implementation needs to exist at compile time.",
    source: "exercise-based",
  },
  {
    week: 9,
    topic: "ServiceLoader decoupling benefit",
    question: "In the course's dictionary application, a new Danish dictionary was added without modifying or recompiling the application module: a new provider module was simply placed on the module path. Which property of the ServiceLoader approach makes this possible?",
    options: ["The application is coded only against the Dictionary interface and discovers implementations at runtime, so new providers are picked up purely through their registration metadata", "ServiceLoader recompiles the application automatically when new JARs appear", "The Danish dictionary class extends the application's main class, inheriting its behavior", "The application reads a configuration file that lists every dictionary class name, which the developer updates by hand"],
    answer: 0,
    explanation: "ServiceLoader inverts the dependency: the app knows only the service interface, and providers announce themselves via META-INF/services entries or 'provides ... with' declarations, so deployment-time composition replaces compile-time coupling. No code in the consumer changes when providers are added or removed — this is the core 'plug-in' benefit the example demonstrates.",
    source: "exercise-based",
  },

  // ===== Week 10 — DI principles, decorator, pure DI =====
  {
    week: 10,
    topic: "Tight coupling without DI",
    question: "In the course's payment demo WITHOUT dependency injection, PaymentService's constructor contains: this.paymentProcessor = new CreditCardPaymentProcessor(); and the field is typed as the concrete CreditCardPaymentProcessor class. What is the main design problem this creates?",
    options: [
      "The new keyword is slower than letting a framework instantiate objects",
      "The constructor will throw an exception if CreditCardPaymentProcessor has dependencies of its own",
      "PaymentService is permanently bound to one concrete implementation, so swapping in another processor (e.g., PayPal) or a test double requires editing PaymentService itself",
      "Java does not allow final fields to be assigned inside a constructor",
    ],
    answer: 2,
    explanation: "Because PaymentService both chooses and creates its dependency, it is tightly coupled to one concrete class; changing or mocking the processor means changing PaymentService's source code. Performance of new is irrelevant here, and final fields are perfectly legal to assign in a constructor.",
    source: "exercise-based",
  },
  {
    week: 10,
    topic: "Constructor injection",
    question: "The DI version of the payment demo declares: public PaymentService(PaymentProcessor paymentProcessor) { this.paymentProcessor = paymentProcessor; } where PaymentProcessor is an interface. Which statement best describes the technique being used?",
    options: [
      "Constructor injection: the dependency is supplied from outside through the constructor, so PaymentService depends only on the interface and can receive any implementation",
      "Setter injection: the dependency is assigned through a mutator after the object is built",
      "Field injection: the framework reflectively writes the dependency directly into the field",
      "Service lookup: PaymentService asks a registry for an implementation at runtime",
    ],
    answer: 0,
    explanation: "Passing the collaborator as a constructor parameter is constructor injection; it allows the field to be final and guarantees the object is fully initialized at creation. Setter and field injection assign the dependency after construction, and a service lookup would have PaymentService actively fetching its own dependency, which is the opposite of injection.",
    source: "exercise-based",
  },
  {
    week: 10,
    topic: "Inversion of Control",
    question: "Comparing the two payment demos, the no-DI version has PaymentService create its own processor, while the DI version has main() create a CreditCardPaymentProcessor and pass it into PaymentService. Why is the DI version said to exhibit \"inversion of control\"?",
    options: [
      "Because the program's methods are now called in reverse order",
      "Because control flow moves from compile time to runtime",
      "Because the interface now controls which class implements it",
      "Because responsibility for creating and wiring dependencies is moved out of the class that uses them and given to an external party (here, the main method)",
    ],
    answer: 3,
    explanation: "IoC means a class no longer controls the construction of its own collaborators; an external composer (main, or later a container) decides what gets injected. It has nothing to do with reversing call order or moving compilation to runtime.",
    source: "exercise-based",
  },
  {
    week: 10,
    topic: "Testability with DI",
    question: "A student wants to unit test PaymentService.makePayment() without triggering real payment-processing logic. Why is this easy in the DI version of the course demo but hard in the no-DI version?",
    options: [
      "The DI version has fewer classes, so there is less code to test",
      "In the DI version the test can construct PaymentService with a fake PaymentProcessor implementation; in the no-DI version the real CreditCardPaymentProcessor is hard-wired inside the constructor and cannot be replaced",
      "The no-DI version cannot be compiled in a test environment because it lacks an interface",
      "JUnit only supports classes whose constructors take parameters",
    ],
    answer: 1,
    explanation: "With constructor injection a test simply passes a stub or mock that implements PaymentProcessor. The no-DI version always executes new CreditCardPaymentProcessor() internally, so the real dependency cannot be substituted without modifying the class. The other options describe nonexistent compiler or JUnit restrictions.",
    source: "exercise-based",
  },
  {
    week: 10,
    topic: "Decorator pattern intent",
    question: "In the course's coffee demo, MilkDecorator and SugarDecorator each extend an abstract CoffeeDecorator that implements the Coffee interface and holds a wrapped Coffee object. What is the primary intent of the Decorator pattern demonstrated here?",
    options: [
      "To guarantee only one instance of SimpleCoffee exists in the application",
      "To convert the Coffee interface into a different interface that clients expect",
      "To attach additional responsibilities (milk, sugar) to an object dynamically at runtime by wrapping it, as a flexible alternative to subclassing",
      "To hide the construction logic of complex Coffee objects behind a factory method",
    ],
    answer: 2,
    explanation: "Decorator adds behavior by wrapping an existing object that shares the same interface, so features can be stacked at runtime (coffee = new SugarDecorator(new MilkDecorator(coffee))). Option 0 is Singleton, option 1 is Adapter, and option 3 is Factory Method — different patterns with different intents.",
    source: "exercise-based",
  },
  {
    week: 10,
    topic: "Decorator vs inheritance",
    question: "Suppose the coffee demo had used inheritance instead, creating subclasses like MilkCoffee and SugarCoffee. Compared to that approach, what key advantage does the decorator solution from the exercise provide?",
    options: [
      "Combinations like \"milk and sugar\" can be composed at runtime by nesting wrappers, instead of requiring a separate subclass for every possible combination",
      "Decorators run faster because they avoid virtual method dispatch",
      "Decorators remove the need for the Coffee interface entirely",
      "Inheritance cannot override getCost(), so decorators are the only way to change the price",
    ],
    answer: 0,
    explanation: "With static inheritance you would need a class for each combination (MilkSugarCoffee, etc.), causing a class explosion; decorators compose features dynamically by wrapping. Decorators actually rely on the shared Coffee interface and still use polymorphic dispatch, so the other options are false.",
    source: "exercise-based",
  },
  {
    week: 10,
    topic: "Pure DI without a framework",
    question: "The refactored notification-system demo (before Spring is introduced) has main() build the service like this: new NotificationService(Arrays.asList(new EmailNotifier(), new SMSNotifier(), new PushNotifier())). What does this example show about dependency injection?",
    options: [
      "DI always requires a container such as Spring to manage object creation",
      "Lists of dependencies can only be injected via setter methods",
      "This is service location, not dependency injection, because main() knows the concrete classes",
      "DI is a design principle independent of any framework: a plain main method can act as the \"composition root\" that creates and wires the objects manually",
    ],
    answer: 3,
    explanation: "This is \"pure DI\": NotificationService just declares what it needs (a List<Notifier>) and an ordinary main method composes the concrete objects — no framework involved. It is genuine injection because the service receives its dependencies rather than fetching or creating them; the composition root is supposed to know the concrete classes.",
    source: "exercise-based",
  },

  // ===== Week 11 — Spring DI, lifecycle, AOP =====
  {
    week: 11,
    topic: "XML vs annotation configuration",
    question: "The course showed two Spring configuration styles: a beans.xml file declaring <bean id=\"helloWorldBean\" class=\"...HelloWorld\"> with a <property> element, and an annotation approach using @Configuration plus @ComponentScan with @Component on the classes. Which statement about the tradeoff is most accurate?",
    options: [
      "Annotations are required for setter injection; XML only supports constructor injection",
      "XML configuration is deprecated and no longer works in current Spring versions",
      "XML keeps wiring fully external to the source code (the class needs no Spring imports), while annotations are more concise but embed Spring metadata in the classes themselves",
      "XML configuration is type-checked by the Java compiler, while annotations are only checked at runtime",
    ],
    answer: 2,
    explanation: "In the XML demo, HelloWorld is a plain class with no Spring annotations — all wiring lives in beans.xml — whereas the annotation demo marks classes with @Component/@Service, coupling them to Spring but eliminating external config. XML is verbose but not deprecated, both styles support setter and constructor injection, and XML is checked at runtime, not by the Java compiler.",
    source: "exercise-based",
  },
  {
    week: 11,
    topic: "Component scanning",
    question: "The Spring annotation demo defines: @Configuration @ComponentScan(basePackages = \"dk.sdu.cbs.annotation.example\") public class AppConfig {}. What does the @ComponentScan annotation cause Spring to do when the context starts?",
    options: [
      "It compiles all Java files in the given package before the application runs",
      "It searches the given package (and subpackages) for classes annotated with stereotypes like @Component or @Service and automatically registers them as beans in the container",
      "It scans the package for XML files and merges them into the configuration",
      "It injects every class found in the package into every other class",
    ],
    answer: 1,
    explanation: "Component scanning is classpath scanning for stereotype-annotated classes, which become managed beans without explicit registration. It does not compile code, look for XML, or perform any injection by itself — injection still happens only where @Autowired (or constructor resolution) requests a dependency.",
    source: "exercise-based",
  },
  {
    week: 11,
    topic: "@Autowired collection injection",
    question: "In the Spring version of the notification system, EmailNotifier, SMSNotifier, and PushNotifier are each annotated @Component and implement Notifier. NotificationService has: @Autowired public NotificationService(List<Notifier> notifiers). What happens when Spring creates NotificationService?",
    options: [
      "Spring finds all beans implementing Notifier and injects them together as the list, so all three notifiers are wired in without any manual new calls",
      "Spring throws an ambiguity error because three beans match the Notifier type",
      "Spring injects only the first @Component it discovered and ignores the others",
      "Spring injects an empty list; the notifiers must still be added manually in main()",
    ],
    answer: 0,
    explanation: "When the injection target is a collection of an interface type, Spring gathers every matching bean and injects them all — this is exactly how the demo replaces the manual Arrays.asList(...) wiring. An ambiguity error (resolvable with @Qualifier) only occurs when a single instance of the type is requested and multiple candidates exist.",
    source: "exercise-based",
  },
  {
    week: 11,
    topic: "@Qualifier and ambiguity",
    question: "Suppose the Spring annotation demo's MyServiceConsumer asked for a single MyService in its constructor, but two beans (MyServiceImplA and MyServiceImplB) both implement MyService. What is the standard way to make the injection succeed?",
    options: [
      "Annotate both implementations with @Configuration so Spring merges them",
      "Remove @Component from one class and instantiate it with new inside the consumer",
      "Add @Qualifier with the desired bean's name at the injection point so Spring knows which candidate to choose",
      "Inject the dependency twice and let Spring discard the duplicate",
    ],
    answer: 2,
    explanation: "@Autowired resolves by type, so two candidates of the same type cause a NoUniqueBeanDefinitionException; @Qualifier (or marking one bean @Primary) disambiguates by name. Reverting to new inside the consumer would reintroduce the tight coupling DI was meant to remove.",
    source: "exercise-based",
  },
  {
    week: 11,
    topic: "Bean scopes",
    question: "The course's beans.xml declares the bean with scope=\"prototype\", and the lecturer demonstrated that calling getBean(\"helloWorldBean\") twice then returns different objects. What is true about Spring bean scopes?",
    options: [
      "The default scope is prototype, so every getBean call always returns a fresh object unless singleton is requested",
      "Prototype beans are shared across the application, while singleton beans are created per request",
      "Scope only affects beans defined in XML; annotated beans are always prototype",
      "The default scope is singleton (one shared instance per container); prototype must be requested explicitly and yields a new instance on each request, which Spring does not destroy for you",
    ],
    answer: 3,
    explanation: "Singleton is Spring's default: the container creates and caches one instance and hands the same object back on every lookup. Prototype is opt-in (scope=\"prototype\" or @Scope(\"prototype\")), creates a new instance per request, and Spring does not call destroy callbacks on prototypes — a point also noted in the lifecycle demo.",
    source: "exercise-based",
  },
  {
    week: 11,
    topic: "Bean lifecycle order",
    question: "The lifecycle demo's MyLifecycleBean prints messages from its constructor, an @PostConstruct init() method, a useBean() business method, and an @PreDestroy destroy() method, and main() ends with context.close(). In what order do these messages appear?",
    options: [
      "Constructor, then @PostConstruct, then the business method, then @PreDestroy when the context is closed",
      "@PostConstruct, then constructor, then the business method, then @PreDestroy",
      "Constructor, then the business method, then @PostConstruct, then @PreDestroy",
      "@PreDestroy, then constructor, then @PostConstruct, then the business method",
    ],
    answer: 0,
    explanation: "Spring must first instantiate the bean (constructor) and inject its dependencies, after which @PostConstruct runs as the initialization callback; the bean is then used, and @PreDestroy runs only when the container shuts down (context.close()). @PostConstruct can never precede the constructor because the object must exist before any callback can run on it.",
    source: "exercise-based",
  },
  {
    week: 11,
    topic: "AOP concepts and pointcut syntax",
    question: "The course's AOP demo contains: @Before(\"execution(* dk.sdu.cbs.demo.service.*.*(..))\") public void logAllMethodExecutionBefore(JoinPoint jp) {...} inside a class annotated @Aspect @Component. Which statement correctly maps this code to AOP terminology?",
    options: [
      "The string expression is the advice, and logAllMethodExecutionBefore is the join point",
      "execution(...) selects which classes become Spring beans, replacing @ComponentScan",
      "@Before makes the method run after the matched methods return, but before the application exits",
      "The execution(...) expression is a pointcut selecting join points (here: any method, any return type, in any class of the service package), and the logAllMethodExecutionBefore method is the advice that runs before each matched method",
    ],
    answer: 3,
    explanation: "In AOP vocabulary the pointcut expression selects join points (points in execution, such as method calls), and the annotated method is the advice — @Before advice runs before the matched method executes. In execution(* pkg.*.*(..)) the wildcards mean any return type, any class in the package, any method name, and (..) matches any parameters; the expression has nothing to do with bean registration.",
    source: "exercise-based",
  },

  // ===== Week 12 — Spring Boot, Security, Actuator =====
  {
    week: 12,
    topic: "Spring Boot starters & auto-configuration",
    question: "The course's Spring Boot security demo simply adds the spring-boot-starter-security and spring-boot-starter-actuator dependencies to the pom.xml, and security filters and management endpoints become active without any servlet or filter registration code. What Spring Boot mechanism makes this possible?",
    options: [
      "The Java module system automatically links security modules at compile time",
      "Spring Boot scans the developer's source code for security-related class names and enables matching features",
      "Auto-configuration detects libraries on the classpath and conditionally registers the beans they need with sensible defaults",
      "The starters contain pre-compiled application code that replaces the developer's main class",
    ],
    answer: 2,
    explanation: "Starters pull in curated dependencies, and Spring Boot's auto-configuration uses conditional logic (e.g., @ConditionalOnClass) to register beans when those libraries are detected on the classpath. It is driven by classpath contents and configuration properties, not by scanning the developer's source code for naming patterns.",
    source: "exercise-based",
  },
  {
    week: 12,
    topic: "@SpringBootApplication composition",
    question: "Every Spring Boot project in the course (security demo, RabbitMQ demos, Swagger API) has a main class annotated with @SpringBootApplication. Which combination of annotations does @SpringBootApplication effectively bundle together?",
    options: [
      "@Configuration, @EnableAutoConfiguration, and @ComponentScan",
      "@RestController, @RequestMapping, and @ResponseBody",
      "@Bean, @Autowired, and @Component",
      "@EnableWebSecurity, @EnableScheduling, and @EnableCaching",
    ],
    answer: 0,
    explanation: "@SpringBootApplication is a convenience annotation combining @Configuration (the class can define beans), @EnableAutoConfiguration (activate Spring Boot's auto-configuration), and @ComponentScan (discover components in the package and below). The other options are either web-layer or feature-specific annotations that must be added explicitly.",
    source: "exercise-based",
  },
  {
    week: 12,
    topic: "Actuator purpose",
    question: "In the course's Spring Boot demo, the Actuator dependency adds endpoints such as /actuator/health and /actuator/metrics. What is the primary purpose of Spring Boot Actuator?",
    options: [
      "To generate REST controllers automatically from the database schema",
      "To expose production-ready monitoring and management information about the running application, such as health status and metrics",
      "To accelerate application startup by precomputing the bean graph",
      "To provide a built-in browser UI for testing REST endpoints",
    ],
    answer: 1,
    explanation: "Actuator gives operational insight into a running application: /health reports whether the app (and its dependencies) are up, and /metrics exposes runtime measurements like memory and request counts. It is about monitoring and management, not code generation, startup speed, or API testing (that is Swagger UI's job).",
    source: "exercise-based",
  },
  {
    week: 12,
    topic: "Securing actuator endpoints",
    question: "The course demo sets management.endpoints.web.exposure.include=* to expose every actuator endpoint over HTTP, but its security configuration only permits anonymous access to /actuator/health and /actuator/info, requiring authentication for the rest. Why is this restriction important?",
    options: [
      "Unsecured actuator endpoints make the application fail Spring Boot's startup validation",
      "Actuator endpoints consume so much CPU that they must be rate-limited through login",
      "Actuator endpoints only work over HTTPS, and authentication enables the TLS handshake",
      "Endpoints like /actuator/env and /actuator/metrics can leak sensitive internals (configuration values, system details) that attackers could exploit",
    ],
    answer: 3,
    explanation: "Many actuator endpoints reveal internal details such as environment variables, configuration properties, and runtime metrics, which are valuable to attackers; only low-sensitivity endpoints like /health and /info are commonly left open for load balancers and monitoring. The other options are false: Spring Boot does not refuse to start, and actuator neither requires TLS nor imposes heavy CPU load.",
    source: "exercise-based",
  },
  {
    week: 12,
    topic: "Spring Security filter chain",
    question: "In the course demo, security is configured by declaring a SecurityFilterChain bean that permits requests to \"/\" and \"/api/public\" while requiring authentication for any other request, with form login and HTTP Basic enabled. How does Spring Security enforce these rules at runtime?",
    options: [
      "The compiler injects authentication checks into each controller method during the build",
      "Every incoming HTTP request passes through a chain of servlet filters that apply authentication and authorization rules before the request reaches the controller",
      "The database driver validates credentials on every SQL query the controller issues",
      "Each @RestController re-implements the rules by reading the SecurityConfig class via reflection",
    ],
    answer: 1,
    explanation: "Spring Security is built around a chain of servlet filters that intercept every request before it reaches the application's controllers, performing authentication (e.g., form login or HTTP Basic) and matching the request against the authorization rules. Controllers themselves contain no security logic, which is exactly why the demo's controller code stays unchanged when security rules change.",
    source: "exercise-based",
  },
  {
    week: 12,
    topic: "Default security behavior",
    question: "A student adds spring-boot-starter-security to a Spring Boot project but defines no SecurityFilterChain or user configuration at all. What is Spring Boot's default behavior when the application starts?",
    options: [
      "All endpoints remain publicly accessible until a security configuration class is written",
      "The application fails to start with an error demanding a SecurityConfig class",
      "All HTTP endpoints are secured, and a default user named \"user\" with a randomly generated password (printed in the console log) is created",
      "Only POST, PUT and DELETE requests require authentication; GET requests stay open",
    ],
    answer: 2,
    explanation: "Spring Security's auto-configuration is secure by default: with the starter on the classpath and no custom configuration, every endpoint requires authentication, and a single in-memory user \"user\" is created with a random password logged at startup. The demo overrides this by supplying its own SecurityFilterChain and an InMemoryUserDetailsManager with fixed credentials.",
    source: "exercise-based",
  },

  // ===== Week 13 — SOAP/WSDL, RabbitMQ, Swagger =====
  {
    week: 13,
    topic: "WSDL as a service contract",
    question: "The course's SOAP demo publishes a Java service with @WebService and @WebMethod methods (add, multiply, helloWorld) at an address where appending ?wsdl returns a WSDL document. What role does the WSDL play?",
    options: [
      "It is a machine-readable contract describing the service's operations, message formats, data types, and endpoint location",
      "It is the runtime log of all SOAP calls made against the service",
      "It is a JSON schema used by browsers to render a testing UI for the service",
      "It is the compiled bytecode of the service that clients download and execute locally",
    ],
    answer: 0,
    explanation: "WSDL (Web Services Description Language) is an XML document that formally specifies what operations a SOAP service offers, the structure of request and response messages, and where the service lives, so clients can be built against it without seeing the server's source code. It is a contract, not a log, a UI schema (that is closer to OpenAPI/Swagger for REST), or executable code.",
    source: "exercise-based",
  },
  {
    week: 13,
    topic: "SOAP consumer binding",
    question: "In the course's SOAP exercise, the Python consumer uses the zeep library: it is given only the WSDL URL of the running Java service and can then call client.service.add(10, 15) as if it were a local function. How is this possible?",
    options: [
      "The Python consumer imports the Java service class directly through a JVM bridge",
      "zeep guesses the available methods by sending trial HTTP requests to common operation names",
      "The Java service serializes its objects with Java serialization, which zeep deserializes natively",
      "zeep parses the WSDL at runtime to discover the operations and their types, then builds and sends the corresponding SOAP XML envelopes over HTTP",
    ],
    answer: 3,
    explanation: "The WSDL fully describes the operations and message schemas, so zeep can generate proxy methods dynamically and translate each call into a SOAP XML envelope posted over HTTP. No Java is involved on the client side, which is precisely the interoperability benefit of a contract-based protocol: any language with a SOAP library can consume the service.",
    source: "exercise-based",
  },
  {
    week: 13,
    topic: "RabbitMQ component roles",
    question: "In the course's RabbitMQ demos, a Spring Boot REST controller hands a message to a producer, RabbitMQ stores it, and a separate listener prints it later. Which statement correctly describes the roles of the messaging components?",
    options: [
      "The queue executes consumer code inside the broker; consumers only fetch the results",
      "The producer publishes messages to the broker, where an exchange routes them into queues; consumers receive messages from the queues they subscribe to",
      "The producer writes messages directly into each consumer's memory; the queue is only a backup copy",
      "The consumer routes messages to the exchange, which forwards them to the producer for acknowledgment",
    ],
    answer: 1,
    explanation: "In AMQP, producers never deliver to consumers directly: they publish to the broker, an exchange routes each message to zero or more queues based on bindings and routing keys, and consumers subscribe to queues (in the demo via @RabbitListener in Java or basic_consume in Python). Queues buffer messages; they do not execute consumer logic.",
    source: "exercise-based",
  },
  {
    week: 13,
    topic: "Fanout vs direct routing",
    question: "The course had two RabbitMQ demos. In the work-queue demo, the producer sends each message addressed to one named durable queue, while in the pub/sub demo the producer publishes to a fanout exchange with an empty routing key, and both a Spring queue and a separate Python queue are bound to it. Why does the pub/sub demo use a fanout exchange?",
    options: [
      "Fanout exchanges are the only exchange type that supports durable queues",
      "Fanout exchanges compress messages so multiple consumers can read them faster",
      "A fanout exchange broadcasts a copy of every message to all bound queues, ignoring routing keys, so every subscriber receives every message",
      "A fanout exchange load-balances each message to exactly one of the bound queues",
    ],
    answer: 2,
    explanation: "Fanout exchanges ignore the routing key and deliver a copy of each message to every queue bound to them, which is exactly the publish/subscribe pattern: in the demo both the Spring consumer and the Python consumer received every message because each had its own bound queue. Option D describes the work-queue pattern, where multiple consumers share one queue and each message goes to only one of them.",
    source: "exercise-based",
  },
  {
    week: 13,
    topic: "Asynchronous decoupling",
    question: "In the course's RabbitMQ work-queue demo, the REST endpoint returns \"Message sent to RabbitMQ\" immediately after publishing, even if no consumer is currently running; the durable queue holds the message until a consumer starts. What architectural benefit of message-based integration does this illustrate?",
    options: [
      "Messaging guarantees that every message is processed in under one second",
      "Producer and consumer are decoupled in time and availability: the producer does not block waiting for, or even require, a running consumer",
      "Messaging removes the need for any network communication between components",
      "The broker converts messages into direct synchronous method calls on the consumer",
    ],
    answer: 1,
    explanation: "Asynchronous messaging decouples sender and receiver: the producer publishes and moves on, the broker buffers the message (durably, in the demo), and the consumer processes it whenever it is available, which improves resilience and lets components scale independently. Messaging gives no latency guarantee and still uses the network; it replaces synchronous calls rather than performing them.",
    source: "exercise-based",
  },
  {
    week: 13,
    topic: "Cross-language interoperability",
    question: "In the course exercises, messages published by a Java Spring Boot producer were consumed both by a Java @RabbitListener and by a Python script using the pika library, with no shared code between them. What makes this cross-language interoperability possible?",
    options: [
      "RabbitMQ implements the open AMQP wire protocol, so any client library in any language that speaks AMQP can publish to and consume from the same broker",
      "The Python pika library embeds a JVM that runs the Spring AMQP classes",
      "RabbitMQ automatically translates Java objects into Python objects inside the broker",
      "Both consumers must be compiled against the same shared interface JAR",
    ],
    answer: 0,
    explanation: "AMQP is a standardized, language-neutral wire protocol: the broker deals with byte payloads and protocol frames, not language-specific objects, so Java (Spring AMQP) and Python (pika) clients interoperate as long as they agree on queue/exchange names and the message format. There is no JVM in pika and no shared compiled artifacts; the protocol itself is the contract.",
    source: "exercise-based",
  },
  {
    week: 13,
    topic: "Swagger/OpenAPI documentation",
    question: "The course's Swagger demo adds the springdoc-openapi starter to a Spring Boot REST API, after which a machine-readable description appears at /v3/api-docs and an interactive page at /swagger-ui. What does this OpenAPI documentation primarily provide, and why do REST APIs use it?",
    options: [
      "It encrypts API traffic so that only documented clients can call the endpoints",
      "It replaces the REST controllers with auto-generated server stubs at runtime",
      "It records performance metrics for each endpoint, similar to Spring Boot Actuator",
      "It describes the API's endpoints, HTTP methods, parameters, and responses in a standard format, serving as a contract that humans can browse and tools can use to generate clients or test calls",
    ],
    answer: 3,
    explanation: "OpenAPI (served by springdoc at /v3/api-docs, rendered by Swagger UI) is a standardized, machine-readable description of a REST API generated from the controllers and annotations, playing a role for REST similar to what WSDL does for SOAP: consumers can read it, generate client code from it, and try out calls interactively. It documents the API; it does not secure traffic, replace controllers, or collect metrics.",
    source: "exercise-based",
  },

  // ===== Week 16 — gRPC, Eureka, API Gateway =====
  {
    week: 16,
    topic: "Protocol Buffers as IDL",
    question: "In the course gRPC demo, both the Python server project and the Java client project contain an identical person.proto file defining PersonService and its messages. What is the primary role of this .proto file?",
    options: [
      "It is a configuration file that tells the gRPC runtime which port and hostname the server should listen on.",
      "It is Python source code that the Java project must translate by hand into equivalent Java classes.",
      "It is a language-neutral interface definition (contract) from which protoc generates message classes and client/server stubs for each language.",
      "It is documentation only; gRPC discovers the service methods at runtime via reflection, so the file is optional.",
    ],
    answer: 2,
    explanation: "The .proto file is an Interface Definition Language (IDL) contract: protoc compiles it into generated code (person_pb2.py for Python, PersonProto/PersonServiceGrpc for Java), so both sides agree on the same interface. It is not runtime configuration and not optional documentation — the generated stubs are exactly what client and server code program against.",
    source: "exercise-based",
  },
  {
    week: 16,
    topic: "Proto field numbers",
    question: "A .proto message is defined as: message Person { string name = 1; int32 age = 2; repeated string emails = 3; }. What is the purpose of the numbers 1, 2 and 3, and why must they not be changed once the message is in use?",
    options: [
      "They are unique tags identifying each field in the binary wire format; changing them breaks compatibility between already-deployed clients and servers.",
      "They are default values assigned to the fields when the sender does not provide them.",
      "They define the order in which fields must be set in code; setting fields out of order raises a runtime error.",
      "They indicate the maximum number of times each field may appear in a single message.",
    ],
    answer: 0,
    explanation: "Protobuf does not serialize field names; it serializes each value tagged with its field number, which is how the receiver knows which field a value belongs to. If you renumber fields, an old client and a new server will silently misinterpret each other's data — field numbers are the stable part of the contract, while names can be renamed safely.",
    source: "exercise-based",
  },
  {
    week: 16,
    topic: "gRPC transport and serialization",
    question: "Compared to a typical REST API that sends JSON over HTTP/1.1, which statement best characterizes how gRPC transmits a PersonRequest between client and server?",
    options: [
      "gRPC sends human-readable JSON but compresses it with gzip, which is why it is faster than REST.",
      "gRPC sends XML envelopes over HTTP/1.1, similar to SOAP, but with stricter schemas.",
      "gRPC uses plain TCP sockets with no application protocol, so messages must include their own length headers.",
      "gRPC serializes messages into a compact binary Protocol Buffers format and transports them over HTTP/2, enabling multiplexed streams on one connection.",
    ],
    answer: 3,
    explanation: "gRPC encodes messages as compact binary protobuf (smaller and faster to parse than text JSON) and runs over HTTP/2, which provides multiplexing of many concurrent calls and streaming over a single connection. It is not JSON, not XML/SOAP, and not raw TCP.",
    source: "exercise-based",
  },
  {
    week: 16,
    topic: "gRPC RPC types",
    question: "The demo service declares: rpc GetPersonInfo (PersonRequest) returns (PersonResponse);. Which kind of gRPC call is this, and which other kinds does gRPC support?",
    options: [
      "It is a server-streaming call; the only other kind gRPC supports is unary.",
      "It is a unary call (one request, one response); gRPC also supports server-streaming, client-streaming, and bidirectional-streaming RPCs declared with the stream keyword.",
      "It is a bidirectional-streaming call because both a request and a response type are declared.",
      "It is a publish-subscribe call; gRPC delivers the response asynchronously to all subscribed clients.",
    ],
    answer: 1,
    explanation: "Without the stream keyword on either side, the RPC is unary: the client sends exactly one request and receives exactly one response, as the blocking stub call in the demo shows. Adding stream to the request, the response, or both yields client-streaming, server-streaming, or bidirectional-streaming RPCs — declaring both a request and response type does not make a call streaming.",
    source: "exercise-based",
  },
  {
    week: 16,
    topic: "Cross-language interoperability",
    question: "In the course exercise, a Java client successfully calls GetPersonInfo on a gRPC server written in Python. What makes this cross-language call work without any translation code written by the developer?",
    options: [
      "The Java client embeds a Python interpreter that runs the server's stub code locally.",
      "The Python server detects that the caller is Java and switches its responses to Java object serialization.",
      "Both sides generate code from the same .proto contract, and the wire format (protobuf over HTTP/2) is language-independent, so any generated client can talk to any generated server.",
      "gRPC converts all messages to JSON at the boundary, since JSON is the only format both languages understand.",
    ],
    answer: 2,
    explanation: "Each language's protoc plugin generates native stubs (a Java BlockingStub, a Python Servicer) from the identical .proto file, and the binary protobuf wire format is the same regardless of language. The server neither knows nor cares what language the client is written in — interop comes from the shared contract and standard wire protocol, not from JSON conversion.",
    source: "exercise-based",
  },
  {
    week: 16,
    topic: "Eureka service discovery",
    question: "In the Spring Cloud exercise, each microservice's application.yml sets spring.application.name (e.g. order-service) and eureka.client.service-url.defaultZone: http://localhost:8761/eureka, while the discovery server itself uses @EnableEurekaServer with register-with-eureka: false. What core problem does this Eureka setup solve?",
    options: [
      "It eliminates the need for each microservice to have its own HTTP port, since all traffic flows through port 8761.",
      "It encrypts inter-service traffic so that services can safely call each other over public networks.",
      "It merges all microservice databases into one shared registry database to keep data consistent.",
      "It removes hardcoded service URLs: services register themselves by name at startup, and other services look up current instance locations from the registry at runtime.",
    ],
    answer: 3,
    explanation: "Eureka is a service registry: each client registers under its application name and consumers resolve names like order-service to actual host:port instances dynamically, which is essential when instances scale, move, or restart. Eureka does not proxy traffic (services still have their own ports), and it provides discovery, not encryption or data storage — the register-with-eureka: false setting simply stops the server from registering with itself.",
    source: "exercise-based",
  },
  {
    week: 16,
    topic: "API Gateway purpose",
    question: "The course API gateway runs on port 8080 with config like: spring.cloud.gateway.routes: - id: order-service, uri: http://localhost:8082, predicates: - Path=/orders/**. Why introduce such a gateway in front of the user, order, and payment services?",
    options: [
      "It gives clients a single entry point that routes requests to the right backend service based on predicates (e.g. path), and centralizes cross-cutting concerns like authentication, rate limiting, and logging.",
      "It replaces the backend services entirely by caching all their responses, so the services only run during cache misses.",
      "It is required by HTTP/2, which does not allow browsers to connect to more than one server port.",
      "It guarantees ACID transactions across the three services by coordinating their database commits.",
    ],
    answer: 0,
    explanation: "An API gateway provides one stable entry point: route predicates such as Path=/orders/** forward each request to the matching service, and filters let you apply security, throttling, and monitoring in one place instead of in every service. It is a router for cross-cutting concerns, not a cache replacement and certainly not a distributed transaction coordinator.",
    source: "exercise-based",
  },

  // ===== Week 17 — Saga, distributed transactions =====
  {
    week: 17,
    topic: "Why not 2PC across microservices",
    question: "In the saga demo, the order, payment, stock, and delivery microservices each have their own private H2 database. Why can't a single ACID transaction (or classic two-phase commit) simply span all four services when an order is placed?",
    options: [
      "Because H2 is an in-memory database and in-memory databases never support transactions of any kind.",
      "Because Kafka messages are always processed in random order, making any transactional guarantee impossible.",
      "Because each service owns a separate database with no shared transaction manager, and 2PC across services would require holding locks while waiting on remote participants — hurting availability and coupling the services tightly.",
      "Because Java's @Transactional annotation only works inside a monolith and is removed by the compiler in microservice projects.",
    ],
    answer: 2,
    explanation: "With database-per-service there is no single transactional resource to commit atomically, and distributed 2PC blocks resources across service boundaries, undermining the autonomy and availability that microservices are chosen for. That is why the demo uses a saga — a sequence of local transactions coordinated through events — rather than one global ACID transaction; the limitation has nothing to do with H2 or @Transactional per se.",
    source: "exercise-based",
  },
  {
    week: 17,
    topic: "Choreography vs orchestration",
    question: "In the course saga demo, the Order service emits ORDER_CREATED to Kafka, the Payment service listens and emits PAYMENT_CREATED, the Stock service listens and emits STOCK_UPDATED, and the Delivery service completes the flow. What makes this a CHOREOGRAPHY-based saga rather than an ORCHESTRATION-based one?",
    options: [
      "Choreography means the services call each other with synchronous REST requests instead of messages.",
      "There is no central coordinator: each service reacts to events from the previous step and publishes its own events, so the workflow logic is distributed across the participants.",
      "Choreography requires Kafka specifically; using RabbitMQ would automatically make it an orchestrated saga.",
      "A choreographed saga can only roll forward; only orchestrated sagas can perform rollbacks.",
    ],
    answer: 1,
    explanation: "In choreography the saga's control flow emerges from services subscribing to each other's events, with no central brain; in orchestration a dedicated coordinator explicitly tells each participant what to do next and tracks saga state. The broker technology is irrelevant to the distinction, and choreographed sagas can roll back too — the demo does exactly that with reversal events.",
    source: "exercise-based",
  },
  {
    week: 17,
    topic: "Compensating transactions",
    question: "In the saga demo, when the Stock service finds insufficient inventory after payment has already succeeded, it publishes a PAYMENT_REVERSED event; the Payment service then marks the payment FAILED and publishes ORDER_REVERSED, and the Order service marks the order FAILED. What saga concept does this chain illustrate?",
    options: [
      "Compensating transactions: since the earlier local commits cannot be rolled back with a database ROLLBACK, each service runs a new local transaction that semantically undoes its previous step, propagating backwards through the saga.",
      "Two-phase commit: the stock service acts as the transaction coordinator and vetoes the global commit in the voting phase.",
      "Idempotent retry: the system automatically replays the payment until enough stock becomes available.",
      "Optimistic locking: the version number on the order row prevents the conflicting update from being applied.",
    ],
    answer: 0,
    explanation: "Once a step in a saga has committed locally, it can only be undone by an explicit compensating action — a new transaction that reverses the business effect (refund the payment, fail the order) — triggered by reversal events flowing backwards through the chain. This is fundamentally different from 2PC, where nothing is durably committed until the coordinator says so.",
    source: "exercise-based",
  },
  {
    week: 17,
    topic: "Eventual consistency",
    question: "In the saga demo's README, after placing an order that will fail in the Delivery service, the student is told to \"wait a few seconds\" before re-querying: the order first shows status CREATED and only later flips to FAILED. Which consistency model does this behavior demonstrate, and why is it inherent to event-driven sagas?",
    options: [
      "Strong consistency — all services see the same state at every instant because Kafka serializes all writes.",
      "Read-your-writes consistency — the order service can never observe its own stale data, only other services can.",
      "Linearizability — the FAILED status is logically applied at the moment the order was created, so the delay is only a UI artifact.",
      "Eventual consistency — each service commits locally and propagates changes asynchronously via events, so different services (and queries) may briefly see divergent states until all events are processed.",
    ],
    answer: 3,
    explanation: "Sagas trade the instantaneous all-or-nothing guarantee of ACID for availability: each local transaction commits immediately and reversal events take time to flow through the broker, so intermediate states like a CREATED order with a failed delivery are observable. The system converges to a correct final state (FAILED) — that convergence-over-time guarantee is eventual consistency, not strong consistency or linearizability.",
    source: "exercise-based",
  },
  {
    week: 17,
    topic: "Database-per-service and event design",
    question: "Each microservice in the saga demo (order, payment, stock, delivery) writes only to its own database and communicates through Kafka events such as ORDER_CREATED carrying the order data. Which statement best captures a key implication of this database-per-service design?",
    options: [
      "Services can simply run SQL joins across each other's tables, since Kafka synchronizes the schemas automatically.",
      "Because no service can directly read or update another service's data, all cross-service state changes must travel as events (or API calls), and the events must carry enough information (e.g. orderId, item, quantity, amount) for the receiver to act independently.",
      "Database-per-service means every service must use a different database vendor to avoid coupling.",
      "The pattern removes the need for compensating transactions because each database is small enough to roll back instantly.",
    ],
    answer: 1,
    explanation: "Database-per-service enforces encapsulation: the only way the Payment service learns about a new order is through the ORDER_CREATED event, which therefore must be self-contained with the data the consumer needs. The pattern says nothing about vendor diversity, prohibits cross-database joins rather than enabling them, and is precisely the reason compensating transactions become necessary.",
    source: "exercise-based",
  },
  {
    week: 17,
    topic: "Saga failure-path variations",
    question: "In the demo, a payment failure (amount > 1000) makes the Payment service emit ORDER_REVERSED directly, whereas a delivery failure triggers the full chain STOCK_REVERSED then PAYMENT_REVERSED then ORDER_REVERSED. Why do the two failure scenarios produce reversal chains of different lengths?",
    options: [
      "Only the local transactions that have already committed before the failure need compensating: a payment failure has nothing downstream to undo, while a delivery failure must unwind the stock deduction and the payment first.",
      "Kafka drops some reversal events under load, so shorter chains are an optimization to reduce message loss.",
      "The Payment service is the saga orchestrator, so it is allowed to skip steps that other services must perform.",
      "Delivery failures are more severe, so the saga performs every compensation twice to be safe.",
    ],
    answer: 0,
    explanation: "Compensation must undo exactly the steps that succeeded before the failure point: if payment itself fails, no stock was deducted and no delivery scheduled, so only the order needs reversing; if delivery fails last, stock and payment commits must each be compensated in reverse order. There is no orchestrator in this choreographed saga — each service just knows which reversal event to emit for its predecessor.",
    source: "exercise-based",
  },

  // ===== Week 18 — Component/integration testing, observability =====
  {
    week: 18,
    topic: "Component vs unit testing",
    question: "In the week 18 demo, UserServiceComponentTest exercises the UserService through its public methods (createUser, listUsers, getUser, deleteUser) while replacing the UserRepository with a Mockito mock. What primarily characterizes this as a COMPONENT test rather than a plain unit test of a single method?",
    options: [
      "It starts the full Spring application context before each test",
      "It requires a real database so the repository behaves authentically",
      "It validates the component's complete behavior through its provided interface, isolating it by mocking its external collaborators",
      "It tests several components together to check their wiring",
    ],
    answer: 2,
    explanation: "Component testing treats the component as a black box and verifies its contract (the provided interface) while mocking required dependencies like the repository. No Spring context or real database is started, and only one component is under test, so options about full context, real DB, or multiple components describe other test levels.",
    source: "exercise-based",
  },
  {
    week: 18,
    topic: "Purpose of mocking",
    question: "The component-testing demo replaces UserRepository with Mockito.mock(UserRepository.class) so tests run without any database. What is the main benefit this mocking provides?",
    options: [
      "The service logic can be tested in isolation, fast and deterministically, without standing up real external dependencies",
      "The mock proves that the real repository implementation is bug-free",
      "It increases test coverage of the repository's SQL queries",
      "It makes the tests exercise real network and persistence failures",
    ],
    answer: 0,
    explanation: "Mocks isolate the component under test: failures then point to the component itself, and tests are fast and repeatable because no database or network is involved. A mock says nothing about the real repository's correctness — that must be covered by integration tests.",
    source: "exercise-based",
  },
  {
    week: 18,
    topic: "Mockito mechanics",
    question: "A test contains: when(mockRepository.findById(\"1\")).thenReturn(Optional.of(user)); followed later by verify(mockRepository, times(1)).save(user);. What do these two Mockito calls respectively do?",
    options: [
      "Both lines assert that the repository methods were called exactly once",
      "when/thenReturn executes the real findById; verify replaces save with a stub",
      "when/thenReturn records what findById returned last run; verify replays that recording",
      "when/thenReturn stubs the mock to return a canned value when findById(\"1\") is called; verify asserts afterwards that save(user) was invoked exactly once",
    ],
    answer: 3,
    explanation: "when(...).thenReturn(...) is stubbing — it defines the canned answer the mock gives — while verify(...) is behavior verification, checking after the action that an interaction actually happened. They are different mechanisms: stubbing controls inputs to the component, verification checks its outgoing calls.",
    source: "exercise-based",
  },
  {
    week: 18,
    topic: "DI and testability",
    question: "UserService receives its UserRepository via constructor injection: public UserService(UserRepository repository) { this.repository = repository; }. Why does this dependency injection style make the component easy to test, as shown in the demo?",
    options: [
      "Constructor injection makes Spring automatically generate mocks for all tests",
      "The test can simply pass a mock implementation of the dependency into the constructor, swapping the real collaborator without changing the component's code",
      "It guarantees the repository is a singleton, so tests share state safely",
      "It avoids the need for any assertions because the constructor validates behavior",
    ],
    answer: 1,
    explanation: "Because the dependency is supplied from outside rather than created internally (e.g. with new), the test can hand the component a Mockito mock — the demo does exactly new UserService(mockRepository). Spring does not auto-generate mocks; the test creates them explicitly, and no Spring container is even needed.",
    source: "exercise-based",
  },
  {
    week: 18,
    topic: "Integration testing with Testcontainers",
    question: "The integration-test demo annotates its test class with @SpringBootTest(webEnvironment = RANDOM_PORT) and @Testcontainers, starting real PostgreSQL and RabbitMQ containers and registering their connection details with @DynamicPropertySource. What is the key purpose of this setup compared to the mocked component test?",
    options: [
      "To make the tests run faster by avoiding Spring's application context",
      "To unit test individual repository methods against an in-memory stub",
      "To verify that the whole application works correctly with real infrastructure — actual persistence and messaging — not just with test doubles",
      "To replace the database with Mockito mocks managed by Docker",
    ],
    answer: 2,
    explanation: "Integration tests boot the full application context and exercise real dependencies (a genuine Postgres and RabbitMQ in throwaway Docker containers) to catch wiring, configuration, and interaction bugs that mocks cannot reveal. This is slower than mocked component tests — speed is the trade-off, not the goal.",
    source: "exercise-based",
  },
  {
    week: 18,
    topic: "@SpringBootTest vs slice tests",
    question: "What is the main difference between annotating a test with @SpringBootTest versus a slice annotation such as @DataJpaTest?",
    options: [
      "@SpringBootTest loads the entire application context (all beans, optionally a running server), while a slice test loads only a focused subset such as the JPA layer, making it faster and narrower",
      "@SpringBootTest runs without Spring at all, while @DataJpaTest starts the whole application",
      "@DataJpaTest can only be used with Testcontainers, while @SpringBootTest cannot",
      "They are interchangeable; the choice only affects the test report naming",
    ],
    answer: 0,
    explanation: "@SpringBootTest bootstraps the complete context — as in the demo, even starting a web server on a random port — which is realistic but heavyweight. Slice tests like @DataJpaTest deliberately load only one layer's beans for faster, more focused tests; the two are far from interchangeable.",
    source: "exercise-based",
  },
  {
    week: 18,
    topic: "Three pillars of observability",
    question: "The observability demo collects metrics with Micrometer and Prometheus. Metrics are one of the commonly cited \"three pillars of observability\". Which option correctly lists all three pillars?",
    options: [
      "Dashboards, alerts, and health checks",
      "Metrics, dashboards, and containers",
      "Logs, backups, and load balancers",
      "Logs, metrics, and traces",
    ],
    answer: 3,
    explanation: "Observability rests on logs (discrete event records), metrics (aggregated numeric measurements over time, like the JVM and HTTP metrics in the demo), and traces (following a request across services). Dashboards and alerts are tools built on top of these signals, not pillars themselves.",
    source: "exercise-based",
  },
  {
    week: 18,
    topic: "Actuator, Micrometer, Prometheus roles",
    question: "In the microservice monitoring demo, each service exposes /actuator/prometheus, and a docker-compose file runs Prometheus and Grafana. Which statement correctly describes the division of roles between Actuator, Micrometer, and Prometheus?",
    options: [
      "Prometheus pushes metrics into each microservice, which Actuator then stores in the database",
      "Micrometer instruments and records metrics in the app, Actuator exposes them over HTTP endpoints, and Prometheus periodically scrapes and stores them as time series for querying and Grafana dashboards",
      "Actuator generates Grafana dashboards, while Micrometer scrapes the services on a schedule",
      "Micrometer is the visualization layer; Prometheus is the in-app metrics facade",
    ],
    answer: 1,
    explanation: "Micrometer is a metrics instrumentation facade inside the application (here with a Prometheus registry), Actuator exposes management endpoints like /actuator/prometheus, and Prometheus pulls (scrapes) those endpoints — every 15 seconds in the demo config — storing the data that Grafana visualizes. Prometheus uses a pull model, so the idea of it pushing metrics into services is backwards.",
    source: "exercise-based",
  },
];

export default questions;
