import type { Question } from "../../types";

const l08: Question[] = [
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Suppose P(A, B) = 0.12 and P(B) = 0.30. What is P(A | B)?",
    options: [
      "0.04",
      "0.12",
      "0.30",
      "0.40",
    ],
    answer: 3,
    explanation: "By definition P(A|B) = P(A,B)/P(B) = 0.12 / 0.30 = 0.40.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "A disease has prevalence P(D) = 0.001. A test has sensitivity P(+ | D) = 0.99 and false-positive rate P(+ | ¬D) = 0.02. Given a positive test, what is P(D | +)?",
    options: [
      "0.047",
      "0.099",
      "0.500",
      "0.990",
    ],
    answer: 0,
    explanation: "P(+) = 0.99·0.001 + 0.02·0.999 = 0.00099 + 0.01998 = 0.02097. P(D|+) = P(+|D)P(D)/P(+) = 0.00099/0.02097 ≈ 0.047. Most positives are false positives because the prior is so low.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "AIMA Alarm BN: B → A ← E, A → J, A → M. With P(B) = 0.001, P(E) = 0.002, P(A=T | B=T, E=F) = 0.94, P(J=T | A=T) = 0.90, P(M=T | A=T) = 0.70. What is the joint P(B=T, E=F, A=T, J=T, M=F)?",
    options: [
      "0.000253",
      "0.000591",
      "0.000845",
      "0.001000",
    ],
    answer: 0,
    explanation: "Joint = P(B)·P(¬E)·P(A|B,¬E)·P(J|A)·P(¬M|A) = 0.001 · 0.998 · 0.94 · 0.90 · 0.30. Stepwise: 0.001·0.998 = 0.000998; ·0.94 = 0.000938; ·0.90 = 0.000845; ·0.30 ≈ 0.000253.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "BN with two roots B and E sharing child A. P(B=T) = 0.5, P(E=T) = 0.3. CPT for A: P(A=T | B=T, E=T) = 0.9, P(A=T | B=T, E=F) = 0.6. What is P(A=T | B=T)?",
    options: [
      "0.18",
      "0.42",
      "0.60",
      "0.69",
    ],
    answer: 3,
    explanation: "E is independent of B (co-parents with no edge). Sum out E using its prior: P(A=T|B=T) = 0.9·0.3 + 0.6·0.7 = 0.27 + 0.42 = 0.69.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "AIMA Burglary network: B → A ← E, A → J, A → M. Which independence statement is FALSE?",
    options: [
      "B ⊥ E given A",
      "J ⊥ M given A",
      "B ⊥ E unconditionally",
      "J ⊥ M given A and B",
    ],
    answer: 0,
    explanation: "A is a collider on the path B → A ← E. Conditioning on the collider OPENS the path (explaining away), so B and E become dependent given A. The other three statements are true: unconditionally B ⊥ E (collider blocks), and conditioning on the fork node A blocks J–M.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In the Burglary BN (B → A ← E, A → J, A → M), how does observing JohnCalls (J = T) affect the relationship between Burglary and Earthquake?",
    options: [
      "B and E remain independent because J is not the collider itself.",
      "B and E become dependent because J is a descendant of the collider A.",
      "B and E become independent because conditioning always blocks paths.",
      "B and E are already dependent unconditionally.",
    ],
    answer: 1,
    explanation: "A v-structure (collider) is unblocked when you condition on the collider OR any of its descendants. J is a descendant of A, so conditioning on J opens the path B → A ← E and makes B and E dependent.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "BN with C → B. P(C=T) = 0.4, P(B=T | C=T) = 0.8, P(B=T | C=F) = 0.3. Apply Bayes' rule: what is P(C=T | B=T)?",
    options: [
      "0.32",
      "0.50",
      "0.64",
      "0.80",
    ],
    answer: 2,
    explanation: "P(B=T) = 0.8·0.4 + 0.3·0.6 = 0.32 + 0.18 = 0.50. P(C=T|B=T) = P(B=T|C=T)·P(C=T)/P(B=T) = 0.32/0.50 = 0.64.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "A BN has four binary variables: A (root), B (parent A), C (parents A and B), D (parents A, B, and C). How many independent CPT parameters are required?",
    options: [
      "8",
      "11",
      "15",
      "16",
    ],
    answer: 2,
    explanation: "For a binary node with k parents you need 2^k free entries. A → 1, B → 2, C → 4, D → 8. Total = 1+2+4+8 = 15. (A full joint would need 2^4 − 1 = 15 also, since the chain has no missing edges.)",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In a BN A → B, P(A=T) = 0.5 and P(B=T | A=T) = P(B=T | A=F) = 0.4. What is P(A=T | B=T)?",
    options: [
      "0.20",
      "0.40",
      "0.50",
      "1.00",
    ],
    answer: 2,
    explanation: "B's CPT does not depend on A, so A and B are independent and P(A|B) = P(A) = 0.5. Numerically: P(B=T) = 0.4·0.5 + 0.4·0.5 = 0.4; P(A=T|B=T) = (0.4·0.5)/0.4 = 0.5.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In likelihood weighting, evidence is E1 = e1 and E2 = e2. For a particular sample, P(e1 | parents) = 0.4 and P(e2 | parents) = 0.5. What weight is assigned to this sample?",
    options: [
      "0.10",
      "0.20",
      "0.40",
      "0.90",
    ],
    answer: 1,
    explanation: "Likelihood weighting fixes each evidence variable to its observed value and multiplies its CPT entry into the sample weight: w = Π P(e_i | parents(E_i)) = 0.4 · 0.5 = 0.20.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Using the chain rule with P(A) = 0.6, P(B | A) = 0.5, P(C | A, B) = 0.4, what is P(A=T, B=T, C=T)?",
    options: [
      "0.06",
      "0.12",
      "0.30",
      "0.60",
    ],
    answer: 1,
    explanation: "Chain rule: P(A,B,C) = P(A)·P(B|A)·P(C|A,B) = 0.6 · 0.5 · 0.4 = 0.12.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Why does rejection sampling perform poorly when the evidence has low probability?",
    options: [
      "It cannot handle continuous variables.",
      "The vast majority of samples are inconsistent with the evidence and are rejected, wasting computation.",
      "It systematically biases the estimate toward the prior.",
      "It requires the Markov blanket of every node.",
    ],
    answer: 1,
    explanation: "Rejection sampling generates full samples from the prior and discards any that disagree with the evidence. When P(e) is small, the rejection rate is high and the effective sample size collapses — the motivation for likelihood weighting, which never rejects.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "P(A) = 0.6, P(B|A) = 0.3, P(B|¬A) = 0.8. What is P(A|B)?",
    options: [
      "0.18",
      "0.30",
      "0.36",
      "0.50",
    ],
    answer: 2,
    explanation: "P(B) = P(B|A)·P(A) + P(B|¬A)·P(¬A) = 0.3·0.6 + 0.8·0.4 = 0.18 + 0.32 = 0.50. P(A|B) = P(B|A)·P(A)/P(B) = 0.18/0.50 = 0.36.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Fuel-tank BN. P(DT=T) = 0.3, P(V=T|DT=T) = 0.7, P(V=T|DT=F) = 0.1. The car shows NO vibrations (V = F). What is P(DT=T | V=F)?",
    options: [
      "0.09",
      "0.125",
      "0.30",
      "0.43",
    ],
    answer: 1,
    explanation: "P(V=F|DT=T) = 0.3, P(V=F|DT=F) = 0.9. P(V=F) = 0.3·0.3 + 0.9·0.7 = 0.09 + 0.63 = 0.72. P(DT=T|V=F) = (0.3·0.3)/0.72 = 0.09/0.72 = 0.125.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Network E → C ← D, with P(E=T) = 0.4. CPT: P(C=T|D=T,E=T) = 0.8, P(C=T|D=T,E=F) = 0.3. What is P(C=T | D=T)?",
    options: [
      "0.30",
      "0.50",
      "0.55",
      "0.80",
    ],
    answer: 1,
    explanation: "E is hidden and independent of D (co-parents with no edge between them). Sum out E using its prior: P(C=T|D=T) = P(C=T|D=T,E=T)·P(E=T) + P(C=T|D=T,E=F)·P(E=F) = 0.8·0.4 + 0.3·0.6 = 0.32 + 0.18 = 0.50.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Fuel-tank BN. Given P(HC=T|FTL=T) = 0.620 and P(HC=T|FTL=F) = 0.0949 (already summed over DT, EM). With P(FTL=T) = 0.2, what is P(FTL=F | HC=F)?",
    options: [
      "0.38",
      "0.62",
      "0.81",
      "0.91",
    ],
    answer: 3,
    explanation: "P(HC=F|FTL=T) = 1 − 0.620 = 0.380. P(HC=F|FTL=F) = 1 − 0.0949 = 0.9051. P(HC=F) = 0.380·0.2 + 0.9051·0.8 = 0.076 + 0.72408 = 0.80008. P(FTL=F|HC=F) = (0.9051·0.8)/0.80008 = 0.72408/0.80008 ≈ 0.905.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Sprinkler BN (Lab 7 Ex 1): Cloudy → Sprinkler, Cloudy → Rain, Sprinkler & Rain → WetGrass. P(C=T) = 0.5, P(S=T|C=T) = 0.1, P(R=F|C=T) = 0.2, P(W=T|S=T,R=F) = 0.9. What is the joint P(C=T, S=T, R=F, W=T)?",
    options: [
      "0.009",
      "0.018",
      "0.090",
      "0.180",
    ],
    answer: 0,
    explanation: "Joint = P(C)·P(S|C)·P(R|C)·P(W|S,R) = 0.5 · 0.1 · 0.2 · 0.9 = 0.009.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Fuel-tank BN. P(DT=T) = 0.3, P(EM=T) = 0.3. SMS CPT: P(SMS=T|DT,EM) = 0.05 (T,T), 0.6 (T,F), 0.3 (F,T), 0.7 (F,F). What is the marginal P(SMS=T)?",
    options: [
      "0.41",
      "0.50",
      "0.54",
      "0.66",
    ],
    answer: 2,
    explanation: "Sum over DT and EM using their priors: 0.05·(0.3·0.3) + 0.6·(0.3·0.7) + 0.3·(0.7·0.3) + 0.7·(0.7·0.7) = 0.05·0.09 + 0.6·0.21 + 0.3·0.21 + 0.7·0.49 = 0.0045 + 0.126 + 0.063 + 0.343 = 0.5365 ≈ 0.54.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "B ← A → C (fork). P(A=T) = 0.5. P(B=T|A=T) = 0.8, P(B=T|A=F) = 0.2. P(C=T|A=T) = 0.9, P(C=T|A=F) = 0.3. Both B=T and C=T are observed. What is P(A=T | B=T, C=T)?",
    options: [
      "0.50",
      "0.73",
      "0.92",
      "0.97",
    ],
    answer: 2,
    explanation: "B and C are conditionally independent given A (common cause). Numerator: P(B=T|A=T)·P(C=T|A=T)·P(A=T) = 0.8·0.9·0.5 = 0.36. For ¬A: 0.2·0.3·0.5 = 0.03. P(A=T|B=T,C=T) = 0.36/(0.36+0.03) = 0.36/0.39 ≈ 0.923.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "A BN has five binary variables: A (root), B (parent A), C (parents A, B), D (parent C), E (parent C). How many independent CPT parameters are required?",
    options: [
      "8",
      "10",
      "11",
      "16",
    ],
    answer: 2,
    explanation: "Each node needs (2^k) − 1 = 2^k free entries, where k is the number of parents (binary case): A → 1, B → 2, C → 4 (two parents), D → 2, E → 2. Total = 1+2+4+2+2 = 11.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Fuel-tank BN. P(DT=T) = 0.3, P(V=T|DT=T) = 0.7, P(V=T|DT=F) = 0.1. What is the marginal P(V=T)?",
    options: [
      "0.07",
      "0.21",
      "0.28",
      "0.40",
    ],
    answer: 2,
    explanation: "Sum out DT: P(V=T) = P(V=T|DT=T)·P(DT=T) + P(V=T|DT=F)·P(DT=F) = 0.7·0.3 + 0.1·0.7 = 0.21 + 0.07 = 0.28.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Fuel-tank BN. The driver observes SMS=T (slow max speed). Given P(SMS=T|DT=T) = 0.435 and P(SMS=T|DT=F) = 0.580 (already summed over EM), and P(DT=T) = 0.3, what is P(DT=T | SMS=T)?",
    options: [
      "0.13",
      "0.24",
      "0.30",
      "0.44",
    ],
    answer: 1,
    explanation: "P(SMS=T) = 0.435·0.3 + 0.580·0.7 = 0.1305 + 0.406 = 0.5365. P(DT=T|SMS=T) = (0.435·0.3)/0.5365 = 0.1305/0.5365 ≈ 0.243.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Consider the BN with edges: Burglary → Alarm, Earthquake → Alarm, Alarm → JohnCalls, Alarm → MaryCalls. Which independence holds?",
    options: [
      "JohnCalls ⊥ MaryCalls unconditionally.",
      "JohnCalls ⊥ MaryCalls given Alarm.",
      "Burglary ⊥ Earthquake given Alarm.",
      "Burglary ⊥ JohnCalls given Earthquake.",
    ],
    answer: 1,
    explanation: "JohnCalls ← Alarm → MaryCalls is a fork. Conditioning on the common cause Alarm blocks the path, so JohnCalls ⊥ MaryCalls | Alarm. Option C is wrong: Burglary → Alarm ← Earthquake is a collider — conditioning on Alarm OPENS the path ('explaining away').",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Alarm BN. P(B=T) = 0.001, P(E=T) = 0.002, P(A=T|B=T,E=F) = 0.94, P(J=T|A=T) = 0.90, P(M=T|A=T) = 0.70. What is the joint P(B=T, E=F, A=T, J=T, M=T)?",
    options: [
      "0.000591",
      "0.000845",
      "0.000938",
      "0.005910",
    ],
    answer: 0,
    explanation: "Joint = P(B)·P(¬E)·P(A|B,¬E)·P(J|A)·P(M|A) = 0.001 · 0.998 · 0.94 · 0.90 · 0.70. Stepwise: 0.001·0.998 = 0.000998; ·0.94 = 0.000938; ·0.90 = 0.000845; ·0.70 ≈ 0.000591.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Fuel-tank BN. DT=T and FTL=T are confirmed (tire damaged and fuel tank leaking). EM is unknown, P(EM=T) = 0.3. CPT: P(HC=T|DT=T,FTL=T,EM=T) = 0.9, P(HC=T|DT=T,FTL=T,EM=F) = 0.8. What is P(HC=T | DT=T, FTL=T)?",
    options: [
      "0.72",
      "0.80",
      "0.83",
      "0.90",
    ],
    answer: 2,
    explanation: "Sum out EM using its prior (EM is independent of DT and FTL — they are co-parents with no edges between them): P(HC=T|DT=T,FTL=T) = 0.9·0.3 + 0.8·0.7 = 0.27 + 0.56 = 0.83.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Which expression correctly applies enumeration to compute P(Q | E=e) for hidden variables H in a BN?",
    options: [
      "P(Q | E=e) = Σ_h ∏_i P(Xi | Parents(Xi))",
      "P(Q | E=e) = α · Σ_h ∏_i P(Xi | Parents(Xi)), with α = 1/P(E=e)",
      "P(Q | E=e) = ∏_h P(Q, E=e, H=h)",
      "P(Q | E=e) = Σ_q P(Q=q) · P(E=e)",
    ],
    answer: 1,
    explanation: "Inference by enumeration: expand the joint via the BN factorisation, sum over all values of the hidden variables H, then normalise by α = 1/P(E=e). Without the normaliser you only get the unnormalised P(Q, E=e), not the conditional P(Q | E=e).",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "P(A)=0.3, P(B|A)=0.8, P(B|¬A)=0.2. What is P(A|B)?",
    options: [
      "0.63",
      "0.38",
      "0.24",
      "0.80",
    ],
    answer: 0,
    explanation: "P(B) = P(B|A)P(A) + P(B|¬A)P(¬A) = 0.8·0.3 + 0.2·0.7 = 0.24 + 0.14 = 0.38. Then P(A|B) = P(B|A)P(A)/P(B) = 0.24/0.38 ≈ 0.63.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Disease prevalence P(D)=0.01. Test sensitivity P(+|D)=0.9, false-positive rate P(+|¬D)=0.1. What is P(D|+)?",
    options: [
      "0.009",
      "0.083",
      "0.500",
      "0.900",
    ],
    answer: 1,
    explanation: "P(+) = 0.9·0.01 + 0.1·0.99 = 0.009 + 0.099 = 0.108. P(D|+) = 0.009/0.108 ≈ 0.083. Most positives are false positives because the disease is rare.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In a BN L → V ← M, P(L=T)=0.6, P(M=T)=0.3. P(V=T|L=T,M=T)=0.9, P(V=T|L=T,M=F)=0.5. What is P(V=T | L=T)?",
    options: [
      "0.45",
      "0.62",
      "0.70",
      "0.90",
    ],
    answer: 1,
    explanation: "L is a parent of V, so we just look up the CPT. M is hidden and independent of L, so sum out using its prior: P(V=T|L=T) = 0.9·0.3 + 0.5·0.7 = 0.27 + 0.35 = 0.62.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Given the BN A → B → C with edge A → C, what is the correct factorisation of P(A, B, C)?",
    options: [
      "P(A) P(B) P(C)",
      "P(A) P(B|A) P(C|A,B)",
      "P(A|B) P(B|C) P(C)",
      "P(A) P(B|A) P(C|B)",
    ],
    answer: 1,
    explanation: "Each node's factor is P(node | its parents). A has no parents, B has parent A, C has parents A and B: P(A,B,C) = P(A)·P(B|A)·P(C|A,B).",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In a chain A → B → C, which statement about conditional independence is TRUE?",
    options: [
      "A and C are independent unconditionally.",
      "A and C are dependent given B.",
      "A and C are always independent.",
      "A and C are independent given B.",
    ],
    answer: 3,
    explanation: "Conditioning on the middle variable of a chain blocks the path, so A ⊥ C | B. Without conditioning, A and C are dependent through B.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In a collider A → B ← C (v-structure), which statement is TRUE?",
    options: [
      "A and C are independent unconditionally; conditioning on B makes them dependent.",
      "A and C are dependent unconditionally; conditioning on B makes them independent.",
      "A and C are always independent.",
      "A and C are always dependent.",
    ],
    answer: 0,
    explanation: "In a collider, two causes A and C are independent without conditioning. Observing the common effect B 'explains away' and creates a dependence between A and C.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Bayes' rule states P(A|B) = ?",
    options: [
      "P(A) P(B)",
      "P(B|A) / P(A)",
      "P(A,B) / P(A)",
      "P(B|A) · P(A) / P(B)",
    ],
    answer: 3,
    explanation: "Bayes' rule: P(A|B) = P(B|A)·P(A) / P(B). It follows directly from P(A,B) = P(A|B)P(B) = P(B|A)P(A).",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "P(Rain)=0.014, P(Predict|Rain)=0.9, P(Predict|¬Rain)=0.1. What is P(Rain | Predict)?",
    options: [
      "0.011",
      "0.111",
      "0.500",
      "0.900",
    ],
    answer: 1,
    explanation: "P(Predict) = 0.9·0.014 + 0.1·0.986 = 0.0126 + 0.0986 = 0.1112. P(Rain|Predict) = 0.0126/0.1112 ≈ 0.111.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "P(A)=0.5, P(B|A)=0.4, P(B|¬A)=0.6. What is P(A|B)?",
    options: [
      "0.40",
      "0.50",
      "0.60",
      "0.80",
    ],
    answer: 0,
    explanation: "P(B) = 0.4·0.5 + 0.6·0.5 = 0.5. P(A|B) = P(B|A)P(A)/P(B) = (0.4·0.5)/0.5 = 0.4.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "What does the marginalisation (sum rule) say about P(A) in terms of a joint with B?",
    options: [
      "P(A) = P(A|B) · P(B)",
      "P(A) = Σ_b P(A, B=b)",
      "P(A) = P(A,B) / P(B)",
      "P(A) = P(B|A) · P(A) / P(B)",
    ],
    answer: 1,
    explanation: "Marginalisation: P(A) = Σ_b P(A, B=b). Equivalently P(A) = Σ_b P(A|B=b)·P(B=b). You sum the joint over all values of the other variable.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Sprinkler BN: Cloudy → Sprinkler, Cloudy → Rain, Sprinkler → WetGrass, Rain → WetGrass. With P(C=T)=0.5, P(S=F|C=T)=0.9, P(R=T|C=T)=0.8, P(W=T|S=F,R=T)=0.9, what is P(C=T, S=F, R=T, W=T)?",
    options: [
      "0.180",
      "0.250",
      "0.450",
      "0.324",
    ],
    answer: 3,
    explanation: "Joint = P(C)·P(S|C)·P(R|C)·P(W|S,R) = 0.5 · 0.9 · 0.8 · 0.9 = 0.324.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Network A → C ← B with P(A=T)=0.4, P(B=T)=0.5. P(C=T|A=T,B=T)=0.8, P(C=T|A=T,B=F)=0.4. What is P(C=T | A=T)?",
    options: [
      "0.60",
      "0.40",
      "0.50",
      "0.80",
    ],
    answer: 0,
    explanation: "B is hidden and independent of A. Sum out B using its prior: P(C=T|A=T) = 0.8·0.5 + 0.4·0.5 = 0.4 + 0.2 = 0.6.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In the car-malfunction BN, P(DT=T)=0.3, P(V=T|DT=T)=0.7, P(V=T|DT=F)=0.1. What is P(DT=T | V=T)?",
    options: [
      "0.21",
      "0.28",
      "0.50",
      "0.75",
    ],
    answer: 3,
    explanation: "P(V=T) = 0.7·0.3 + 0.1·0.7 = 0.21 + 0.07 = 0.28. P(DT=T|V=T) = 0.21/0.28 = 0.75.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Which method is NOT a valid inference algorithm for Bayesian Networks?",
    options: [
      "Variable elimination",
      "Likelihood weighting",
      "Backpropagation",
      "Gibbs sampling",
    ],
    answer: 2,
    explanation: "Backpropagation is a neural-network training algorithm, not a BN inference method. Variable elimination, likelihood weighting, and Gibbs sampling are all valid BN inference techniques.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In a fork A ← B → C (common cause), what is true about A and C?",
    options: [
      "Always independent.",
      "Always dependent.",
      "Independent unconditionally; dependent given B.",
      "Dependent unconditionally; independent given B.",
    ],
    answer: 3,
    explanation: "In a fork, A and C share a common cause B, so they are dependent. Conditioning on B blocks the path and makes them conditionally independent: A ⊥ C | B.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "How does likelihood weighting differ from rejection sampling?",
    options: [
      "It rejects samples that don't match the evidence.",
      "It samples evidence variables from their CPTs and discards mismatches.",
      "It fixes evidence variables to observed values and weights each sample by the product of P(e_i | parents).",
      "It uses MCMC by resampling one variable at a time.",
    ],
    answer: 2,
    explanation: "Likelihood weighting fixes evidence to observed values (no rejection) and weights each sample by ∏ P(e_i | parents). Every sample contributes, avoiding the rejection problem when evidence is rare.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "P(A)=0.2, P(B|A)=0.9, P(B|¬A)=0.1. What is P(A|B)?",
    options: [
      "0.18",
      "0.26",
      "0.50",
      "0.69",
    ],
    answer: 3,
    explanation: "P(B) = 0.9·0.2 + 0.1·0.8 = 0.18 + 0.08 = 0.26. P(A|B) = 0.18/0.26 ≈ 0.69.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "What is the chain rule of probability for n variables?",
    options: [
      "P(X1,...,Xn) = ∏_i P(Xi | X1,...,X_{i-1})",
      "P(X1,...,Xn) = ∏_i P(Xi)",
      "P(X1,...,Xn) = Σ_i P(Xi)",
      "P(X1,...,Xn) = ∏_i P(Xi | Parents(Xi))",
    ],
    answer: 0,
    explanation: "The general chain rule: P(X1,...,Xn) = ∏_i P(Xi | X1,...,X_{i-1}). Option D is the BN factorisation, a special case using only parents (Markov condition).",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "A BN has binary variables: A (root), B (root), C with parents A and B, D with parent C. How many independent CPT parameters?",
    options: [
      "4",
      "6",
      "8",
      "16",
    ],
    answer: 2,
    explanation: "A: 1 (one free entry), B: 1, C: 2^2 = 4 parent combos × 1 free entry = 4, D: 2 (2 parent values × 1 free entry). Total: 1+1+4+2 = 8.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Given a BN with root nodes B and E, and A with parents B, E; J with parent A; M with parent A — which factorisation is correct?",
    options: [
      "P(B) P(E) P(A) P(J) P(M)",
      "P(B|A) P(E|A) P(A|J,M)",
      "P(B,E,A,J,M) all independent",
      "P(B) P(E) P(A|B,E) P(J|A) P(M|A)",
    ],
    answer: 3,
    explanation: "Each node factor is P(node | parents). B and E are roots. A has parents B,E. J and M each have parent A: P(B)·P(E)·P(A|B,E)·P(J|A)·P(M|A).",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Network A → C ← B with P(A=T)=0.5, P(B=T)=0.4, P(C=T|A=T,B=T)=1.0, P(C=T|A=T,B=F)=0.5, P(C=T|A=F,B=T)=0.5, P(C=T|A=F,B=F)=0.0. What is P(C=T | A=F)?",
    options: [
      "0.20",
      "0.30",
      "0.40",
      "0.50",
    ],
    answer: 0,
    explanation: "Sum out hidden B using its prior: P(C=T|A=F) = P(C=T|A=F,B=T)·P(B=T) + P(C=T|A=F,B=F)·P(B=F) = 0.5·0.4 + 0.0·0.6 = 0.20.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "What does the BN factorisation P(X1,...,Xn) = ∏ P(Xi | Parents(Xi)) rely on?",
    options: [
      "All variables being mutually exclusive.",
      "All variables being independent.",
      "The Markov condition: each node is conditionally independent of its non-descendants given its parents.",
      "The graph being undirected.",
    ],
    answer: 2,
    explanation: "The BN factorisation derives from the Markov condition, which states each node is conditionally independent of its non-descendants given its parents. This allows the joint to factor into per-node CPTs.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "P(A)=0.4, P(B|A)=0.5, P(B|¬A)=0.25. What is P(A|B)?",
    options: [
      "0.20",
      "0.35",
      "0.57",
      "0.80",
    ],
    answer: 2,
    explanation: "P(B) = 0.5·0.4 + 0.25·0.6 = 0.20 + 0.15 = 0.35. P(A|B) = 0.20/0.35 ≈ 0.571 ≈ 0.57.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "The Markov blanket of a node X in a BN consists of:",
    options: [
      "Only its parents.",
      "Only its children.",
      "Its parents and children only.",
      "Its parents, children, and children's other parents.",
    ],
    answer: 3,
    explanation: "The Markov blanket of X is parents ∪ children ∪ children's other parents. Given the Markov blanket, X is conditionally independent of all other variables in the network.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "What is the main idea of variable elimination?",
    options: [
      "Enumerate the full joint distribution explicitly.",
      "Sum out hidden variables one at a time by multiplying only the factors that mention them.",
      "Sample from the prior and reject inconsistent samples.",
      "Compute the Markov blanket of every node.",
    ],
    answer: 1,
    explanation: "Variable elimination repeatedly picks a hidden variable, multiplies only the factors mentioning it, sums it out to produce a smaller factor, and continues. It avoids enumerating the full joint and reuses intermediate sums.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "In a BN A → C ← B, P(A=T)=0.5, P(B=T)=0.5. P(C=T|A=T,B=T)=0.95, P(C=T|A=T,B=F)=0.5, P(C=T|A=F,B=T)=0.5, P(C=T|A=F,B=F)=0.05. What is P(C=T | A=T)?",
    options: [
      "0.50",
      "0.65",
      "0.725",
      "0.95",
    ],
    answer: 2,
    explanation: "Sum out hidden B using its prior: P(C=T|A=T) = 0.95·0.5 + 0.5·0.5 = 0.475 + 0.25 = 0.725.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Two events A and B are mutually exclusive with P(A)=0.3 and P(B)=0.4. Are they independent?",
    options: [
      "Yes, mutually exclusive means independent.",
      "No — mutually exclusive events with nonzero probability are dependent.",
      "Yes, because they don't share outcomes.",
      "Cannot tell without more information.",
    ],
    answer: 1,
    explanation: "If A and B are mutually exclusive with nonzero probability, then knowing A occurred tells you B did NOT occur — so they are dependent. P(A,B)=0 but P(A)P(B)=0.12, so P(A,B) ≠ P(A)P(B).",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Which best describes Gibbs sampling for BN inference?",
    options: [
      "Sample variables top-down from the DAG and reject inconsistent samples.",
      "Fix evidence variables and weight each sample by likelihood.",
      "Start from a random assignment and iteratively resample each non-evidence variable from its distribution conditioned on its Markov blanket.",
      "Compute the exact posterior by enumeration.",
    ],
    answer: 2,
    explanation: "Gibbs sampling is an MCMC method: starting from a random assignment, it repeatedly resamples one non-evidence variable conditioned on the current values of its Markov blanket. It converges to the true posterior but can be slow to mix.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "Given a BN A → B, A → C, B → D, C → D, what is the correct factorisation of P(A, B, C, D)?",
    options: [
      "P(A) P(B) P(C) P(D)",
      "P(A) P(B|A) P(C|A) P(D|B,C)",
      "P(A|B,C) P(B|D) P(C|D) P(D)",
      "P(A) P(B|A) P(C|A,B) P(D|A,B,C)",
    ],
    answer: 1,
    explanation: "Each node factor uses only its actual parents: A has none, B's parent is A, C's parent is A, D's parents are B and C. So P(A,B,C,D) = P(A)·P(B|A)·P(C|A)·P(D|B,C).",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "A full joint over n binary variables has 2^n entries. If a BN has every node with at most k parents, how many CPT entries are needed (asymptotically)?",
    options: [
      "O(2^n)",
      "O(n^k)",
      "O(n · 2^k)",
      "O(n + k)",
    ],
    answer: 2,
    explanation: "Each node has at most 2^k CPT rows (one per parent combination), and there are n nodes. Total: O(n · 2^k) — linear in n, exponential only in the parent count k.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "*Given the BN `A → B → C` with `A → D`, which is the correct factorisation of the joint?*?",
    options: [
      "`P(A)P(B)P(C)P(D)`",
      "`P(A)P(B|A)P(C|B)P(D|A)`",
      "`P(A|B)P(B|C)P(C)P(D)`",
      "`P(A,B,C,D)`",
    ],
    answer: 1,
    explanation: "Correct: B.",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "*In `Burglary → Alarm ← Earthquake`, which is true?*?",
    options: [
      "Burglary and Earthquake are independent unconditionally.",
      "Burglary and Earthquake are independent given Alarm.",
      "Burglary and Earthquake are always dependent.",
      "Burglary causes Earthquake.",
    ],
    answer: 0,
    explanation: "\"explaining away\".)",
  },
  {
    week: 8,
    topic: "Bayesian Networks",
    question: "*Which is NOT a valid inference method for BNs?*?",
    options: [
      "Variable elimination",
      "Likelihood weighting",
      "Backpropagation  (that's neural-network training)",
      "Gibbs sampling",
    ],
    answer: 2,
    explanation: "Correct: C.",
  },
];

export default l08;
