import type { Question } from "../../types";

const l06: Question[] = [
  {
    week: 6,
    topic: "Adversarial Search",
    question: "AIMA defines a two-player zero-sum game as a search problem with six components. Which of the following is NOT one of those components?",
    options: [
      "To-Move(s): the player whose turn it is in state s",
      "Result(s, a): the state resulting from action a in state s",
      "Heuristic(s): an admissible lower bound on path cost to terminal",
      "Utility(s, p): the final numeric value for player p in terminal state s",
    ],
    answer: 2,
    explanation: "AIMA chapter 5 formalises a game as (S0, To-Move, Actions, Result, Is-Terminal, Utility). There is no admissible heuristic component; instead, depth-limited search uses an evaluation function on non-terminal states.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX is at the root of a 3-ply tree. MAX has three MIN children A, B, C. A's leaves are (2, 4, 6); B's leaves are (7, 3, 5); C's leaves are (8, 9, 1). What is the minimax value at the root?",
    options: [
      "1",
      "2",
      "3",
      "8",
    ],
    answer: 2,
    explanation: "A = min(2,4,6) = 2. B = min(7,3,5) = 3. C = min(8,9,1) = 1. Root = max(2,3,1) = 3.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "What are the time and space complexities of minimax search with branching factor b and maximum depth m?",
    options: [
      "Time O(b*m), space O(b^m)",
      "Time O(b^m), space O(bm)",
      "Time O(b^(m/2)), space O(bm)",
      "Time O(b^m), space O(b^m)",
    ],
    answer: 1,
    explanation: "Minimax is depth-first, so it visits O(b^m) nodes in the worst case but only stores one root-to-leaf path with b siblings at each level, giving O(bm) space.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root with three MIN children A, B, C. Leaves left-to-right: A = (5, 6, 7); B = (4, 2, 3); C = (6, 8, 9). Using DFS left-to-right alpha-beta, which leaves get pruned?",
    options: [
      "None — all 9 leaves are evaluated",
      "The leaves 2 and 3 (last two of B)",
      "The leaves 8 and 9 (last two of C)",
      "The leaves 6 and 7 (last two of A)",
    ],
    answer: 1,
    explanation: "A: 5,6,7 → A=5, root α=5. B with α=5: first leaf 4 sets β=4. Since β=4 ≤ α=5, α-cutoff; leaves 2 and 3 are pruned. C: 6,8,9 → C=6. Root = max(5,4,6) = 6.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "In the best case (with perfect move ordering), alpha-beta pruning has time complexity O(b^(m/2)). What is the practical consequence?",
    options: [
      "The effective branching factor becomes sqrt(b), so we can search roughly twice as deep in the same time",
      "The space complexity drops from O(bm) to O(m)",
      "The algorithm becomes incomplete and may miss the optimal move",
      "The minimax value computed is only approximate",
    ],
    answer: 0,
    explanation: "O(b^(m/2)) = O((sqrt(b))^m), so the effective branching factor is sqrt(b). For the same number of node expansions, the achievable search depth roughly doubles, without changing the final value.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "A 4-ply tree: MAX root with two MIN children L and R; each MIN has two MAX children; each MAX has two leaves. Leaves left-to-right: L1=(2,3), L2=(5,9), R1=(4,1), R2=(6,7). Using DFS left-to-right alpha-beta, how many leaves are pruned?",
    options: [
      "0",
      "1",
      "2",
      "3",
    ],
    answer: 1,
    explanation: "L1=max(2,3)=3; L2=max(5,9)=9; L=min(3,9)=3, root α=3. R1=max(4,1)=4; at R MIN, β=4 (>α=3, no cutoff). R2 with α=3, β=4: first leaf 6 sets the MAX value to 6 ≥ β=4 → β-cutoff, prune leaf 7. R = min(4,≥6) = 4. Root = max(3,4) = 4. Exactly 1 leaf (the 7) is pruned.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Which statement about move ordering and alpha-beta is FALSE?",
    options: [
      "Iterative deepening lets us use shallow-search results to order moves at the next depth",
      "Transposition tables can cache previously computed values to provide move-ordering hints",
      "A good static ordering can change the minimax value returned at the root",
      "'Killer moves' that caused cutoffs at sibling nodes are tried early at the current node",
    ],
    answer: 2,
    explanation: "Move ordering only affects how many cutoffs occur (and thus runtime); it never changes the minimax value. Iterative deepening, transposition tables, and killer moves are all standard ordering heuristics.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "In a depth-limited 'cutoff search', what replaces the Utility function for non-terminal states reached at the cutoff depth?",
    options: [
      "A constant 0, since the game has not ended",
      "A heuristic evaluation function Eval(s) that estimates expected utility",
      "The minimax value of the parent state",
      "The number of legal moves from state s",
    ],
    answer: 1,
    explanation: "When the search is cut off before reaching terminal states, an evaluation function Eval(s) — often a weighted linear combination of features — provides an estimate of the state's expected utility for the player to move.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root has two CHANCE children C1 and C2. C1 has outcomes (0.5 → 6, 0.5 → 2). C2 has outcomes (0.4 → 10, 0.6 → 4). What is the expectiminimax value at the root?",
    options: [
      "4.0",
      "5.2",
      "6.4",
      "10.0",
    ],
    answer: 2,
    explanation: "C1 = 0.5·6 + 0.5·2 = 4.0. C2 = 0.4·10 + 0.6·4 = 4.0 + 2.4 = 6.4. Root MAX = max(4.0, 6.4) = 6.4.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Which technique is most commonly used to handle imperfect-information games (like Poker) where minimax does not directly apply?",
    options: [
      "Iterative deepening A*",
      "Monte Carlo Tree Search (MCTS) with sampling over hidden information",
      "Pure alpha-beta with very deep cutoffs",
      "Breadth-first search from the root",
    ],
    answer: 1,
    explanation: "For imperfect-information games, AIMA discusses Monte Carlo Tree Search and sampling-based methods (e.g., averaging over deals of hidden cards) because the standard minimax/expectiminimax tree assumes the state is fully observable.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root has two MIN children A and B. A has leaves (7, 2, 9); B has leaves (4, 6, 1). What is the minimax value at the root?",
    options: [
      "1",
      "2",
      "4",
      "9",
    ],
    answer: 1,
    explanation: "A = min(7, 2, 9) = 2. B = min(4, 6, 1) = 1. Root MAX = max(2, 1) = 2.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MIN root has two MAX children A and B. A has leaves (5, 3, 8); B has leaves (2, 9, 6). What is the minimax value at the root?",
    options: [
      "2",
      "8",
      "9",
      "3",
    ],
    answer: 1,
    explanation: "A = max(5, 3, 8) = 8. B = max(2, 9, 6) = 9. Root MIN = min(8, 9) = 8.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root has three MIN children A, B, C. A has leaves (10, 4); B has leaves (6, 7, 3); C has leaves (8, 5). What is the minimax value at the root?",
    options: [
      "3",
      "4",
      "5",
      "10",
    ],
    answer: 2,
    explanation: "A = min(10, 4) = 4. B = min(6, 7, 3) = 3. C = min(8, 5) = 5. Root MAX = max(4, 3, 5) = 5.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "A 4-level tree: MAX root, then MIN, then MAX, then leaves. The root has two MIN children L and R. L has two MAX children with leaves (3, 5) and (2, 9). R has two MAX children with leaves (6, 1) and (4, 7). What is the minimax value at the root?",
    options: [
      "5",
      "6",
      "7",
      "9",
    ],
    answer: 1,
    explanation: "L's MAX children: max(3,5)=5, max(2,9)=9. L = min(5,9) = 5. R's MAX children: max(6,1)=6, max(4,7)=7. R = min(6,7) = 6. Root MAX = max(5,6) = 6.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root has three MIN children A, B, C. A has leaves (-3, -1, -5); B has leaves (-2, -4); C has leaves (0, -6, -8). What is the minimax value at the root?",
    options: [
      "-8",
      "-6",
      "-4",
      "-1",
    ],
    answer: 2,
    explanation: "A = min(-3, -1, -5) = -5. B = min(-2, -4) = -4. C = min(0, -6, -8) = -8. Root MAX = max(-5, -4, -8) = -4.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root with two MIN children A and B. Leaves left-to-right: A=(8, 7, 3); B=(9, 1, 2). Using alpha-beta DFS left-to-right, which leaves are pruned?",
    options: [
      "None",
      "Only leaf with value 2 (last child of B)",
      "Leaves with values 1 and 2 (last two children of B)",
      "Leaves with values 7 and 3 (last two children of A)",
    ],
    answer: 1,
    explanation: "A: visit 8 (β=8), 7 (β=7), 3 (β=3). A=3, root α=3. B with α=3: visit 9 (β=9, no cut), then 1 → β=1 ≤ α=3 ⇒ α-cutoff. Leaf 1 was read (it triggered the cutoff); only the last leaf (value 2) is pruned.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root with three MIN children A, B, C. Leaves left-to-right: A=(5, 8); B=(3, 9); C=(7, 6). Using alpha-beta DFS left-to-right, how many leaves are evaluated (NOT pruned)?",
    options: [
      "6",
      "5",
      "4",
      "3",
    ],
    answer: 1,
    explanation: "A: 5 (β=5), 8 (still β=5). A=5, root α=5. B with α=5: 3 → β=3 ≤ α=5 ⇒ α-cutoff, prune 9. C with α=5: 7 (β=7), 6 (β=6). C=6. Root = max(5,3,6)=6. Leaves evaluated: 5, 8, 3, 7, 6 = 5 leaves; pruned: just 9.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root with two MIN children A and B. Leaves left-to-right: A=(2, 5, 8); B=(6, 4, 7). Using alpha-beta DFS left-to-right, which leaves get pruned?",
    options: [
      "None — all 6 leaves are evaluated",
      "The leaves 4 and 7 (last two of B)",
      "The leaf 7 only (last child of B)",
      "The leaves 5 and 8 (last two of A)",
    ],
    answer: 0,
    explanation: "A: 2 (β=2), 5 (β=2), 8 (β=2). A=2, root α=2. B with α=2: 6 (β=6, 6>2 no cut), 4 (β=4, 4>2 no cut), 7 (β=4, no cut). B=4. All 6 leaves evaluated; root = max(2,4) = 4.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "A chance node has two outcomes: outcome X with probability 0.3 leading to a subtree with value 10, and outcome Y with probability 0.7 leading to a subtree with value 5. What is the expectiminimax value at the chance node?",
    options: [
      "7.5",
      "6.5",
      "5.0",
      "8.0",
    ],
    answer: 1,
    explanation: "Expected value = 0.3·10 + 0.7·5 = 3.0 + 3.5 = 6.5.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root has two children that are CHANCE nodes C1 and C2. C1 has outcomes (0.5 → 8, 0.5 → 4). C2 has outcomes (0.25 → 12, 0.75 → 2). What is the expectiminimax value at the root?",
    options: [
      "4.0",
      "5.0",
      "6.0",
      "7.0",
    ],
    answer: 2,
    explanation: "C1 = 0.5·8 + 0.5·4 = 4 + 2 = 6. C2 = 0.25·12 + 0.75·2 = 3 + 1.5 = 4.5. Root MAX = max(6, 4.5) = 6.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "MAX root with four MIN children A, B, C, D, each having two leaves. Leaves left-to-right: A=(3, 5); B=(2, 9); C=(8, 7); D=(4, 6). Using alpha-beta DFS left-to-right, what is the minimax value at the root and how many leaves are pruned?",
    options: [
      "Value 7, 1 leaf pruned",
      "Value 7, 2 leaves pruned",
      "Value 7, 3 leaves pruned",
      "Value 9, 0 leaves pruned",
    ],
    answer: 1,
    explanation: "A: 3 (β=3), 5 (β=3). A=3, root α=3. B with α=3: 2 → β=2 ≤ α=3 ⇒ α-cutoff, prune leaf 9. C with α=3: 8 (β=8), 7 (β=7). C=7, root α=7. D with α=7: 4 → β=4 ≤ α=7 ⇒ α-cutoff, prune leaf 6. Root MAX = max(3,2,7,4) = 7. Pruned: leaves 9 and 6 — 2 leaves total.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Which of the following best describes a zero-sum game?",
    options: [
      "Both players can win simultaneously if they cooperate",
      "One player's gain equals the other player's loss (constant total payoff)",
      "Neither player wins, the game always ends in a draw",
      "The total payoff increases over time as the game progresses",
    ],
    answer: 1,
    explanation: "In a zero-sum game, the sum of payoffs is constant: whatever one player gains, the other loses. There is 'no win-win', which is why MAX maximises utility and MIN minimises the same utility.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "What is the worst-case time complexity of alpha-beta pruning (with poor move ordering)?",
    options: [
      "O(b^(m/2))",
      "O(b*m)",
      "O(log b)",
      "O(b^m)",
    ],
    answer: 3,
    explanation: "With bad move ordering, alpha-beta never gets to prune and degenerates to plain minimax, with worst-case O(b^m). Only with optimal ordering do we get O(b^(m/2)).",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Compared to plain minimax, the value returned at the root by alpha-beta pruning is:",
    options: [
      "Identical to the minimax value",
      "An approximation that may differ slightly",
      "Higher because bad branches are skipped",
      "Lower because some paths are not explored",
    ],
    answer: 0,
    explanation: "Alpha-beta pruning returns the EXACT same value as minimax. It only saves computational work by skipping provably irrelevant subtrees; it never changes the decision.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "In alpha-beta pruning, what does the parameter α represent?",
    options: [
      "The best (lowest) value MIN is guaranteed at most so far",
      "The best (highest) value MAX is guaranteed at least so far",
      "The total number of nodes pruned so far",
      "The current search depth",
    ],
    answer: 1,
    explanation: "α is MAX's floor — the highest value MAX is guaranteed at least. Mnemonic: 'α = at least'. It updates at MAX nodes (only increases) and is used to trigger α-cutoffs at MIN nodes.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "When does alpha-beta pruning trigger a cutoff?",
    options: [
      "When α < β",
      "When the depth limit is reached",
      "When α ≥ β",
      "When a terminal state is found",
    ],
    answer: 2,
    explanation: "The pruning rule is: prune whenever α ≥ β. At that point the current subtree cannot influence the choice at an ancestor, so further exploration is wasted.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "A MAX root has two MIN children. The left MIN's leaves are (5, 2), so the left MIN returns 2. Then we expand the right MIN, whose first leaf is 1. What happens next?",
    options: [
      "Continue expanding the right MIN's remaining children, since β has not crossed α",
      "Trigger an α-cutoff: prune the right MIN's remaining children because 1 ≤ α = 2",
      "Return 1 as the root value immediately",
      "Backtrack to the root without updating any bound",
    ],
    answer: 1,
    explanation: "After the left MIN returns 2, α at the root becomes 2. At the right MIN, β becomes 1 after seeing the first leaf. Since 1 ≤ α = 2, an α-cutoff fires and the remaining children of the right MIN are pruned — MAX would never choose this branch.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Why does move ordering matter so much for alpha-beta pruning?",
    options: [
      "It changes the minimax value returned at the root",
      "It reduces the space complexity from O(b*m) to O(m)",
      "Examining strong moves first increases the chance of early cutoffs",
      "It is required for the algorithm to be complete",
    ],
    answer: 2,
    explanation: "Move ordering does not change correctness, but examining the best moves first makes α and β tighten quickly, triggering more cutoffs. With perfect ordering you get O(b^(m/2)); with bad ordering you degrade to O(b^m).",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Which property is NOT generally required of a good static evaluation function?",
    options: [
      "Agrees with utility on terminal states",
      "Fast to compute",
      "Correlates with the actual probability of winning",
      "Must be a strict nonlinear function of the features",
    ],
    answer: 3,
    explanation: "Good evaluation functions are typically built as a weighted linear sum of features because that is fast and explainable; they need to agree with utility on terminals, be fast, and correlate with winning chance. Nonlinearity is not required.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "In stochastic games like Backgammon, what value is computed at a chance node in Expectiminimax?",
    options: [
      "The maximum value among all outcomes",
      "The minimum value among all outcomes",
      "The probability-weighted sum (expected value) over outcomes",
      "The median value of all outcomes",
    ],
    answer: 2,
    explanation: "A chance node computes Σ P(r) · ExpectMinimax(Result(s, r)) — the expected value, weighted by the probability of each random outcome r. Exact magnitudes (not just orderings) of leaf values matter at chance nodes.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Consider a MAX root A with three MIN children B, C, D. B's leaves are (3, 12, 8), C's leaves are (2, 4, 6), and D's leaves are (14, 5, 2). What is the minimax value at A?",
    options: [
      "14",
      "3",
      "2",
      "8",
    ],
    answer: 1,
    explanation: "B = min(3, 12, 8) = 3. C = min(2, 4, 6) = 2. D = min(14, 5, 2) = 2. A = max(3, 2, 2) = 3.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Using the tree from the previous question (B leaves (3,12,8), C leaves (2,4,6), D leaves (14,5,2)) and DFS left-to-right alpha-beta, which leaves get pruned?",
    options: [
      "None — all 9 leaves are visited",
      "The leaves 4 and 6 (the last two children of C)",
      "The leaves 5 and 2 (the last two children of D)",
      "The leaves 12 and 8 (the last two children of B)",
    ],
    answer: 1,
    explanation: "After B returns 3, root α = 3. At C the first leaf 2 sets β = 2; since β = 2 ≤ α = 3 an α-cutoff fires and C's remaining leaves (4 and 6) are pruned. D is fully explored and returns 2.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Which game is best classified as STOCHASTIC with PERFECT information?",
    options: [
      "Chess",
      "Poker",
      "Backgammon",
      "Battleship",
    ],
    answer: 2,
    explanation: "Backgammon involves a dice roll (stochastic) but both players see the full board (perfect information). Chess is deterministic+perfect, Poker is stochastic+imperfect, Battleship is deterministic+imperfect.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "What is the space complexity of plain minimax with branching factor b and maximum depth m?",
    options: [
      "O(b^m)",
      "O(b*m)",
      "O(b^(m/2))",
      "O(m^b)",
    ],
    answer: 1,
    explanation: "Minimax is implemented as depth-first search, so only one path from root to leaf is held in memory at a time, with b children at each level. That gives O(b*m) space, not exponential.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "A common form of evaluation function used in real game-playing programs is:",
    options: [
      "A weighted linear sum of board features: EVAL(s) = w1*f1(s) + w2*f2(s) + ... + wn*fn(s)",
      "The exact minimax value computed to the leaves",
      "A random value drawn each call to encourage exploration",
      "The branching factor at that state",
    ],
    answer: 0,
    explanation: "The standard simple choice is a weighted linear combination of features (e.g., material balance, mobility, king safety in chess). It is fast, explainable, and used inside depth-limited 'H-Minimax' searches.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "If MAX plays minimax against an opponent who plays sub-optimally (worse than minimax), MAX's actual utility:",
    options: [
      "Can only go down compared to facing an optimal opponent",
      "Stays exactly the same as against an optimal opponent",
      "Can only go up (or stay the same) compared to facing an optimal opponent",
      "Becomes undefined because minimax assumes optimality",
    ],
    answer: 2,
    explanation: "Minimax gives the best worst-case payoff against an optimal opponent. If the opponent makes mistakes, MAX can only do better (or equally well), never worse — the minimax value is a lower bound on what MAX achieves.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Why can plain alpha-beta pruning NOT be applied directly to chance nodes in stochastic games (without extra assumptions)?",
    options: [
      "Because chance nodes have only one child by definition",
      "Because expected values depend on the exact magnitudes of every child, not just their ordering",
      "Because the tree is no longer finite",
      "Because α and β are not defined for non-zero-sum games",
    ],
    answer: 1,
    explanation: "At a chance node we compute Σ P(r)·v(r). Changing any unseen child's value alters the expected value, so we cannot prove a subtree is irrelevant without bounded utilities. This is unlike MAX/MIN nodes, which only care about the best or worst child.",
  },
  {
    week: 6,
    topic: "Adversarial Search",
    question: "Why is alpha-beta with optimal move ordering said to let you 'search twice as deep' for the same cost?",
    options: [
      "Because pruning halves the branching factor's exponent: O(b^(m/2)) = O((sqrt(b))^m)",
      "Because alpha-beta uses breadth-first search instead of depth-first",
      "Because the evaluation function is twice as fast",
      "Because alpha-beta caches all visited nodes in memory",
    ],
    answer: 0,
    explanation: "Best-case alpha-beta runs in O(b^(m/2)), which equals O((sqrt(b))^m). The effective branching factor becomes sqrt(b), so within the same time budget we can roughly double the search depth m.",
  },
];

export default l06;
