import type { Question } from "../../types";

const l03: Question[] = [
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Romania-style road map with undirected edges (cost in km): Arad-Sibiu(140), Sibiu-Fagaras(99), Sibiu-Rimnicu(80), Fagaras-Bucharest(211), Rimnicu-Pitesti(97), Pitesti-Bucharest(101). Start = Arad, Goal = Bucharest. Break ties alphabetically. What path does uniform-cost search return, and what is its cost?",
    options: [
      "Arad-Sibiu-Fagaras-Bucharest, cost 450",
      "Arad-Sibiu-Rimnicu-Pitesti-Bucharest, cost 418",
      "Arad-Sibiu-Rimnicu-Pitesti-Bucharest, cost 458",
      "Arad-Sibiu-Fagaras-Bucharest, cost 410",
    ],
    answer: 1,
    explanation: "UCS expands by cumulative cost g(n). Arad-Sibiu-Fagaras-Bucharest = 140+99+211 = 450. Arad-Sibiu-Rimnicu-Pitesti-Bucharest = 140+80+97+101 = 418. UCS pops Bucharest at cost 418 first and returns the Pitesti route as optimal.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Directed graph (edge:cost): S->A(2), S->B(3), A->C(1), B->C(1), C->D(2), D->G(2), B->G(9). Start = S, Goal = G. Break ties alphabetically. What does UCS return?",
    options: [
      "S->A->C->D->G with cost 7",
      "S->B->C->D->G with cost 8",
      "S->A->C->D->G with cost 8",
      "S->B->G with cost 12",
    ],
    answer: 0,
    explanation: "S->A->C->D->G = 2+1+2+2 = 7 (cheapest). S->B->C->D->G = 3+1+2+2 = 8. S->B->G = 3+9 = 12. UCS pops in g(n) order and returns the cost-7 path.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "What is the worst-case time complexity of uniform-cost search when C* is the cost of the optimal solution and every step cost is at least epsilon > 0?",
    options: [
      "O(b^d) where d is the shallowest-goal depth",
      "O(b^m) where m is the maximum tree depth",
      "O(b^(1 + floor(C* / epsilon)))",
      "O(b^(d/2))",
    ],
    answer: 2,
    explanation: "UCS may expand all nodes with g(n) <= C*. The effective depth is bounded by C*/epsilon, giving O(b^(1 + floor(C*/epsilon))). When all step costs are equal, this reduces to O(b^d) like BFS.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Why is depth-first TREE search NOT complete in general?",
    options: [
      "DFS cannot expand more than b children per node",
      "DFS requires uniform step costs to terminate",
      "DFS may descend an infinite (or very deep) branch and never return to alternative branches, even if a goal exists elsewhere",
      "DFS uses a priority queue that may overflow",
    ],
    answer: 2,
    explanation: "In an infinite state space or one with infinite paths, DFS can descend forever without ever backtracking to a branch that contains the goal. Graph-search DFS with an explored set is complete in finite spaces, but tree-search DFS is not complete in general.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Tree: A->B,C; B->D,E; C->F. Goal = D. IDS is run with limits l = 0, 1, 2, alphabetical tie-break, goal-test on POP. How many total node pops occur across all three iterations until D is found?",
    options: [
      "11",
      "9",
      "5",
      "7",
    ],
    answer: 3,
    explanation: "l=0: pop A (1). l=1: pop A, B, C (3). l=2: pop A, B, D - D is the goal (3). Total = 1+3+3 = 7. The pattern reflects how IDS repeats shallow work but is dominated by the deepest iteration.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "What are the time and space complexities of bidirectional BFS when the solution depth is d and the branching factor is b in both directions?",
    options: [
      "Time O(b*d), space O(b*d)",
      "Time O(b^d), space O(b^d)",
      "Time O(2*b^d), space O(2*b^d)",
      "Time O(b^(d/2)), space O(b^(d/2))",
    ],
    answer: 3,
    explanation: "Each frontier only needs to reach depth d/2 before the two searches meet, so both time and space are O(b^(d/2)). This is exponentially faster than one-directional BFS but requires a reversible action model and a hash-based meeting test.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Directed graph: S->A, S->B; A->C, A->D; B->D, B->E; C->G; E->G. Unit costs, goal = G, alphabetical tie-break. Using BFS GRAPH SEARCH (with an explored set, goal-test on pop), in what order are nodes expanded?",
    options: [
      "S, A, B, C, D, E, G",
      "S, A, C, G",
      "S, A, B, C, D, G",
      "S, A, B, D, C, E, G",
    ],
    answer: 0,
    explanation: "Pop S, push A,B. Pop A, push C,D. Pop B, D is already on frontier (skip), push E. Pop C, push G. Pop D (no new successors). Pop E, G is already on frontier (skip). Pop G - goal. Expansion order: S, A, B, C, D, E, G.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which is the KEY difference between tree search and graph search in AIMA's framework?",
    options: [
      "Tree search uses a stack, graph search uses a queue",
      "Tree search is always complete, graph search is not",
      "Graph search requires a heuristic, tree search does not",
      "Graph search maintains an explored set so already-expanded states are not re-expanded; tree search does not",
    ],
    answer: 3,
    explanation: "The explored (closed) set is what turns tree search into graph search. It prevents re-expansion of the same state, which is essential for finite termination in state spaces with cycles or multiple paths to the same state.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which combination of (goal-test timing, optimality) is correct for breadth-first search with UNIT step costs?",
    options: [
      "Goal-test on generation; still optimal because the first goal generated is at the shallowest depth",
      "Goal-test on expansion (pop) only; not optimal even with unit costs",
      "Goal-test on generation; not optimal because a shallower goal could be popped later",
      "Goal-test must be on expansion to be optimal, even with unit costs",
    ],
    answer: 0,
    explanation: "With unit step costs, BFS reaches the shallowest goal first. Because all nodes at a given depth are generated before any at the next depth, the first generated goal is guaranteed to be at the shallowest depth, so BFS may goal-test on generation and remain optimal. UCS, in contrast, MUST goal-test on pop because a goal can be generated with high cost while a cheaper path is still being processed.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "When formulating the 8-puzzle as a search problem, which is the CORRECT transition model?",
    options: [
      "Result(s, a) returns the goal state directly if a is the optimal move",
      "Result(s, a) returns the previous state because the puzzle is reversible",
      "Result(s, a) returns a new board configuration obtained by sliding the blank in direction a (Up/Down/Left/Right), swapping it with the adjacent tile",
      "Result(s, a) returns a heuristic estimate of distance from s to the goal",
    ],
    answer: 2,
    explanation: "The transition model deterministically maps (state, action) to a successor state. For the 8-puzzle, an action slides the blank in one of four directions, swapping it with the adjacent tile. The goal test compares against the target board; path cost is the number of moves (uniform cost = 1).",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Tree: A has children B,C,D. B has children E,F. C has child G. D has child H. Goal = G. Alphabetical tie-break. In what order does BFS expand nodes?",
    options: [
      "A, B, C, D, E, F, G",
      "A, B, E, F, C, G",
      "A, C, G",
      "A, B, C, D, G",
    ],
    answer: 0,
    explanation: "BFS expands by depth, alphabetical within a level. Depth 0: A. Depth 1: B, C, D. Depth 2: E, F (B's children), then G (C's child) which is the goal. Order: A, B, C, D, E, F, G.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Same tree (A->B,C,D; B->E,F; C->G; D->H), goal = G. Alphabetical tie-break, leftmost child explored first. In what order does DFS expand nodes?",
    options: [
      "A, B, C, D, E, F, G",
      "A, B, E, F, C, G",
      "A, D, H, C, G",
      "A, B, E, F, C, D, G",
    ],
    answer: 1,
    explanation: "DFS pushes children with leftmost on top. Pop A, push D,C,B -> [B,C,D]. Pop B, push F,E -> [E,F,C,D]. Pop E (leaf). Pop F (leaf). Pop C, push G -> [G,D]. Pop G - goal. Order: A, B, E, F, C, G.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Tree: S->A,B; A->C; C->G; B->G. All edges unit cost. Goal = G. Alphabetical tie-break, leftmost child explored first by DFS. Which path does DFS return?",
    options: [
      "S -> B -> G",
      "S -> A -> C -> G",
      "S -> A -> G",
      "DFS does not terminate",
    ],
    answer: 1,
    explanation: "DFS: pop S, push B,A -> [A,B]. Pop A, push C -> [C,B]. Pop C, push G -> [G,B]. Pop G - goal. DFS dives left first and returns S->A->C->G, even though BFS would return the shorter S->B->G.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Same graph as previous (S->A,B; A->C; C->G; B->G; unit costs). Which path does BFS return?",
    options: [
      "S -> A -> C -> G (depth 3)",
      "S -> B -> G (depth 2)",
      "S -> A -> G (depth 2)",
      "BFS does not terminate",
    ],
    answer: 1,
    explanation: "BFS expands by depth: S, then A, B (depth 1), then C, G via B (depth 2 - goal). The shallowest goal is reached through B, so BFS returns S->B->G at depth 2.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Tree: A->B,C; B->D,E; C->F,G; D->H,I. Goal = I. IDS is run with depth limits l = 0, 1, 2, 3 (alphabetical tie-break). DLS does not expand nodes at depth = limit. How many total node POPS occur across all iterations until I is found?",
    options: [
      "10",
      "12",
      "16",
      "20",
    ],
    answer: 2,
    explanation: "l=0: pop A (1). l=1: pop A, B, C (3). l=2: pop A, B, D, E, C, F, G (7). l=3: pop A, B, D, H, I (5, stops at goal). Total = 1+3+7+5 = 16. IDS's repeated work is dominated by the deepest iteration.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Tree: A->B,C,D; B->E,F; C->G; D->H,I. Goal = I. Alphabetical tie-break, leftmost first for DFS. After A and B have been popped and expanded, what does the DFS fringe look like (with top of stack listed first)?",
    options: [
      "[C, D, E, F]",
      "[E, F, C, D]",
      "[B, C, D, E, F]",
      "[F, E, D, C]",
    ],
    answer: 1,
    explanation: "Start [A]. Pop A, push children with leftmost on top: push D, C, B -> [B, C, D]. Pop B, push F then E -> [E, F, C, D]. The deepest most-recently-added node (E) is on top.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Directed graph (edge:cost): S->A(1), S->B(2), A->B(1), A->C(5), B->C(2), C->G(1). Break ties alphabetically. What is the expansion order of UCS, and what path does it return?",
    options: [
      "Expand S, A, B, C, G. Path S->A->B->C->G with cost 5",
      "Expand S, A, B, C, G. Path S->B->C->G with cost 5",
      "Expand S, B, A, C, G. Path S->A->C->G with cost 6",
      "Expand S, A, B, G. Path S->A->G (no such edge)",
    ],
    answer: 0,
    explanation: "UCS: pop S:0, push A:1, B:2. Pop A:1, push B:2 (same cost, keep), C:6. Pop B:2 (via S, tie broken alphabetically), push C:4 (cheaper than 6, replace). Pop C:4, push G:5. Pop G:5. Order S,A,B,C,G. Path S->A->B->C->G cost 1+1+2+1=5.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Tree: A->B,C; B->D,E; C->F,G; goal = G, unit costs. Which statement correctly compares BFS, DFS, and IDS on this tree (alphabetical tie-break)?",
    options: [
      "BFS and IDS both return A->C->G (optimal, depth 2); DFS returns A->C->G after exploring B's subtree first",
      "All three return A->B->E because that is leftmost",
      "BFS returns A->C->G; DFS returns A->B->E and never reaches G",
      "Only UCS can find G; BFS/DFS/IDS all fail",
    ],
    answer: 0,
    explanation: "BFS pops A,B,C,D,E,F,G - returns A->C->G (depth 2). DFS pops A,B,D,E,C,F,G - also returns A->C->G but only after exhausting B's subtree. IDS at l=2 finds G and returns A->C->G. All three return the optimal depth-2 path with unit costs.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which five components define a classical search problem?",
    options: [
      "Initial state, heuristic, goal test, path cost, transition model",
      "Initial state, actions, transition model, goal test, path cost",
      "State space, fringe, explored set, goal test, branching factor",
      "Start node, end node, edges, weights, depth",
    ],
    answer: 1,
    explanation: "A search problem is formally defined by (1) initial state, (2) actions/successor function, (3) transition model Result(s,a), (4) goal test, and (5) path cost. Heuristics are not part of an uninformed problem definition.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "What is the difference between a state and a node in search?",
    options: [
      "They are synonyms; the lecture uses them interchangeably",
      "A state is a data structure with parent pointers; a node is a physical world configuration",
      "A state is a physical world configuration; a node is a data structure containing (state, parent, action, path-cost, depth)",
      "Nodes belong to the fringe, states belong to the explored set; otherwise identical",
    ],
    answer: 2,
    explanation: "A state describes a configuration of the world. A node is a bookkeeping object in the search tree that records which state it represents along with its parent, the action that produced it, path cost, and depth. Many different nodes can refer to the same state.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "What is the time and space complexity of breadth-first search (BFS) in terms of branching factor b and depth d of the shallowest goal?",
    options: [
      "Time O(b^d), Space O(b*d)",
      "Time O(b^m), Space O(b*m)",
      "Time O(b^d), Space O(b^d)",
      "Time O(b^(d/2)), Space O(b^(d/2))",
    ],
    answer: 2,
    explanation: "BFS expands every node up to depth d, giving O(b^d) time. It must keep the whole frontier (the last expanded layer) in memory, also O(b^d). Space, not time, is usually BFS's killer.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which uninformed search algorithm has space complexity O(b*d) AND is complete AND optimal when step costs are uniform?",
    options: [
      "Iterative Deepening DFS (IDS)",
      "Breadth-First Search",
      "Depth-First Search",
      "Uniform-Cost Search",
    ],
    answer: 0,
    explanation: "IDS keeps only the current DFS path in memory (O(b*d)), yet is complete and (with uniform step costs) optimal because every depth is eventually reached. BFS shares the optimality but uses O(b^d) space.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Under what condition do BFS and uniform-cost search expand nodes in the same order?",
    options: [
      "Never; they always use different criteria",
      "When the state space is a tree (no loops)",
      "When all step costs are equal",
      "When the goal lies at the maximum depth of the tree",
    ],
    answer: 2,
    explanation: "UCS orders the frontier by cumulative cost g(n). When every step costs the same, g(n) is proportional to depth, which is exactly the ordering BFS uses, so the two algorithms expand identically.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Graph: S->A:2, S->B:1, A->C:1, B->C:3, C->G:2. Tie-break alphabetically. What path does UCS return?",
    options: [
      "S -> B -> C -> G with cost 6",
      "S -> A -> C -> G with cost 5",
      "S -> B -> C -> G with cost 5",
      "S -> A -> C -> G with cost 4",
    ],
    answer: 1,
    explanation: "UCS: pop B(1) push C:4; pop A(2) push C:3 (cheaper than 4, replace); pop C(3) push G:5; pop G(5). The optimal path is S->A->C->G with total cost 2+1+2=5.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Graph: S->G:10, S->A:1, A->G:2. UCS goal-tests at pop. The goal node G first appears on the frontier when expanding S (at cost 10). What does UCS return?",
    options: [
      "S -> G with cost 10, because that is the first goal node generated",
      "Failure, because the same state appears twice on the frontier",
      "S -> A -> G with cost 3",
      "S -> A with cost 1",
    ],
    answer: 2,
    explanation: "UCS does not return a goal when it is generated, only when it is popped. The cheaper path S->A->G (cost 3) is discovered and replaces G:10 on the frontier, so UCS pops G at cost 3 and returns the optimal solution.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Tree: A has children B,C. B has children D,E. C has children F,G. Goal = E, alphabetical order so leftmost child is explored first. In what order does DFS expand nodes?",
    options: [
      "A, B, C, D, E",
      "A, B, D, E",
      "A, C, F, G, B, D, E",
      "A, B, D, E, C, F, G",
    ],
    answer: 1,
    explanation: "DFS pushes C then B so B is on top. Pop B, push E then D so D is on top. Pop D (leaf). Pop E - goal found. Expansion order: A, B, D, E. DFS stops as soon as the goal is reached.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Same tree (A->B,C; B->D,E; C->F,G), goal = F. In what order does BFS expand nodes?",
    options: [
      "A, B, C, D, E, F",
      "A, B, D, E, C, F",
      "A, C, F",
      "A, B, C, F",
    ],
    answer: 0,
    explanation: "BFS expands layer by layer, alphabetical within a layer: depth 0 = A, depth 1 = B then C, depth 2 = D, E, F. Goal F is the sixth node popped.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "What is the asymptotic time complexity of Iterative Deepening DFS (IDS) in terms of b and d?",
    options: [
      "O(b*d)",
      "O(b^m) where m is max tree depth",
      "O(d * b^d)",
      "O(b^d)",
    ],
    answer: 3,
    explanation: "Although IDS re-runs DFS at depths 0,1,2,...,d, the work is dominated by the deepest iteration. The total is (d+1)*b^0 + d*b^1 + ... + 1*b^d, which is O(b^d) - the same as BFS.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which statement about DFS optimality is correct?",
    options: [
      "DFS is optimal when step costs are uniform",
      "DFS is optimal whenever the state space is finite",
      "DFS is never guaranteed to be optimal; it returns the first goal it stumbles onto",
      "DFS is optimal when the goal is at maximum depth",
    ],
    answer: 2,
    explanation: "DFS dives into the leftmost branch and returns the first goal it finds, which may be deep and expensive. Even in finite, unit-cost spaces, DFS may return a sub-optimal solution before exploring shorter paths.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "What is the role of the explored set (closed list) in graph search?",
    options: [
      "It stores nodes that still need to be expanded",
      "It holds the path from the start to the current node",
      "It tracks the priority of each frontier node",
      "It records every state already expanded so the algorithm does not re-expand or revisit it",
    ],
    answer: 3,
    explanation: "Graph search maintains an explored set of states already expanded. Before adding a child to the frontier, the algorithm checks the explored set (and frontier) to avoid re-exploring states - critical when the state graph has cycles or multiple paths to the same state.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "What is the time complexity of bidirectional search (with BFS in both directions) for a goal at depth d?",
    options: [
      "O(b^d)",
      "O(b^d / 2)",
      "O(2 * b^d)",
      "O(b^(d/2))",
    ],
    answer: 3,
    explanation: "Each direction only needs to reach depth d/2 before the two frontiers meet, giving O(b^(d/2)) time and space. This is exponentially better than ordinary BFS, provided you can compute predecessors of the goal and detect frontier intersection efficiently.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which data structure does Uniform-Cost Search use for its frontier?",
    options: [
      "Priority queue ordered by g(n)",
      "FIFO queue",
      "LIFO stack",
      "A hash set keyed by state",
    ],
    answer: 0,
    explanation: "UCS always expands the cheapest unexpanded node, so the frontier is a priority queue keyed on cumulative path cost g(n). This is essentially Dijkstra's algorithm applied to search trees.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which condition is necessary for Uniform-Cost Search to be guaranteed complete?",
    options: [
      "The state space must be a tree",
      "The branching factor must be at most 2",
      "Step costs must all be equal",
      "Every step cost must be >= some constant epsilon > 0",
    ],
    answer: 3,
    explanation: "If some step costs can be arbitrarily close to zero, UCS could keep finding cheaper extensions forever and never expand a true goal. Requiring step cost >= epsilon > 0 prevents this and guarantees completeness (along with non-negative costs).",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Why must UCS test the goal when a node is popped from the frontier, not when it is generated?",
    options: [
      "Because a goal node generated early could be reached more cheaply via another path that has not yet been expanded",
      "To avoid storing the goal in the explored set",
      "Because the priority queue may not have been heapified yet",
      "For performance: popping is faster than generating",
    ],
    answer: 0,
    explanation: "A goal might appear on the frontier with a high cost, while a cheaper path to that same goal state is still being processed. Only when the goal is popped do we know no cheaper path remains, so testing at pop time preserves optimality.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Using the lecture's UCS example - A->D:3, A->B:5, D->E:2, D->F:2, B->C:1, B->E:4, F->G:3, E->G:4, C->E:6, C->G:8 - what is the cost of the optimal path from A to G?",
    options: [
      "7",
      "8",
      "9",
      "14",
    ],
    answer: 1,
    explanation: "UCS expands in order of g(n) and discovers A->D->F->G with cost 3+2+3 = 8. All other paths (A->D->E->G = 9, A->B->E->G = 13, A->B->C->G = 14, etc.) are more expensive.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Why is the assumption 'all step costs are non-negative' important for UCS?",
    options: [
      "Negative costs break UCS's optimality guarantee because revisiting a node could decrease the cumulative cost",
      "Negative costs would make the priority queue underflow",
      "Negative costs are fine; UCS handles them just like Dijkstra does",
      "Negative costs make BFS equivalent to UCS",
    ],
    answer: 0,
    explanation: "UCS relies on the fact that extending a path can only increase its cost. With negative edges, a longer path could become cheaper than one already expanded, invalidating the 'pop = optimal' guarantee (the same reason Dijkstra fails with negative edges).",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Consider the tree from the lecture (A->B,C; B->D,E; C->F,G) with goal = G. IDS is run with limits l = 0, 1, 2. How many node EXPANSIONS occur in total across all three iterations? (Count each pop, alphabetical tie-break, goal test on expansion.)",
    options: [
      "7",
      "10",
      "11",
      "4",
    ],
    answer: 2,
    explanation: "l=0 expands A (1). l=1 expands A,B,C (3). l=2 expands A,B,D,E,C,F,G — that is 7 pops, goal test succeeds on G. Total = 1 + 3 + 7 = 11.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which of these is NOT a standard assumption made for classical (uninformed) search?",
    options: [
      "The environment is fully observable",
      "The environment is deterministic",
      "The state space is continuous",
      "The environment is discrete and known",
    ],
    answer: 2,
    explanation: "Classical search assumes the environment is observable, deterministic, discrete, and known. A discrete (not continuous) state space lets the agent enumerate successors and plan a fixed sequence of actions.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Which statement best describes the practical advantage of IDS over BFS?",
    options: [
      "IDS uses O(b*d) memory instead of BFS's O(b^d), with the same O(b^d) time and the same completeness/optimality guarantees",
      "IDS is asymptotically faster than BFS in time",
      "IDS handles weighted edges while BFS cannot",
      "IDS does not need to know the branching factor",
    ],
    answer: 0,
    explanation: "IDS achieves the same O(b^d) time and the same completeness/optimality properties as BFS for unit-cost problems, but only uses O(b*d) memory because each DFS iteration is linear in depth. That memory advantage is decisive on large state spaces.",
  },
  {
    week: 3,
    topic: "Uninformed Search",
    question: "Graph: S->A:1, S->C:1, A->B:1, B->G:1, C->G:5. Tie-break alphabetically. Compare BFS (goal-test at pop) and UCS - what paths do they return?",
    options: [
      "BFS returns S->A->B->G (cost 3); UCS returns S->C->G (cost 6)",
      "Both return S->A->B->G (cost 3)",
      "Both return S->C->G (cost 6)",
      "BFS returns S->C->G (cost 6); UCS returns S->A->B->G (cost 3)",
    ],
    answer: 3,
    explanation: "BFS finds the shallowest goal: S->C->G is depth 2, while S->A->B->G is depth 3, so BFS returns the depth-2 path (cost 6). UCS finds the cheapest: S->A->B->G costs 1+1+1=3 versus S->C->G's 1+5=6, so UCS returns the cheaper deeper path.",
  },
];

export default l03;
