import type { Question } from "../../types";

const l01: Question[] = [
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Russell & Norvig argue that 'acting rationally' is the preferred framework for AI. What is their main justification?",
    options: [
      "It is the only definition that produces measurable behavior",
      "It is more general than laws of thought and more amenable to scientific development than imitating humans",
      "It is the historically oldest of the four approaches to AI",
      "It guarantees that agents will behave like humans in all situations",
    ],
    answer: 1,
    explanation: "Rationality is mathematically well-defined and fully general, unlike imitating humans (hard to specify) or pure logic (cannot easily handle uncertainty). This makes it the most scientifically tractable foundation.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Which set of five capabilities does Russell & Norvig list as those a machine must possess to pass the (standard) Turing Test?",
    options: [
      "Computer vision, robotics, planning, search, and logic",
      "Natural language processing, knowledge representation, automated reasoning, machine learning, and (for the Total Turing Test) computer vision plus robotics",
      "Symbolic reasoning, perception, control, memory, and emotion",
      "Speech recognition, translation, dialogue, summarization, and question answering",
    ],
    answer: 1,
    explanation: "The standard Turing Test requires NLP, knowledge representation, automated reasoning, and machine learning. The Total Turing Test additionally requires computer vision and robotics for physical interaction.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "In Russell & Norvig's framework, a rational agent is one that:",
    options: [
      "Always achieves the best possible outcome in the environment",
      "Reasons using formal logic from a complete knowledge base",
      "Acts to maximize expected performance given its percepts and knowledge",
      "Behaves indistinguishably from a human expert",
    ],
    answer: 2,
    explanation: "Rationality depends on expected, not actual, performance: the agent does the best it can given what it knows. Omniscience (always best outcome) is not required and is impossible in practice.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Russell & Norvig draw foundational ideas from many disciplines. Which discipline contributed the key idea of utility and decision theory under uncertainty?",
    options: [
      "Philosophy",
      "Economics",
      "Neuroscience",
      "Linguistics",
    ],
    answer: 1,
    explanation: "Economics gave AI utility theory and decision theory, formalizing how rational agents should choose among uncertain outcomes. Philosophy contributed logic and mind, neuroscience the brain model, linguistics language structure.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Why does Russell & Norvig argue the 'laws of thought' (thinking rationally) approach is insufficient as a complete basis for AI?",
    options: [
      "Formal logic cannot represent any real-world knowledge",
      "Informal knowledge is hard to state in logic, and solving problems in principle differs from doing so in practice given computational limits",
      "Logic is incompatible with machine learning",
      "Humans never reason logically, so the approach has no empirical grounding",
    ],
    answer: 1,
    explanation: "Translating informal knowledge into formal logic is hard, especially with uncertainty, and even solvable problems may be computationally intractable. Rationality must therefore account for bounded resources.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "The 'thinking humanly' approach to AI is most closely associated with which research program?",
    options: [
      "Cognitive science: building computational models that match human cognition empirically",
      "Expert systems engineering for industrial applications",
      "Statistical machine learning from large datasets",
      "Formal verification of agent behavior",
    ],
    answer: 0,
    explanation: "Thinking humanly requires a scientific theory of mind, achieved through introspection, psychological experiments, and brain imaging — the domain of cognitive science.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Why do Russell & Norvig include 'limited rationality' (bounded rationality) as a refinement of the rational-agent ideal?",
    options: [
      "Because humans are rarely rational, so AI should not aim too high",
      "Because perfect rationality requires unlimited computation, which no real agent has, so agents must act appropriately given finite resources",
      "Because logical inference is too slow for any practical purpose",
      "Because machine learning has replaced rational reasoning entirely",
    ],
    answer: 1,
    explanation: "Perfect rationality is computationally infeasible in complex environments. Limited rationality acknowledges that good agents must make timely decisions with bounded compute, not exhaustively optimal ones.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Russell & Norvig describe modern AI as containing machine learning, which in turn contains deep learning. What does this nested relationship (AI ⊃ ML ⊃ DL) imply?",
    options: [
      "All AI systems use neural networks at some level",
      "Deep learning is one technique within machine learning, which is one approach within the broader field of AI",
      "Deep learning has replaced symbolic AI as the only viable paradigm",
      "Machine learning and AI are synonyms in modern usage",
    ],
    answer: 1,
    explanation: "AI includes many non-learning methods (search, logic, planning); ML is the subset that improves from data; DL is the subset of ML using deep neural networks. The containment is strict, not equivalence.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Which suggested alternate title does the lecturer propose for the course, reflecting the textbook's preferred view of AI?",
    options: [
      "Symbolic Reasoning",
      "Cognitive Engineering",
      "Computational Rationality",
      "Applied Machine Learning",
    ],
    answer: 2,
    explanation: "The 'Acting rationally' slide explicitly states a better title would be 'Computational Rationality', since AI focuses on agents that do the right thing.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Which combination correctly lists ALL four problems the lecture attributes to the logicist (thinking-rationally) approach?",
    options: [
      "Computational complexity; encoding real-world knowledge; uncertainty; not all rational behavior is logic-based",
      "Slow hardware; lack of data; poor algorithms; weak networks",
      "Lack of training data; overfitting; vanishing gradients; bias",
      "Computational complexity; ethics; hardware cost; user interfaces",
    ],
    answer: 0,
    explanation: "The slide lists exactly four: computational complexity, describing real-world knowledge in logic, dealing with uncertainty, and that much rational behavior has nothing to do with logic.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Which two axes define Russell & Norvig's 2x2 grid of AI definitions?",
    options: [
      "Symbolic vs. statistical, and supervised vs. unsupervised",
      "Human vs. rational, and thought vs. behavior",
      "Strong vs. weak AI, and theory vs. practice",
      "Learning vs. reasoning, and perception vs. action",
    ],
    answer: 1,
    explanation: "Russell & Norvig organize the four definitions of AI along two axes: the standard for success (human-like vs. rational) and what is measured (internal thought vs. external behavior). This produces the four cells: Thinking humanly, Thinking rationally, Acting humanly, and Acting rationally.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Who proposed the Turing Test, and in what year?",
    options: [
      "John McCarthy, 1956",
      "Marvin Minsky, 1969",
      "Alan Turing, 1950",
      "Herbert Simon, 1957",
    ],
    answer: 2,
    explanation: "Alan Turing introduced the imitation game (now called the Turing Test) in 1950, posing the question 'Can a machine think?' McCarthy coined the term 'AI' at Dartmouth in 1956; Minsky & Papert critiqued perceptrons in 1969; Simon made his chess prediction in 1957.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Which approach to AI is most closely tied to cognitive science and neuroscience?",
    options: [
      "Thinking humanly",
      "Acting humanly",
      "Thinking rationally",
      "Acting rationally",
    ],
    answer: 0,
    explanation: "'Thinking humanly' tries to mimic human thought processes and therefore draws on cognitive science and neuroscience (studying the brain as an information-processing machine). 'Acting humanly' is associated with the Turing Test; 'thinking rationally' is the logicist approach; 'acting rationally' is the rational-agent approach.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "What is the Total Turing Test (in contrast to the standard Turing Test)?",
    options: [
      "A test that requires the machine to win every conversation",
      "A test that also includes perception and robotics for physical interaction",
      "A test administered to many machines simultaneously",
      "A test that uses written language only and excludes speech",
    ],
    answer: 1,
    explanation: "The Total Turing Test extends the standard Turing Test by adding perception and robotics, so the machine must also handle the physical world. The standard Turing Test is text-based and requires only NLP, knowledge representation, automated reasoning, and machine learning.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Who built the first model of a neuron, and roughly when?",
    options: [
      "Rosenblatt, in the 1950s",
      "McCulloch & Pitts, in the 1940s",
      "Minsky & Papert, in 1969",
      "McCarthy & Minsky, in 1956",
    ],
    answer: 1,
    explanation: "McCulloch & Pitts proposed the first mathematical model of a neuron in the 1940s, predating the Dartmouth meeting. Rosenblatt later built the perceptron in the 1950s, and Minsky & Papert critiqued perceptrons in 1969.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "What is the Winograd Schema Challenge designed to test, and why was it proposed as a 'better Turing test'?",
    options: [
      "Speech synthesis quality, because audio is harder to fake than text",
      "Pronoun reference in sentences, because it is Google-proof and machine-graded",
      "Robotic dexterity, because it requires physical interaction",
      "Long-form essay writing, because it requires creativity",
    ],
    answer: 1,
    explanation: "Levesque (IJCAI 2013) proposed the Winograd Schema Challenge: multiple-choice questions about pronoun reference (like the trophy/suitcase example). They are designed to be Google-proof, objective, and machine-graded — resistant to the cheap conversational tricks that can fool human judges in a standard Turing Test.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "According to the lecture, rationality concerns:",
    options: [
      "The thought process that produced a decision",
      "Whether the agent uses symbolic logic",
      "The decision that is made, not the process behind it",
      "Whether the agent behaves like a human",
    ],
    answer: 2,
    explanation: "Rationality is about the decision/outcome — did the agent choose the action that maximizes expected utility — not about how it arrived there. The lecture explicitly notes that even a look-up table can be 'rational' if it produces the right action.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "What is the relationship between goals and utility in the rational-agent framework?",
    options: [
      "Goals are a numeric measure of desirability; utility is what you want",
      "Goals describe what you want; utility is the numeric measure of desirability of outcomes",
      "They are synonyms used interchangeably",
      "Utility replaces goals in modern AI; goals are obsolete",
    ],
    answer: 1,
    explanation: "Goals describe what an agent wants to achieve, while utility is the numeric measure of how desirable each outcome is. A rational agent maximizes expected utility in pursuit of its goals.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Which of the following is NOT a subset of machine learning listed in the lecture?",
    options: [
      "Supervised learning",
      "Unsupervised learning",
      "Reinforcement learning",
      "Logicist learning",
    ],
    answer: 3,
    explanation: "The three ML paradigms are supervised, unsupervised, and reinforcement learning; deep learning cuts across all three. 'Logicist' refers to the symbolic-logic approach to AI ('thinking rationally'), which is not a branch of ML.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "What does the lecture's 'artificial flight' analogy argue?",
    options: [
      "Flight succeeded only after engineers stopped imitating birds, so AI should focus on building useful systems rather than fooling humans",
      "Birds are the best model for any flying machine, just as humans are for any thinking machine",
      "Aviation and AI are unrelated and shouldn't be compared",
      "Flight succeeded because engineers perfectly copied bird anatomy",
    ],
    answer: 0,
    explanation: "The analogy: aviation made real progress only when engineers stopped trying to flap like birds and instead designed for the underlying principles. Similarly, AI's goal isn't to deceive humans (imitate them) but to build genuinely useful intelligent systems.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Why did the lecture describe the Turing Test as relying on 'deception,' and how is this typically framed?",
    options: [
      "As a positive feature, because deception proves true intelligence",
      "As a neutral observation with no real consequences",
      "As a criticism: modern AI argues we should not aim to deceive humans",
      "As the main reason the test is still the gold standard today",
    ],
    answer: 2,
    explanation: "The deception-based nature of the Turing Test is treated as a criticism: passing depends on fooling a judge rather than demonstrating useful intelligence. Levesque and others argue we should design tests (like the Winograd Schema) that don't reward deception.",
  },
  {
    week: 1,
    topic: "Introduction to AI",
    question: "Which statement best captures the difference between 'thinking rationally' and 'acting rationally'?",
    options: [
      "Thinking rationally emphasizes the logical process; acting rationally emphasizes the correct/optimal outcome regardless of how it was derived",
      "They are identical — both require symbolic logic",
      "Thinking rationally is about behavior; acting rationally is about internal thought",
      "Acting rationally requires passing the Turing Test; thinking rationally does not",
    ],
    answer: 0,
    explanation: "'Thinking rationally' (the logicist approach) focuses on the deductive process — drawing correct conclusions via formal logic. 'Acting rationally' (the rational-agent approach, the textbook's preferred definition) cares about the outcome: choosing the action that maximizes expected utility, regardless of whether the underlying mechanism is logical, statistical, or even a look-up table.",
  },
];

export default l01;
