import type { Question } from "../../types";

const l07: Question[] = [
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "AIMA defines a CSP as a triple (X, D, C). What do these three components represent?",
    options: [
      "X = states, D = depth, C = cost function",
      "X = expansion, D = decisions, C = children",
      "X = variables, D = domains (one per variable), C = constraints (each specifying allowed value combinations for a subset of variables)",
      "X = solution, D = data, C = complexity",
    ],
    answer: 2,
    explanation: "AIMA chapter 6 defines a CSP by X = {X1,...,Xn} variables, D = {D1,...,Dn} a domain for each variable, and C = a set of constraints, each consisting of a scope (variables involved) and a relation defining allowed assignments.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "In AIMA's canonical Australia map-coloring CSP with 3 colors {R, G, B}, which region borders the MOST other regions and is therefore the best first pick by the Degree heuristic?",
    options: [
      "Western Australia (WA)",
      "Queensland (Q)",
      "South Australia (SA)",
      "Tasmania (T)",
    ],
    answer: 2,
    explanation: "SA borders WA, NT, Q, NSW, and V — five neighbours in the constraint graph. WA has 2 (NT, SA), Q has 3 (NT, SA, NSW), and T has 0. The Degree heuristic picks the variable with the most constraints to other unassigned variables, so SA is chosen first.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Trace AC-3 on a 2-variable CSP: D(X) = {1, 2, 3, 4}, D(Y) = {1, 2, 3, 4}, constraint X = Y^2. After running AC-3 to fixpoint, what are the final domains?",
    options: [
      "D(X) = {1, 2, 3, 4}, D(Y) = {1, 2, 3, 4}",
      "D(X) = {1, 4}, D(Y) = {1, 2}",
      "D(X) = {1, 4, 9, 16}, D(Y) = {1, 2, 3, 4}",
      "D(X) = {}, D(Y) = {}",
    ],
    answer: 1,
    explanation: "Arc X->Y: for each x, need y with x=y^2. x=1 (y=1) keep; x=2 (y=sqrt(2)) drop; x=3 drop; x=4 (y=2) keep. D(X)={1,4}. Arc Y->X: for each y, need x=y^2 in D(X)={1,4}. y=1 (x=1) keep; y=2 (x=4) keep; y=3 (x=9) drop; y=4 (x=16) drop. D(Y)={1,2}. No further pruning.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Trace arc consistency: D(A) = {1, 2, 3, 4, 5}, D(B) = {1, 2, 3}, constraint A = B + 1. After enforcing arc consistency on the arc A->B, what is D(A)?",
    options: [
      "{1, 2, 3, 4}",
      "{2, 3, 4, 5}",
      "{1, 2, 3}",
      "{2, 3, 4}",
    ],
    answer: 3,
    explanation: "Prune A. For each a, need some b in {1,2,3} with a = b+1, i.e. b = a-1. a=1: b=0, no. a=2: b=1, yes. a=3: b=2, yes. a=4: b=3, yes. a=5: b=4, not in D(B), no. D(A)={2,3,4}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Trace arc consistency: D(X) = {1, 2, 3, 4, 5, 6, 7}, D(Y) = {3, 4, 5}, constraints X > Y AND X is odd. After enforcing arc consistency on the arc X->Y (note: X-odd is unary on X, applied first as node consistency), what is D(X)?",
    options: [
      "{1, 3, 5, 7}",
      "{4, 5, 6, 7}",
      "{5, 7}",
      "{3, 5, 7}",
    ],
    answer: 2,
    explanation: "First node-consistency removes even values: D(X) = {1,3,5,7}. Then arc X->Y: need some y in {3,4,5} with x>y. x=1: no y<1, drop. x=3: need y<3, none in {3,4,5}, drop. x=5: y=3 or 4 works. x=7: y=3,4,5 works. D(X)={5,7}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Trace arc consistency: D(X) = {1, 2, 3, 4, 5, 6, 7}, D(Y) = {2, 3, 4, 5}, constraint X + Y = 8. After enforcing arc consistency on BOTH arcs X->Y and Y->X to fixpoint, what are the resulting domains?",
    options: [
      "D(X) = {3, 4, 5, 6}, D(Y) = {2, 3, 4, 5}",
      "D(X) = {1, 2, 3, 4, 5, 6, 7}, D(Y) = {2, 3, 4, 5}",
      "D(X) = {3, 5}, D(Y) = {3, 5}",
      "D(X) = {} , D(Y) = {}",
    ],
    answer: 0,
    explanation: "Arc X->Y: for each x, need y=8-x in D(Y)={2,3,4,5}. x=1: y=7 no. x=2: y=6 no. x=3: y=5 yes. x=4: y=4 yes. x=5: y=3 yes. x=6: y=2 yes. x=7: y=1 no. D(X)={3,4,5,6}. Arc Y->X: need x=8-y in D(X)={3,4,5,6}. y=2: x=6 yes. y=3: x=5 yes. y=4: x=4 yes. y=5: x=3 yes. D(Y)={2,3,4,5}. Stable.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Cryptarithmetic SEND + MORE = MONEY. Each letter is a different digit (Alldiff), leading letters S and M are nonzero, and the sum must hold column-by-column. Which digit must M equal?",
    options: [
      "9",
      "0",
      "Cannot be determined from the constraints alone",
      "1",
    ],
    answer: 3,
    explanation: "The sum of two 4-digit numbers is at most about 19998, so the 5-digit result MONEY starts with at most 1. M cannot be 0 (leading digit), so M = 1.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Which constraint type does the n-queens problem most naturally use, and on how many variables?",
    options: [
      "Unary constraint on each queen",
      "A single ternary constraint on three queens",
      "Binary 'not-same-row' and 'not-same-diagonal' constraints between every pair of queens, plus a global Alldiff on column assignments",
      "Only path consistency constraints",
    ],
    answer: 2,
    explanation: "Modeling queens by column-per-row variable, we need: pairwise binary constraints that no two queens share a row or diagonal, and an Alldiff (global) constraint asserting all column assignments differ. Diagonals are checked pairwise as binary constraints.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Min-conflicts local search for CSPs operates by:",
    options: [
      "Building up a partial assignment one variable at a time using backtracking",
      "Running AC-3 until a fixpoint and reading off a solution",
      "Enumerating all m^n complete assignments and returning the first consistent one",
      "Starting from a complete (possibly inconsistent) assignment, then repeatedly picking a conflicted variable and reassigning it to the value that minimizes the number of remaining conflicts",
    ],
    answer: 3,
    explanation: "Min-conflicts begins with a full assignment, picks any variable currently in conflict, and greedily switches its value to whichever choice yields the fewest conflicts. It famously solves the million-queens problem in a small constant number of steps on average.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Trace arc consistency: D(X) = {1, 2, 3, 4, 5}, D(Y) = {1, 2, 3, 4, 5}, D(Z) = {1, 2, 3, 4, 5}, with constraints X < Y and Y < Z. After AC-3 to fixpoint, what are the final domains?",
    options: [
      "D(X) = {1, 2, 3}, D(Y) = {2, 3, 4}, D(Z) = {3, 4, 5}",
      "D(X) = {1, 2, 3, 4}, D(Y) = {2, 3, 4}, D(Z) = {3, 4, 5}",
      "D(X) = {1, 2, 3, 4}, D(Y) = {1, 2, 3, 4}, D(Z) = {2, 3, 4, 5}",
      "D(X) = {1, 2, 3, 4, 5}, D(Y) = {1, 2, 3, 4, 5}, D(Z) = {1, 2, 3, 4, 5}",
    ],
    answer: 0,
    explanation: "Arc X->Y: need y>x in {1..5}. x=5 has no support, drop. D(X)={1,2,3,4}. Arc Y->X: y must have some x<y in D(X)={1..4}. y=1 fails, drop. D(Y)={2,3,4,5}. Arc Y->Z: y needs z>y in {1..5}. y=5 fails, drop. D(Y)={2,3,4}. Arc Z->Y: need y<z in D(Y)={2,3,4}. z=1,2 fail, drop. D(Z)={3,4,5}. Re-check X->Y with D(Y)={2,3,4}: x=4 needs y>4 in {2,3,4}, drop. D(X)={1,2,3}. Stable: X={1,2,3}, Y={2,3,4}, Z={3,4,5}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5, 6, 7, 8} and D(Y) = {2, 3, 5, 7} with constraint X = Y + 2. After enforcing arc consistency on the arc X→Y, what is D(X)?",
    options: [
      "{4, 5, 7, 9}",
      "{4, 5, 7}",
      "{2, 3, 5, 7}",
      "{3, 4, 5, 6, 7}",
    ],
    answer: 1,
    explanation: "Arc X→Y prunes only X. For each x we need some y in {2,3,5,7} with x = y+2, i.e. y = x-2. x=1: y=-1 no. x=2: y=0 no. x=3: y=1 no. x=4: y=2 yes. x=5: y=3 yes. x=6: y=4 not in D(Y). x=7: y=5 yes. x=8: y=6 not in D(Y). D(X)={4,5,7}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5} and D(Y) = {1, 2, 3, 4, 5} with constraint Y = 2X. After enforcing arc consistency on the arc X→Y, what is D(X)?",
    options: [
      "{1, 2, 3, 4, 5}",
      "{2, 4}",
      "{1, 2}",
      "{1, 2, 4}",
    ],
    answer: 2,
    explanation: "Prune X. For each x we need some y in D(Y) with y = 2x. x=1: y=2 in D(Y) ✓. x=2: y=4 in D(Y) ✓. x=3: y=6 not in D(Y). x=4: y=8 not in D(Y). x=5: y=10 not in D(Y). D(X)={1,2}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5, 6} and D(Y) = {2, 4, 6} with constraint X + Y = 7. After enforcing arc consistency on the arc X→Y, what is D(X)?",
    options: [
      "{1, 3, 5}",
      "{2, 4, 6}",
      "{1, 2, 3, 4, 5, 6}",
      "{3, 5}",
    ],
    answer: 0,
    explanation: "Prune X. For each x we need some y in {2,4,6} with x+y=7, i.e. y=7-x. x=1: y=6 ✓. x=2: y=5 not in D(Y). x=3: y=4 ✓. x=4: y=3 not in D(Y). x=5: y=2 ✓. x=6: y=1 not in D(Y). D(X)={1,3,5}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5, 6, 7} and D(Y) = {2, 3, 4} with combined constraints X > Y AND X < 2Y. After enforcing arc consistency on the arc X→Y, what is D(X)?",
    options: [
      "{3, 4, 5, 6, 7}",
      "{2, 3, 4, 5, 6}",
      "{3, 4, 5}",
      "{4, 5, 6, 7}",
    ],
    answer: 0,
    explanation: "Both constraints must hold for the same y. x=1: need y<1, none. x=2: need y<2 AND y>1, none in {2,3,4}. x=3: y=2 gives 3>2 ✓ and 3<4 ✓, keep. x=4: y=3 gives 4>3 ✓ and 4<6 ✓, keep. x=5: y=3 gives 5>3 ✓ and 5<6 ✓, keep. x=6: y=4 gives 6>4 ✓ and 6<8 ✓, keep. x=7: y=4 gives 7>4 ✓ and 7<8 ✓, keep. D(X)={3,4,5,6,7}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(A) = {1, 2, 3, 4, 5} and D(B) = {2, 4} with constraint 'A + B is even'. After enforcing arc consistency on the arc A→B, what is D(A)?",
    options: [
      "{1, 2, 3, 4, 5}",
      "{2, 4}",
      "{1, 3, 5}",
      "{2, 3, 4}",
    ],
    answer: 1,
    explanation: "A+B is even iff A and B have the same parity. D(B)={2,4} contains only even numbers, so we need A to be even. a=1: needs b odd, none in D(B), remove. a=2: b=2 or 4 even ✓. a=3: needs odd b, none, remove. a=4: ✓. a=5: remove. D(A)={2,4}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5, 6} and D(Y) = {1, 2, 3, 4, 5, 6} with constraint X · Y = 12 (product equals 12). After enforcing arc consistency on the arc X→Y, what is D(X)?",
    options: [
      "{2, 3, 4, 6}",
      "{1, 2, 3, 4, 6}",
      "{3, 4, 6}",
      "{2, 3, 4, 6, 12}",
    ],
    answer: 0,
    explanation: "Prune X. For each x we need some y in {1..6} with x·y=12, i.e. y=12/x. x=1: y=12 not in D(Y). x=2: y=6 ✓. x=3: y=4 ✓. x=4: y=3 ✓. x=5: y=12/5 not integer. x=6: y=2 ✓. D(X)={2,3,4,6}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5, 6} and D(Y) = {1, 2, 3} with constraint X - Y = 2. After enforcing arc consistency on the arc X→Y, what is D(X)?",
    options: [
      "{3, 4, 5}",
      "{1, 2, 3}",
      "{3, 4, 5, 6}",
      "{1, 3, 5}",
    ],
    answer: 0,
    explanation: "Prune X. For each x we need some y in {1,2,3} with x-y=2, i.e. y=x-2. x=1: y=-1, no. x=2: y=0, no. x=3: y=1 ✓. x=4: y=2 ✓. x=5: y=3 ✓. x=6: y=4 not in D(Y), no. D(X)={3,4,5}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5} and D(Y) = {1, 2, 3, 4, 5} with combined constraints X ≠ Y AND X + Y ≤ 5. After enforcing arc consistency on the arc X→Y, what is D(X)?",
    options: [
      "{1, 2, 3, 4, 5}",
      "{1, 2, 3, 4}",
      "{1, 2, 3}",
      "{1, 2}",
    ],
    answer: 1,
    explanation: "Both constraints must hold for the same y. x=1: y∈{2,3,4} (y≠1, y≤4) ✓. x=2: y∈{1,3} (y≠2, y≤3) ✓. x=3: y∈{1,2} (y≠3, y≤2) ✓. x=4: y=1 (y≠4, y≤1) ✓. x=5: need y≠5 AND y≤0, impossible. D(X)={1,2,3,4}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "We just chose variable X with D(X) = {red, green, blue}. X has 3 unassigned neighbours. Assigning X=red would eliminate 4 total values from neighbour domains; X=green would eliminate 2; X=blue would eliminate 5. By the LCV (Least Constraining Value) heuristic, what order should X's values be tried?",
    options: [
      "blue, red, green",
      "red, green, blue",
      "green, red, blue",
      "green, blue, red",
    ],
    answer: 2,
    explanation: "LCV orders values from least to most constraining — the value that rules out the fewest neighbour options first. green eliminates 2 (best), red eliminates 4 (middle), blue eliminates 5 (worst). Order: green, red, blue.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "CSP with 3 variables A, B, C, each with domain {1,2,3}, and constraints A<B, B<C, A≠C. We assign A=2 and then run forward checking. What are D(B) and D(C) immediately after forward checking propagates the assignment A=2?",
    options: [
      "D(B)={3}, D(C)={1,3}",
      "D(B)={3}, D(C)={1,2,3}",
      "D(B)={1,2,3}, D(C)={1,2,3}",
      "D(B)={3}, D(C)={3}",
    ],
    answer: 1,
    explanation: "Forward checking only propagates from the just-assigned variable A=2 to its unassigned neighbours. A<B forces B>2, so D(B)={3}. A≠C removes 2 from D(C), giving D(C)={1,3}. FC does NOT propagate the new D(B)={3} into D(C); that would require AC. So D(C) still includes 1, even though once B=3 is forced, C must be >3 (impossible).",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Same CSP as the previous question: variables A,B,C with domain {1,2,3}, constraints A<B, B<C, A≠C, and we just assigned A=2. After forward checking we have D(B)={3}, D(C)={1,3}. We now run full AC-3 to propagate further. What happens?",
    options: [
      "AC-3 leaves the domains unchanged",
      "AC-3 finds an inconsistency: D(C) becomes empty after propagating B<C with D(B)={3}",
      "AC-3 shrinks D(C) to {3} but the CSP remains solvable",
      "AC-3 shrinks D(B) to {} immediately",
    ],
    answer: 1,
    explanation: "AC-3 enforces arc C→B (or B→C). From B<C with D(B)={3}: any c in D(C) needs some b<c in {3}, so c must be >3. c=1: no b<1, remove. c=3: no b<3 in {3}, remove. D(C)=∅, inconsistency detected. This failure between two still-unassigned variables (B and C) is exactly what FC misses but AC-3 catches.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "A CSP is best characterized as which kind of problem?",
    options: [
      "An identification problem where we want a goal state, not a path",
      "A planning problem requiring an optimal path",
      "An adversarial search problem",
      "A reinforcement learning problem",
    ],
    answer: 0,
    explanation: "CSPs are identification problems: we only care about finding a complete, consistent assignment (a state), not the sequence of actions that produced it.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Given D(X) = {1, 2, 3, 4, 5} and D(Y) = {1, 3, 5} with constraint X < Y, what is D(X) after enforcing arc consistency on the arc X→Y?",
    options: [
      "{1, 2, 3}",
      "{1, 2, 3, 4}",
      "{1, 2, 3, 4, 5}",
      "{3, 5}",
    ],
    answer: 1,
    explanation: "Arc X→Y prunes only X. For each x we need some y in {1,3,5} with y>x. x=1,2,3,4 all have y=5 as support; x=5 has no y>5 so 5 is removed. D(X)={1,2,3,4}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(A) = {1, 2, 3, 4} and D(B) = {2, 3} with constraint A > B. After enforcing arc consistency on A→B, what is D(A)?",
    options: [
      "{3, 4}",
      "{4}",
      "{2, 3, 4}",
      "{1, 2, 3, 4}",
    ],
    answer: 0,
    explanation: "We prune A. For each a we need some b in {2,3} with a>b. a=1: no b<1, remove. a=2: need b<2, none, remove. a=3: b=2 works. a=4: b=2 or 3 works. D(A)={3,4}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5, 6}, D(Y) = {2, 3, 4}, constraint X = 2Y (X equals twice Y). After enforcing arc consistency on X→Y, what is D(X)?",
    options: [
      "{2, 4, 6}",
      "{4, 6}",
      "{4, 6, 8}",
      "{1, 2, 3, 4, 5, 6}",
    ],
    answer: 1,
    explanation: "We prune X. For each x, need y in {2,3,4} with x=2y, i.e. y=x/2. x=1: no. x=2: y=1 not in domain, no. x=3: no. x=4: y=2 ✓. x=5: no. x=6: y=3 ✓. Also x=8 would need y=4 but 8 ∉ D(X). D(X)={4,6}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5}, D(Y) = {1, 2, 3, 4, 5}, constraints X < Y AND X + Y = 6. After enforcing arc consistency on X→Y, what is D(X)?",
    options: [
      "{1, 2}",
      "{1, 2, 3}",
      "{1, 2, 3, 4, 5}",
      "{4, 5}",
    ],
    answer: 0,
    explanation: "Both constraints must hold for the same y. x=1: y=5 gives 1<5 ✓ and 1+5=6 ✓, keep. x=2: y=4 gives 2<4 ✓ and 2+4=6 ✓, keep. x=3: would need y=3 but 3<3 fails. x=4,5: x≥y/2 violates X<Y given sum=6. D(X)={1,2}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(A) = {1, 2, 3}, D(B) = {1, 2, 3}, constraint A ≠ B. After enforcing arc consistency on A→B, what is D(A)?",
    options: [
      "{} (empty)",
      "{1}",
      "{1, 2}",
      "{1, 2, 3}",
    ],
    answer: 3,
    explanation: "For every a in {1,2,3}, there exists some b ≠ a in {1,2,3} (e.g. for a=1, b=2). So no value is pruned. The ≠ constraint never prunes when both domains have size ≥ 2.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(X) = {1, 2, 3, 4, 5, 6}, D(Y) = {2, 4, 6}, constraints X < Y AND X + Y > 8. Enforcing arc consistency on Y→X, what is the resulting D(Y)?",
    options: [
      "{2, 4, 6}",
      "{4, 6}",
      "{6}",
      "{}",
    ],
    answer: 2,
    explanation: "Now we prune Y. For each y, need x in D(X) with x<y AND x+y>8. y=2: need x<2 AND x>6, impossible. y=4: need x<4 AND x>4, impossible. y=6: need x<6 AND x>2, so x ∈ {3,4,5} works. D(Y)={6}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Which of the following statements about arc consistency is TRUE?",
    options: [
      "Enforcing arc X→Y prunes values from D(Y)",
      "Arc consistency is the same as forward checking",
      "Arc consistency alone always solves a CSP without search",
      "Enforcing arc X→Y prunes values from D(X) only",
    ],
    answer: 3,
    explanation: "Arc X→Y prunes only the tail X: we remove an x in D(X) if no y in D(Y) satisfies the constraint. To prune Y you must run the reverse arc Y→X.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Unassigned variables have current domain sizes 4, 2, 3, 1, 5. The MRV (Minimum Remaining Values) heuristic picks the variable with domain size:",
    options: [
      "5 (largest)",
      "3 (median)",
      "1 (smallest)",
      "4",
    ],
    answer: 2,
    explanation: "MRV picks the most constrained variable — the one with the FEWEST legal values remaining (1 here). The idea is to fail fast: if a variable has 0 or 1 options, we should commit/fail immediately.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "The Degree heuristic is best used as:",
    options: [
      "The primary variable selection method instead of MRV",
      "A tie-breaker when MRV produces multiple candidates, or as the first pick when no variable is assigned",
      "A value ordering heuristic",
      "A method for enforcing arc consistency",
    ],
    answer: 1,
    explanation: "The Degree heuristic chooses the variable involved in the most constraints with other unassigned variables. It is typically a tie-breaker for MRV, and most useful as the very first choice when all domains are equal.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "The Least Constraining Value (LCV) heuristic orders the values of a chosen variable to:",
    options: [
      "Eliminate the most options from neighbours' domains first",
      "Maximize the number of conflicts",
      "Leave the maximum number of options open in neighbours' domains",
      "Try the largest numeric value first",
    ],
    answer: 2,
    explanation: "LCV picks the value that rules out the fewest options in the domains of neighbouring variables, leaving maximum flexibility — the 'succeed-first' philosophy for values, opposite to MRV's 'fail-first' for variables.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Which propagation technique is strictly stronger?",
    options: [
      "Forward checking is stronger than arc consistency",
      "They are exactly equivalent",
      "Neither — they detect disjoint sets of failures",
      "Arc consistency is strictly stronger than forward checking",
    ],
    answer: 3,
    explanation: "Arc consistency catches all failures forward checking catches, plus failures between two still-unassigned variables. FC only propagates from the just-assigned variable to its neighbours; AC propagates among all variables until fixpoint.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "In Australia map coloring, why can Tasmania's color be decided independently of the other states?",
    options: [
      "Because it is a disconnected component in the constraint graph (no edges)",
      "Because of MRV",
      "Because it has the smallest domain",
      "Because it is alphabetically last",
    ],
    answer: 0,
    explanation: "Tasmania shares no border with any mainland state, so in the constraint graph it has no edges. Disconnected components of a CSP can be solved independently.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Naive DFS over a CSP with n variables and m values per variable has roughly n!·m^n leaves. Why does backtracking reduce this to m^n?",
    options: [
      "Backtracking uses heuristics like MRV",
      "Variable assignments are commutative, so we can fix one variable order instead of permuting all orders",
      "Backtracking does inference at every step",
      "Backtracking uses min-conflicts",
    ],
    answer: 1,
    explanation: "Because assigning X=a then Y=b is equivalent to Y=b then X=a, we can fix a single ordering of variables. This removes the n! factor coming from all permutations, leaving m^n leaves.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Node consistency enforces which type of constraint?",
    options: [
      "Unary constraints",
      "Binary constraints",
      "Ternary constraints",
      "Global Alldiff constraints",
    ],
    answer: 0,
    explanation: "A variable X is node-consistent iff every value in D(X) satisfies every unary constraint on X. It is enforced trivially by removing forbidden values from D(X).",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Which problem is the canonical use case for min-conflicts local search?",
    options: [
      "Sudoku puzzles with few givens",
      "Tree-structured CSPs",
      "Cryptarithmetic",
      "N-queens for very large N (e.g. N = 1,000,000)",
    ],
    answer: 3,
    explanation: "Min-conflicts starts from a complete assignment and repeatedly reassigns a conflicted variable to the value with fewest conflicts. It solves N-queens for N up to a million in seconds, dramatically outperforming backtracking.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "In AC-3, after REVISE removes some value from D(Xi), which arcs should be re-added to the queue?",
    options: [
      "Only (Xi, Xj)",
      "All arcs in the CSP",
      "All arcs (Xk, Xi) where Xk is a neighbour of Xi and Xk ≠ Xj",
      "All arcs (Xi, Xk)",
    ],
    answer: 2,
    explanation: "When D(Xi) shrinks, any inbound arc Xk→Xi may have lost support and must be re-examined. AC-3 adds these inbound arcs (excluding the one we just came from) back into the queue.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Forward checking, after assigning X = v, will:",
    options: [
      "Run AC-3 to fixpoint over the whole CSP",
      "Remove from each unassigned neighbour Y's domain any value inconsistent with v",
      "Check consistency only between pairs of already-assigned variables",
      "Reassign every variable using min-conflicts",
    ],
    answer: 1,
    explanation: "Forward checking propagates the new assignment X=v locally: for each unassigned neighbour Y, it deletes from D(Y) any value inconsistent with v. If D(Y) becomes empty, we backtrack immediately.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Which problem features the global constraint Alldiff?",
    options: [
      "Map coloring",
      "Sudoku (per row, column, and 3×3 box) and cryptarithmetic (over letters)",
      "Tree-structured CSPs",
      "Min-conflicts search",
    ],
    answer: 1,
    explanation: "Alldiff(X1,...,Xn) asserts that all listed variables take distinct values. In Sudoku it applies to each row, column, and 3×3 box. In cryptarithmetic, the letters must each represent a different digit.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "What is the time complexity of AC-3, where c is the number of binary constraints and d is the maximum domain size?",
    options: [
      "O(c·d)",
      "O(c·d²)",
      "O(c·d³)",
      "O(d^c)",
    ],
    answer: 2,
    explanation: "AC-3 has worst-case complexity O(c·d³). Each arc may be inserted into the queue O(d) times, and REVISE for one arc costs O(d²).",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "In the Australia map-coloring CSP under 'adjacent regions differ', how many neighbours does SA (South Australia) have in the constraint graph?",
    options: [
      "3",
      "4",
      "5",
      "6",
    ],
    answer: 2,
    explanation: "SA borders WA, NT, Q, NSW, and V — five mainland neighbours. It does NOT border Tasmania (T).",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "D(P) = {1, 2, 3, 4}, D(Q) = {2, 3}, constraint P + Q = 5. After enforcing arc consistency on P→Q, what is D(P)?",
    options: [
      "{2, 3}",
      "{1, 2, 3, 4}",
      "{3, 4}",
      "{2, 3, 4}",
    ],
    answer: 0,
    explanation: "For each p we need some q in {2,3} with p+q=5, i.e. q=5−p. p=1: q=4, not in D(Q), remove. p=2: q=3 ✓. p=3: q=2 ✓. p=4: q=1, not in D(Q), remove. D(P)={2,3}.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Why are binary CSPs considered general enough to cover most CSP theory?",
    options: [
      "Because all real-world CSPs happen to be binary",
      "Because any k-ary constraint can be converted into a set of binary constraints using auxiliary variables",
      "Because AC-3 only works on unary constraints",
      "Because Alldiff is automatically binary",
    ],
    answer: 1,
    explanation: "Any higher-order (k-ary) constraint can be reformulated as a set of binary constraints by introducing auxiliary variables that encode tuples. Hence algorithms designed for binary CSPs (like AC-3) cover the general case.",
  },
  {
    week: 7,
    topic: "Constraint Satisfaction Problems",
    question: "Which statement about CSP search complexity is correct?",
    options: [
      "Every CSP can be solved in polynomial time",
      "CSPs are always exponential, even for tree structures",
      "Min-conflicts guarantees a solution in linear time",
      "CSPs are NP-complete in general, but tree-structured CSPs can be solved in O(n·d²)",
    ],
    answer: 3,
    explanation: "General CSPs are NP-complete (exponential worst case). However, when the constraint graph is a tree, the CSP can be solved in O(n·d²) by directional arc consistency followed by an assignment sweep.",
  },
];

export default l07;
