import type { Question } from "../../types";

const l04: Question[] = [
  {
    week: 4,
    topic: "Informed Search",
    question: "AIMA defines a heuristic h(n) as admissible iff, for every node n, the following holds:",
    options: [
      "h(n) >= h*(n) and h(goal) = 0",
      "h(n) <= h*(n) and h(goal) = 0",
      "h(n) <= c(n,a,n') + h(n') for every successor n'",
      "h(n) = g(n) + h*(n)",
    ],
    answer: 1,
    explanation: "Admissibility means h never overestimates the true optimal cost-to-go: h(n) <= h*(n) for all n, with h(goal)=0. Option C is the stronger consistency condition.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "AIMA proves that a consistent heuristic is also admissible. The intuition is that consistency h(n) <= c(n,a,n') + h(n') applied along the optimal path from n to the goal:",
    options: [
      "Telescopes into h(n) <= h*(n), so h is admissible",
      "Forces h(n) = h*(n) exactly",
      "Implies h(goal) > 0",
      "Is unrelated to admissibility",
    ],
    answer: 0,
    explanation: "Summing the consistency inequality along the optimal path from n to a goal yields h(n) <= sum of edge costs + h(goal) = h*(n) + 0 = h*(n). Hence consistent => admissible.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "HAND-TRACE. Graph: S(h=6), A(h=4), B(h=2), G(h=0). Edges (undirected costs): S-A=2, S-B=5, A-B=1, A-G=8, B-G=3. Run A* tree search. What total cost does A* return?",
    options: [
      "6 (path S->A->B->G)",
      "8 (path S->B->G)",
      "10 (path S->A->G)",
      "11 (path S->A->B->G via repeat)",
    ],
    answer: 0,
    explanation: "f(A)=2+4=6, f(B via S)=5+2=7. Expand A. New: f(B via A)=2+1+2=5, f(G via A)=2+8+0=10. Expand B (f=5). New: f(G via A->B)=2+1+3+0=6. Expand G, cost 6. Path S->A->B->G.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "HAND-TRACE. Same graph as T3 [S(h=6), A(h=4), B(h=2), G(h=0); S-A=2, S-B=5, A-B=1, A-G=8, B-G=3]. Run GREEDY best-first (smallest h, ties alphabetical). What path and cost does Greedy return?",
    options: [
      "S->A->B->G, cost 6",
      "S->B->G, cost 8",
      "S->A->G, cost 10",
      "S->B->A->G, cost 14",
    ],
    answer: 1,
    explanation: "Greedy ignores g. From S, children A(h=4), B(h=2): pick B. From B, child G(h=0): pick G. Path S->B->G, cost 5+3=8. Greedy returns 8, A* returns 6 — A* beats Greedy here.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "HAND-TRACE consistency. Graph edge A->B with cost c(A,B)=4. Heuristic values h(A)=8, h(B)=3. Is consistency violated on this edge?",
    options: [
      "No — 8 <= 4 + 3 holds",
      "Cannot tell without h*",
      "Yes — 8 > 4 + 3, so h(A) > c(A,B) + h(B)",
      "Only if h(B)=0",
    ],
    answer: 2,
    explanation: "Consistency requires h(A) <= c(A,B) + h(B), i.e. 8 <= 4+3 = 7. Since 8 > 7, consistency fails on this edge. (h may still be admissible globally, but it is not consistent.)",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "For the 8-puzzle, AIMA reports that h2 (Manhattan distance) dominates h1 (misplaced tiles). What is the practical consequence of dominance when both are admissible?",
    options: [
      "h1 becomes inadmissible whenever h2 exists",
      "h2 must equal the true cost h*",
      "A* with h2 expands no more nodes than A* with h1",
      "A* with h2 always finds a strictly shorter solution path",
    ],
    answer: 2,
    explanation: "If h2(n) >= h1(n) for all n and both are admissible, then h2 dominates h1. A* with h2 expands no more nodes (and usually far fewer) than A* with h1, since every node A* with h2 expands has f-value <= C*, which is also true under h1.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "AIMA introduces the effective branching factor b*. If a problem with solution depth d is solved by expanding N+1 total nodes, b* is defined by the equation:",
    options: [
      "N + 1 = 1 + b* + (b*)^2 + ... + (b*)^d",
      "N + 1 = b* * d",
      "b* = N / d",
      "b* = log_b(N)",
    ],
    answer: 0,
    explanation: "b* is the branching factor a uniform tree of depth d would need to contain N+1 nodes: N+1 = 1 + b* + (b*)^2 + ... + (b*)^d. A well-designed heuristic gives b* close to 1.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "AIMA describes pattern databases. What does a DISJOINT pattern database allow that an ordinary one does not?",
    options: [
      "Storing exact costs h* in a table",
      "Replacing A* with greedy search",
      "Computing heuristics on the fly without storage",
      "Summing the costs from multiple sub-patterns (and still being admissible)",
    ],
    answer: 3,
    explanation: "If patterns are disjoint (each move contributes to exactly one sub-pattern's cost), the sum of their pattern-DB costs is an admissible heuristic. Ordinary (overlapping) pattern DBs require taking max, not sum, to stay admissible.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "AIMA contrasts IDA*, RBFS, and SMA*. Which statement is correct?",
    options: [
      "IDA* uses linear memory by iterating depth-limited searches with an f-cost cutoff",
      "RBFS uses exponential memory like A*",
      "SMA* refuses to run if memory is insufficient for the optimal path",
      "IDA* and RBFS both store the full closed list",
    ],
    answer: 0,
    explanation: "IDA* runs DFS-style searches with increasing f-cost bounds — memory is O(bd). RBFS uses linear memory by tracking f-limits and backtracking. SMA* uses all available memory and drops worst-f nodes when full.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "HAND-TRACE Weighted A* with w=2 on: S(h=4), A(h=3), B(h=1), G(h=0). Edges S->A=1, S->B=5, A->G=10, B->G=1. Using f(n)=g(n)+w*h(n) and tree search, which node is expanded first after S, and what path does w=2 ultimately return?",
    options: [
      "Expand B first; return S->B->G (cost 6)",
      "Expand A first; return S->A->G (cost 11)",
      "Expand A first; return S->B->G (cost 6)",
      "Expand B first; return S->A->G (cost 11)",
    ],
    answer: 2,
    explanation: "After S: f(A)=1+2*3=7, f(B)=5+2*1=7. Tie; alphabetical picks A. Expand A: f(G via A)=11+0=11. Frontier: B(f=7), G(f=11). Expand B: f(G via B)=6+0=6. Expand G, cost 6 (path S->B->G). Optimal here (C*=6), within bound w*C*=12.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Nodes S(h=10), A(h=6), B(h=4), G(h=0). Edges: S->A cost 3, S->B cost 5, A->G cost 8, B->G cost 6. Using A* (tree search, ties alphabetical), what is f(B) when B is added to the frontier?",
    options: [
      "4",
      "5",
      "9",
      "11",
    ],
    answer: 2,
    explanation: "g(B) = cost(S->B) = 5 and h(B) = 4, so f(B) = g + h = 5 + 4 = 9.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Same graph as X1: S(h=10), A(h=6), B(h=4), G(h=0); S->A(3), S->B(5), A->G(8), B->G(6). What total path cost does A* return?",
    options: [
      "8",
      "11",
      "12",
      "14",
    ],
    answer: 1,
    explanation: "Path S->A->G costs 3+8 = 11; path S->B->G costs 5+6 = 11. Both are 11, so A* returns cost 11 (S->A->G first by alphabetical tie-breaking).",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Greedy best-first on: S(h=8), A(h=3), B(h=5), C(h=1), G(h=0). Edges: S->A(2), S->B(1), A->C(7), B->C(2), C->G(4). Which path does Greedy return?",
    options: [
      "S -> A -> C -> G",
      "S -> B -> C -> G",
      "S -> B -> G",
      "S -> A -> G",
    ],
    answer: 0,
    explanation: "Greedy expands by smallest h: from S, A(h=3) < B(h=5), so go to A. From A, only child C(h=1). From C, only child G(h=0). Path: S->A->C->G.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "On the same graph as X3, what total path cost does A* return (tree search, admissible h)?",
    options: [
      "7 (S->B->C->G)",
      "13 (S->A->C->G)",
      "5 (S->B->G)",
      "11 (S->A->G)",
    ],
    answer: 0,
    explanation: "Paths: S->A->C->G = 2+7+4 = 13; S->B->C->G = 1+2+4 = 7. A* picks the cheaper one, cost 7. Note Greedy picked the 13-cost path — classic A*-beats-Greedy case.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Using the Lab 3 graph (start A, goals {K,L}, h-values: A=6,B=5,C=5,D=2,E=4,F=5,G=4,H=1,I=2,J=1,K=0,L=0; standard edge costs from search_a_star.py), what are f-values of A's three children when A is expanded?",
    options: [
      "f(B)=6, f(C)=7, f(D)=6",
      "f(B)=5, f(C)=5, f(D)=2",
      "f(B)=1, f(C)=2, f(D)=4",
      "f(B)=11, f(C)=12, f(D)=10",
    ],
    answer: 0,
    explanation: "g(B)=1, h(B)=5 -> f=6; g(C)=2, h(C)=5 -> f=7; g(D)=4, h(D)=2 -> f=6. So B and D tie at f=6, C is 7.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Continuing the Lab 3 A* trace: after A is expanded, B and D both have f=6 (B first, alphabetically). After B is expanded, what are f(E) and f(F) via B?",
    options: [
      "f(E)=4, f(F)=5",
      "f(E)=8, f(F)=11",
      "f(E)=3, f(F)=6",
      "f(E)=7, f(F)=10",
    ],
    answer: 1,
    explanation: "Via B: g(E)=1+3=4, h(E)=4 -> f=8; g(F)=1+5=6, h(F)=5 -> f=11.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "On the Lab 3 graph, after expanding A then B then D, which node from the frontier does A* expand next?",
    options: [
      "C with f=7",
      "E with f=8",
      "H with f=6",
      "J with f=7",
    ],
    answer: 2,
    explanation: "After expanding D, H is added with g=4+1=5 and h=1, so f(H)=6. Frontier f-values: H=6, C=7, J=7, E=8, I=10, F=11. The minimum is H at f=6.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "On a 4-node graph: S(h=5), A(h=4), B(h=1), G(h=0). Edge S->A cost 1; edge A->B cost 1; edge B->G cost 1. Is h consistent on edge S->A?",
    options: [
      "Yes, h(S) - h(A) = 1 <= c(S,A) = 1",
      "No, h(S) > h(A)",
      "No, h(S) > c(S,A) + h(A)",
      "Cannot determine without h*",
    ],
    answer: 0,
    explanation: "Consistency on edge S->A: h(S) <= c(S,A) + h(A), i.e., 5 <= 1 + 4 = 5. Holds with equality, so consistent on this edge.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "A heuristic gives h(n) = 3 and the true optimal cost from n to the goal is h*(n) = 5. Is h admissible at n?",
    options: [
      "Yes, h(n) <= h*(n) (3 <= 5)",
      "No, h underestimates",
      "Yes, but only with a closed list",
      "No, because h != h*",
    ],
    answer: 0,
    explanation: "Admissible means h(n) <= h*(n). 3 <= 5, so h is admissible at n. Underestimating is exactly the optimistic property A* needs.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "A heuristic gives h(n) = 7 while the true optimal cost h*(n) = 4. Is h admissible at n, and what could go wrong?",
    options: [
      "Admissible — A* still finds optimum",
      "Not admissible — A* may return a sub-optimal solution",
      "Admissible — only consistency matters",
      "Not admissible — but Greedy is still optimal",
    ],
    answer: 1,
    explanation: "h(n) = 7 > h*(n) = 4, so h overestimates and is NOT admissible. A* loses its optimality guarantee — it may overlook the truly cheapest path.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "What does the heuristic function h(n) represent in informed search?",
    options: [
      "The actual path cost from the start node to n",
      "The estimated cost of the cheapest path from n to a goal",
      "The number of nodes already expanded",
      "The branching factor of the search tree",
    ],
    answer: 1,
    explanation: "h(n) is the heuristic estimate of the cheapest cost from the current node n to the nearest goal. It encodes domain knowledge used to guide the search.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Which value must h(goal) equal for the heuristic to be admissible?",
    options: [
      "1",
      "Infinity",
      "0",
      "The branching factor b",
    ],
    answer: 2,
    explanation: "h(goal) = 0 because the true remaining cost from a goal to itself is zero. Any positive value would overestimate this cost and break admissibility.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "A heuristic h estimates the cost from node n to the goal as 5, but the true optimal cost h*(n) is 7. Is h admissible at n?",
    options: [
      "Yes, because h(n) <= h*(n)",
      "No, because h underestimates the true cost",
      "Only if the graph is a tree",
      "Only if h is also consistent",
    ],
    answer: 0,
    explanation: "Admissibility requires h(n) <= h*(n) (never overestimate). 5 <= 7, so h is admissible at this node. Underestimating is exactly what 'optimistic' means.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "A heuristic h estimates 9 at node n, but the true optimal cost h*(n) is 6. Is h admissible at n?",
    options: [
      "Yes, because higher h means more informed",
      "Yes, because admissibility requires h >= h*",
      "No, because h(n) > h*(n) (overestimates)",
      "Only if the search is greedy",
    ],
    answer: 2,
    explanation: "Admissibility means h must never exceed the true cost: h(n) <= h*(n). Here 9 > 6, so h overestimates and is NOT admissible.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Which inequality defines a CONSISTENT heuristic for every edge n -> n' with cost c(n,a,n')?",
    options: [
      "h(n) <= h*(n)",
      "h(n) <= c(n,a,n') + h(n')",
      "h(n) >= c(n,a,n') + h(n')",
      "h(n) = g(n) + h(n')",
    ],
    answer: 1,
    explanation: "Consistency (monotonicity) is the triangle inequality: h(n) <= c(n,a,n') + h(n'). This guarantees f-values never decrease along any path, which makes A* with graph search optimal.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Which statement about admissibility and consistency is TRUE?",
    options: [
      "Consistent implies admissible, but not vice versa",
      "Admissible implies consistent",
      "They are equivalent",
      "Neither implies the other",
    ],
    answer: 0,
    explanation: "Consistency is the stronger property: every consistent heuristic is admissible, but an admissible heuristic need not be consistent.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Greedy best-first search is best described as:",
    options: [
      "Complete and optimal",
      "Complete but not optimal",
      "Neither complete nor optimal",
      "Optimal but not complete",
    ],
    answer: 2,
    explanation: "Greedy expands the node with smallest h(n) and can loop or commit to dead ends; it is neither complete (without cycle checking) nor optimal.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "What evaluation function does A* use?",
    options: [
      "f(n) = h(n)",
      "f(n) = g(n)",
      "f(n) = g(n) + h(n)",
      "f(n) = g(n) * h(n)",
    ],
    answer: 2,
    explanation: "A* ranks frontier nodes by f(n) = g(n) + h(n), the actual cost to reach n plus the estimated remaining cost — the estimated total cost of a path through n.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Consider nodes A(h=5), B(h=3), C(h=0, goal) with edges A->B cost 2 and B->C cost 4. What is f(B) when B is reached via A->B?",
    options: [
      "3",
      "5",
      "6",
      "7",
    ],
    answer: 1,
    explanation: "g(B) = cost(A->B) = 2 and h(B) = 3, so f(B) = g(B) + h(B) = 2 + 3 = 5.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Same graph: A(h=5), B(h=3), C(h=0 goal); edges A->B(2), B->C(4), A->C(10). Assuming the heuristic is admissible, what total path cost will A* return?",
    options: [
      "5",
      "6",
      "10",
      "12",
    ],
    answer: 1,
    explanation: "Two paths exist: A->B->C with cost 2+4 = 6 and A->C directly with cost 10. A* with an admissible heuristic returns the optimal path, which is 6.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "For the 8-puzzle, h1 = number of misplaced tiles and h2 = sum of Manhattan distances of all tiles to their goal positions. Which is true?",
    options: [
      "h1 dominates h2",
      "h2 dominates h1 (both admissible, h2 >= h1)",
      "Neither dominates the other",
      "h2 is not admissible",
    ],
    answer: 1,
    explanation: "Each misplaced tile contributes at least 1 to its Manhattan distance, so h2(n) >= h1(n) for every n, and both are admissible. h2 therefore dominates h1 and A* with h2 expands fewer nodes.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "What is h1 (misplaced tiles, excluding the blank) for the 8-puzzle start state where every numbered tile is in a wrong position?",
    options: [
      "0",
      "8",
      "9",
      "18",
    ],
    answer: 1,
    explanation: "h1 counts misplaced numbered tiles (not the blank). When all 8 numbered tiles are wrong, h1 = 8.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "If h1 and h2 are both admissible, what is the most useful way to combine them?",
    options: [
      "h(n) = min(h1(n), h2(n))",
      "h(n) = (h1(n) + h2(n)) / 2",
      "h(n) = max(h1(n), h2(n))",
      "h(n) = h1(n) * h2(n)",
    ],
    answer: 2,
    explanation: "Taking the max of admissible heuristics yields a heuristic that is still admissible and dominates each component, so A* expands at most as many nodes as with either alone.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Under which condition is A* GUARANTEED optimal when using graph search (closed list)?",
    options: [
      "The heuristic is admissible only",
      "The heuristic is consistent",
      "The heuristic equals h*",
      "The branching factor is finite",
    ],
    answer: 1,
    explanation: "For graph search with repeated-state checking, A* is optimal iff the heuristic is consistent. Admissibility alone is enough only for tree search.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Weighted A* uses f(n) = g(n) + alpha * h(n). With alpha = 3 and admissible h, the returned cost C satisfies:",
    options: [
      "C <= C* (better than optimal)",
      "C = C* (always optimal)",
      "C* <= C <= 3 * C*",
      "C is unbounded",
    ],
    answer: 2,
    explanation: "Weighted A* trades optimality for speed: the returned cost is no better than C* but bounded above by alpha * C*. With alpha = 3, C <= 3 * C*.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "In Weighted A*, what does setting alpha = 0 reduce the algorithm to?",
    options: [
      "Uniform-Cost Search (UCS)",
      "A*",
      "Greedy best-first",
      "Depth-first search",
    ],
    answer: 0,
    explanation: "When alpha = 0, f(n) = g(n) + 0 = g(n), which is exactly UCS. (alpha = 1 is A*, alpha = infinity is Greedy.)",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Why does Greedy best-first sometimes fail to find the optimal path?",
    options: [
      "It always returns the deepest path",
      "It ignores the path cost g(n) already accumulated",
      "It uses an inadmissible heuristic by definition",
      "It ignores h(n) entirely",
    ],
    answer: 1,
    explanation: "Greedy uses only h(n), so it can commit to a neighbor that looks closest to the goal even though reaching it (or continuing from it) costs more overall. A* fixes this by adding g(n).",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Which informed-search variant is designed primarily to reduce A*'s memory footprint to roughly linear in path depth?",
    options: [
      "Weighted A*",
      "IDA* (Iterative-Deepening A*)",
      "Greedy best-first",
      "UCS",
    ],
    answer: 1,
    explanation: "IDA* repeatedly runs depth-limited A* with an increasing f-cost cutoff. It only needs O(bd) space at the cost of revisiting nodes.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "What characterizes SMA* (Simplified Memory-Bounded A*)?",
    options: [
      "It uses no heuristic",
      "It is identical to Greedy best-first",
      "It guarantees linear time",
      "It keeps a fixed-size frontier and drops the worst nodes when full",
    ],
    answer: 3,
    explanation: "SMA* runs A* but bounds the frontier; when memory is exhausted it forgets the highest-f (worst) nodes, backing up their values into ancestors so the search can continue.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Why is the straight-line distance heuristic admissible for route finding on a road map?",
    options: [
      "Because roads are always straight",
      "Because no real path can be shorter than a straight line",
      "Because it always equals h*",
      "Because it is consistent by definition",
    ],
    answer: 1,
    explanation: "Euclidean distance is the geometric lower bound on travel distance — any actual road path is at least as long. So h_SLD <= h* everywhere, satisfying admissibility.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "A heuristic on a graph gives h(A)=10, h(B)=2, with edge A->B of cost 3. Is consistency violated on this edge?",
    options: [
      "No, the values are admissible",
      "No, because 10 <= 2 + something",
      "Yes, because h(A) - h(B) = 8 > 3 = c(A,B)",
      "Cannot tell without h*",
    ],
    answer: 2,
    explanation: "Consistency requires h(A) <= c(A,B) + h(B), i.e. 10 <= 3 + 2 = 5, which fails. Equivalently h(A) - h(B) = 8 exceeds the edge cost 3.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "A* is run on a small graph: start S with h=4; successors A (g=1, h=4) and B (g=2, h=1). Which node does A* expand next, after S?",
    options: [
      "A, because f(A)=5",
      "B, because f(B)=3",
      "Either, they tie",
      "Neither — A* terminates",
    ],
    answer: 1,
    explanation: "f(A) = 1 + 4 = 5 and f(B) = 2 + 1 = 3. A* expands the lowest-f node next, so B is expanded.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "Which heuristic is obtained from the 8-puzzle relaxation that lets a tile move to any adjacent square ignoring blocking?",
    options: [
      "Misplaced tiles (h1)",
      "Manhattan distance (h2)",
      "Zero heuristic",
      "Euclidean distance",
    ],
    answer: 1,
    explanation: "Allowing each tile to slide freely to any adjacent square ignoring other tiles gives a shortest distance equal to the Manhattan distance of each tile to its goal — that is h2.",
  },
  {
    week: 4,
    topic: "Informed Search",
    question: "On the Lab 3 graph (start A, goals K and L), Greedy best-first returns A -> D -> H -> K with cost 11, while A* returns A -> D -> H -> L with cost 10. What does this illustrate?",
    options: [
      "Greedy is optimal whenever h is admissible",
      "A* and Greedy always return the same path",
      "A* requires an inadmissible heuristic to beat Greedy",
      "Greedy can be misled by low h while A* with g+h finds the optimum",
    ],
    answer: 3,
    explanation: "Greedy followed the locally cheapest-looking h-values down to K, paying a high final edge cost. A* accounted for path cost g(n) and discovered the truly cheaper route ending at L.",
  },
];

export default l04;
