import type { Question } from "../../types";

const l02: Question[] = [
  {
    week: 2,
    topic: "Agents",
    question: "In AIMA's PEAS description of an automated taxi driver, which item belongs to the Environment (E) component?",
    options: [
      "Steering, accelerator, brake, signal, horn, display",
      "Roads, other traffic, pedestrians, customers",
      "Cameras, sonar, speedometer, GPS, odometer, engine sensors",
      "Safe, fast, legal, comfortable trip; maximize profits",
    ],
    answer: 1,
    explanation: "AIMA lists the taxi's environment as roads, other traffic, pedestrians, and customers. The other options are actuators, sensors, and the performance measure respectively.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "AIMA defines a rational agent as one that:",
    options: [
      "Always selects the action that achieves the best actual outcome in the world",
      "For each percept sequence, selects an action expected to maximize its performance measure given the evidence in its percept sequence and built-in knowledge",
      "Always knows the true state of the world and acts to maximize utility",
      "Learns from experience to approximate an optimal policy",
    ],
    answer: 1,
    explanation: "Rationality is defined relative to expected (not actual) performance, the percept sequence to date, and prior built-in knowledge — not omniscience or learning ability.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which AIMA task environment is best classified as fully observable, multi-agent, deterministic, sequential, semi-dynamic, and discrete?",
    options: [
      "Taxi driving",
      "Medical diagnosis",
      "Chess with a clock",
      "Image analysis",
    ],
    answer: 2,
    explanation: "AIMA's table classifies chess with a clock as fully observable, multi-agent, deterministic, sequential, semi-dynamic (clock affects score), and discrete.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which component of a learning agent is responsible for suggesting exploratory actions that lead to new and informative experiences?",
    options: [
      "Performance element",
      "Critic",
      "Learning element",
      "Problem generator",
    ],
    answer: 3,
    explanation: "The problem generator proposes exploratory actions that may be suboptimal in the short term but expose the agent to new experiences that improve long-term performance.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "A simple reflex agent is generally INSUFFICIENT when the environment is:",
    options: [
      "Episodic and deterministic",
      "Partially observable, so current percept alone does not reveal needed state",
      "Fully observable and discrete",
      "Single-agent and static",
    ],
    answer: 1,
    explanation: "Simple reflex agents condition only on the current percept. When the environment is partially observable, they cannot infer hidden state and may loop or fail; a model-based agent is required.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "According to AIMA, what is the relationship between an agent function and an agent program?",
    options: [
      "The agent function is an abstract mapping from percept sequences to actions; the agent program is a concrete implementation running on an architecture",
      "They are interchangeable terms for the same code module",
      "The agent function handles perception; the agent program handles action execution",
      "The agent program defines the goal; the agent function is the search procedure",
    ],
    answer: 0,
    explanation: "AIMA distinguishes the (possibly infinite) abstract mapping f: P* -> A from the finite implementation. agent = architecture + program, and the program realizes the function.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "A utility-based agent extends a goal-based agent primarily because:",
    options: [
      "It can handle partially observable environments via internal state",
      "It can replace search with table lookup",
      "It assigns a real-valued degree of desirability to states, allowing rational trade-offs among conflicting goals and uncertain outcomes",
      "It eliminates the need for a model of how the world evolves",
    ],
    answer: 2,
    explanation: "Goals are binary (achieved or not). A utility function maps states to real numbers so the agent can compare partial successes, balance conflicting goals, and maximize expected utility under uncertainty.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "For AIMA's part-picking robot, which item correctly fills the Sensors (S) slot of PEAS?",
    options: [
      "Camera, joint angle sensors",
      "Jointed arm and hand",
      "Conveyor belt with parts; bins",
      "Percentage of parts in correct bins",
    ],
    answer: 0,
    explanation: "AIMA lists camera and joint angle sensors as the robot's sensors. The arm/hand are actuators, the conveyor and bins are environment, and percentage correct is the performance measure.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "In AIMA's learning-agent architecture, what role does the critic play?",
    options: [
      "It selects external actions based on the current percept",
      "It compares the agent's behavior against a fixed external performance standard and tells the learning element how well the agent is doing",
      "It modifies the performance element directly using gradient descent",
      "It proposes exploratory actions to gather new evidence",
    ],
    answer: 1,
    explanation: "The critic uses a fixed external performance standard to judge outcomes and feeds this evaluation to the learning element, which then improves the performance element.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "An interactive English tutor must adapt as new students enroll and curricula change. Along which environment dimensions does AIMA classify this task?",
    options: [
      "Fully observable, deterministic, episodic, static, discrete, single-agent",
      "Fully observable, stochastic, episodic, static, continuous, single-agent",
      "Partially observable, stochastic, sequential, dynamic, discrete, multi-agent",
      "Partially observable, deterministic, sequential, semi-dynamic, continuous, multi-agent",
    ],
    answer: 2,
    explanation: "AIMA classifies the interactive English tutor as partially observable (student knowledge is hidden), stochastic, sequential (lessons build on each other), dynamic, discrete, and multi-agent.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "An autonomous Mars rover exploring an unmapped surface is best classified as:",
    options: [
      "Fully observable, deterministic, episodic, static, discrete, single-agent",
      "Partially observable, stochastic, sequential, dynamic, continuous, single-agent",
      "Fully observable, stochastic, sequential, static, discrete, multi-agent",
      "Partially observable, deterministic, episodic, semi-dynamic, continuous, single-agent",
    ],
    answer: 1,
    explanation: "Terrain is hidden (partial), wheel slip is stochastic, decisions affect future state (sequential), the environment changes, sensors are continuous, and the rover operates alone.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which environment dimension best distinguishes online poker from chess?",
    options: [
      "Single-agent vs. multi-agent",
      "Discrete vs. continuous",
      "Observability and stochasticity (poker is partially observable and stochastic)",
      "Static vs. semi-dynamic",
    ],
    answer: 2,
    explanation: "Both are sequential, discrete, and multi-agent. Poker differs because opponents' cards are hidden and the deck shuffle is random; chess is fully observable and deterministic.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "For a part-picking robot on an assembly line, which PEAS entry correctly lists the Performance measure?",
    options: [
      "Conveyor belt, parts, bins",
      "Percentage of parts in correct bins",
      "Jointed arm and hand",
      "Camera, joint angle sensors",
    ],
    answer: 1,
    explanation: "Performance is what we want to maximize: the percentage of parts placed in their correct bins. The others are environment, actuators, and sensors.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "For an interactive English tutor, which item is the Environment (E) in PEAS?",
    options: [
      "Maximize student's score on a test",
      "Display exercises, suggestions, corrections",
      "Set of students, the testing agency",
      "Keyboard input",
    ],
    answer: 2,
    explanation: "The environment is the set of students being tutored together with the testing agency. The others are performance, actuators, and sensors.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "For a mathematical theorem-proving agent, which environment dimension is MOST atypical compared to a taxi?",
    options: [
      "It is multi-agent and competitive",
      "It is partially observable",
      "It is continuous",
      "It is static (the axioms do not change while the agent thinks)",
    ],
    answer: 3,
    explanation: "A theorem prover operates on a fixed set of axioms that never change during deliberation, making it static, discrete, and single-agent — the opposite of taxi driving.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "An internet shopping agent that browses sites, compares prices, and places orders is best classified as:",
    options: [
      "Fully observable, deterministic, episodic, static",
      "Partially observable, stochastic, sequential, dynamic",
      "Fully observable, stochastic, episodic, semi-dynamic",
      "Partially observable, deterministic, episodic, static",
    ],
    answer: 1,
    explanation: "Prices and stock are hidden until queried (partial), availability changes randomly (stochastic), purchases affect future state (sequential), and sites update during deliberation (dynamic).",
  },
  {
    week: 2,
    topic: "Agents",
    question: "What is the key distinction between an agent FUNCTION and an agent PROGRAM?",
    options: [
      "The function runs on hardware; the program is abstract mathematics",
      "The function is an abstract mapping from percept sequences to actions; the program is its concrete implementation",
      "The function handles sensing; the program handles acting",
      "They are synonyms — both refer to the same code",
    ],
    answer: 1,
    explanation: "The agent function f: P* -> A is the abstract input/output specification (possibly infinite). The agent program is the finite code running on the architecture that realizes it.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which statement about the learning agent's four components is CORRECT?",
    options: [
      "The critic chooses external actions based on the current percept",
      "The problem generator computes the agent's utility function",
      "The learning element modifies the performance element using feedback from the critic",
      "The performance element provides the fixed external standard used to judge behavior",
    ],
    answer: 2,
    explanation: "The critic evaluates outcomes against an external standard, the learning element uses that feedback to improve the performance element (which selects actions), and the problem generator suggests exploratory actions.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "How would you classify medical diagnosis as a task environment?",
    options: [
      "Fully observable, deterministic, episodic, static, discrete, single-agent",
      "Partially observable, stochastic, sequential, dynamic, continuous, single-agent",
      "Fully observable, stochastic, sequential, semi-dynamic, discrete, multi-agent",
      "Partially observable, deterministic, episodic, static, continuous, multi-agent",
    ],
    answer: 1,
    explanation: "Medical diagnosis is partially observable (hidden symptoms/conditions), stochastic (uncertain disease progression), sequential (treatments affect future state), dynamic (patient changes during deliberation), continuous (vital signs), and single-agent.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which of the following best describes the environment of an image-classification system on a factory assembly line?",
    options: [
      "Sequential and dynamic",
      "Episodic and static (or semi-static)",
      "Stochastic and multi-agent",
      "Partially observable and continuous",
    ],
    answer: 1,
    explanation: "Each image is classified independently of past or future images, making the task episodic. The environment is also static or semi-static since the world does not change while the system thinks.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "For an automated taxi agent, which of the following best represents the Performance measure (the 'P' in PEAS)?",
    options: [
      "Steering, accelerator, brake, signal, horn, display",
      "Roads, other traffic, pedestrians, customers",
      "Cameras, speedometer, GPS, odometer, engine sensors",
      "Safe, fast, legal, comfortable, maximize profits",
    ],
    answer: 3,
    explanation: "Performance measure describes what we want the agent to achieve — for a taxi this is being safe, fast, legal, comfortable, and profitable. The other options describe Actuators, Environment, and Sensors respectively.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which of the following is the correct Sensors (S) entry in the PEAS description of a spam filter?",
    options: [
      "Incoming messages and user account info",
      "Mark-as-spam, delete, move folder",
      "Minimize false positives and false negatives",
      "The user's email account and email server",
    ],
    answer: 0,
    explanation: "A spam filter senses the world via incoming messages and user account info. Mark/delete/move are actuators, minimizing FP/FN is the performance measure, and the email account/server is the environment.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "A crossword puzzle is best classified along the static/dynamic dimension as:",
    options: [
      "Dynamic — the puzzle keeps changing as you solve it",
      "Semi-dynamic — the puzzle is fixed but your score changes with time",
      "Static — the puzzle does not change while you think",
      "Stochastic — the puzzle changes randomly",
    ],
    answer: 2,
    explanation: "Crossword puzzles do not change while the agent deliberates, so they are static. Semi-dynamic would require the environment to be unchanged but performance to depend on time (like timed chess).",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which agent type is the simplest in the hierarchy and requires a complete lookup of every possible percept sequence?",
    options: [
      "Simple reflex agent",
      "Table-driven agent",
      "Model-based reflex agent",
      "Goal-based agent",
    ],
    answer: 1,
    explanation: "The table-driven agent indexes a giant lookup table by the full percept sequence. It is conceptually trivial but suffers from combinatorial explosion of table size.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "A simple reflex agent will most likely FAIL in which kind of environment?",
    options: [
      "Fully observable and deterministic",
      "Discrete and single-agent",
      "Partially observable",
      "Static and episodic",
    ],
    answer: 2,
    explanation: "Simple reflex agents act only on the current percept, so they cannot infer hidden state. In partially observable environments they may loop or fail; a model-based agent is needed.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which component of a learning agent proposes exploratory actions in order to discover better strategies?",
    options: [
      "Performance element",
      "Critic",
      "Problem generator",
      "Learning element",
    ],
    answer: 2,
    explanation: "The problem generator suggests new, exploratory actions that may not be immediately optimal but expose the agent to experiences that improve future behavior.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "In a learning agent, which component evaluates how the agent is doing against a fixed external performance standard?",
    options: [
      "Critic",
      "Performance element",
      "Problem generator",
      "Learning element",
    ],
    answer: 0,
    explanation: "The critic compares observed outcomes to an external performance standard and provides feedback to the learning element, which updates the performance element.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Scrabble is best classified along the deterministic/stochastic dimension as:",
    options: [
      "Deterministic — the rules are fixed",
      "Stochastic — tile draws introduce randomness",
      "Semi-deterministic — only the opponent is random",
      "Strategic — no real randomness is involved",
    ],
    answer: 1,
    explanation: "Although the rules are fixed, the random tile draws make outcomes uncertain from the agent's viewpoint, so Scrabble is classified as stochastic.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which agent type is best suited when goals conflict and the designer must express trade-offs (e.g., faster vs. safer driving)?",
    options: [
      "Simple reflex agent",
      "Model-based reflex agent",
      "Goal-based agent",
      "Utility-based agent",
    ],
    answer: 3,
    explanation: "A utility-based agent maps states to a real number capturing how desirable they are, so it can compare and trade off conflicting goals by maximizing expected utility.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Taxi driving on a busy road is best described along the agent dimension as:",
    options: [
      "Single-agent",
      "Multi-agent and competitive only",
      "Multi-agent and cooperative only",
      "Multi-agent with both cooperative and competitive aspects",
    ],
    answer: 3,
    explanation: "Other drivers exist (multi-agent). Avoiding collisions is cooperative, but competing for parking, lanes, or customers is competitive — so taxi driving has both aspects.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "For a vacuum-cleaner agent, which list correctly describes the Actuators (A) in PEAS?",
    options: [
      "Dirt cleaned, time taken, electricity used, noise",
      "Squares A, B, dirt",
      "Left, Right, Suck, NoOp",
      "Location sensor, dirt sensor",
    ],
    answer: 2,
    explanation: "The vacuum's actuators are the movements and cleaning actions Left, Right, Suck, and NoOp. The other options describe the performance measure, the environment, and the sensors.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "A model-based reflex agent's internal model must encode which TWO things?",
    options: [
      "The agent's goal and its utility function",
      "The percept sequence and the action history",
      "How the environment evolves independently, and how the agent's actions affect the environment",
      "The performance measure and a lookup table",
    ],
    answer: 2,
    explanation: "A model-based reflex agent needs to know how the world changes by itself (transition dynamics) and how its own actions change the world, so it can update its internal state.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Poker is best classified along the observable/stochastic/agents dimensions as:",
    options: [
      "Partially observable, stochastic, multi-agent",
      "Fully observable, deterministic, single-agent",
      "Fully observable, stochastic, single-agent",
      "Partially observable, deterministic, multi-agent",
    ],
    answer: 0,
    explanation: "In poker the opponents' cards are hidden (partially observable), the deck is shuffled (stochastic), and multiple players compete (multi-agent).",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Chess with a clock is best classified along the static/dynamic dimension as:",
    options: [
      "Static — neither the board nor anything else changes while you think",
      "Dynamic — the board changes while you deliberate",
      "Semi-dynamic — the board is fixed during deliberation but the clock affects performance",
      "Stochastic — time introduces randomness",
    ],
    answer: 2,
    explanation: "The chessboard does not change while you think, but the running clock means your score (or whether you lose on time) does change — this is the definition of semi-dynamic.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which agent type uses explicit goals plus search/planning to choose actions based on their future consequences, but does NOT yet handle trade-offs between competing goals?",
    options: [
      "Goal-based agent",
      "Utility-based agent",
      "Model-based reflex agent",
      "Learning agent",
    ],
    answer: 0,
    explanation: "A goal-based agent reasons about future states to find action sequences that reach a goal, but treats goal-vs-not-goal as binary. Trade-offs between competing goals require a utility-based agent.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Which of these tasks is best described as EPISODIC rather than sequential?",
    options: [
      "Playing a game of chess",
      "Driving a taxi",
      "Classifying defective parts on an assembly line",
      "Solving a crossword puzzle",
    ],
    answer: 2,
    explanation: "Classifying each part is independent of other parts — the decision on one image does not affect future classifications, which is the textbook definition of episodic.",
  },
  {
    week: 2,
    topic: "Agents",
    question: "Taxi driving is best classified along the discrete/continuous dimension as:",
    options: [
      "Discrete — actions like Left/Right/Brake are finite",
      "Discrete — time is measured in distinct ticks",
      "Continuous — speed, steering angle, and sensor readings take continuous values",
      "Semi-discrete — only the GPS coordinates are continuous",
    ],
    answer: 2,
    explanation: "Although you can label actions abstractly, real taxi driving involves continuous-valued quantities like speed, steering angle, acceleration, and sensor readings, so it is a continuous environment.",
  },
];

export default l02;
