import type { Question } from "../../types";

const l05: Question[] = [
  {
    week: 5,
    topic: "Local Search",
    question: "In the state-space landscape used to visualize local search, what is a 'shoulder'?",
    options: [
      "A flat region with no uphill exit, where the algorithm gets permanently stuck",
      "A flat region (plateau) with an uphill edge, so the search can eventually escape and continue ascending",
      "A sequence of local maxima where every single step looks downhill",
      "The highest point in the entire state space",
    ],
    answer: 1,
    explanation: "AIMA distinguishes a flat local maximum (no uphill exit) from a shoulder, which is a plateau that has an uphill slope at one edge. A search on a shoulder can eventually walk off and resume climbing.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Why does steepest-ascent hill climbing fail to solve the 8-queens problem from most random starts?",
    options: [
      "The branching factor is too high to evaluate any successor",
      "The state space is infinite, so no successor can be enumerated",
      "It frequently reaches local maxima where every single-queen move keeps the number of conflicts the same or higher, e.g., configurations with h = 1",
      "The heuristic h (number of attacking pairs) is inadmissible",
    ],
    answer: 2,
    explanation: "8-queens has many local minima with a small non-zero number of attacking pairs (often h = 1). From a random start, steepest-ascent HC gets stuck on such configurations roughly 86% of the time.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "In simulated annealing, a candidate move has ΔE = -3 and the current temperature is T = 6. What is P(accept)?",
    options: [
      "exp(-3) ≈ 0.0498",
      "exp(-0.5) ≈ 0.6065",
      "exp(0.5) ≈ 1.6487",
      "exp(-2) ≈ 0.1353",
    ],
    answer: 1,
    explanation: "P(accept) = exp(ΔE/T) = exp(-3/6) = exp(-0.5) ≈ 0.6065. The ratio |ΔE|/T is small, so the worsening move is accepted with relatively high probability.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Simulated annealing considers a worsening move with ΔE = -8 at temperature T = 2. What is P(accept)?",
    options: [
      "exp(-4) ≈ 0.0183",
      "exp(-2) ≈ 0.1353",
      "exp(-0.25) ≈ 0.7788",
      "1 (always accepted)",
    ],
    answer: 0,
    explanation: "P = exp(ΔE/T) = exp(-8/2) = exp(-4) ≈ 0.0183. The large |ΔE| and low T make this large worsening move very unlikely to be accepted.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Two simulated annealing candidates are evaluated: Move A has ΔE = -2, T = 4; Move B has ΔE = -2, T = 1. Which is more likely to be accepted?",
    options: [
      "Move A: exp(-0.5) ≈ 0.6065 vs Move B: exp(-2) ≈ 0.1353 — A more likely",
      "Move B because lower T concentrates probability mass",
      "Both equal because they share the same ΔE",
      "Neither — SA never accepts worsening moves",
    ],
    answer: 0,
    explanation: "P_A = exp(-2/4) = exp(-0.5) ≈ 0.6065; P_B = exp(-2/1) = exp(-2) ≈ 0.1353. Higher T means worsening moves of equal magnitude are more readily accepted, supporting exploration early in the schedule.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Why is random-restart hill climbing described in AIMA as 'surprisingly effective'?",
    options: [
      "Each restart deterministically finds the global optimum",
      "It uses gradient information unavailable to other variants",
      "Even when each individual hill-climb has a small success probability p, the probability of solving the problem after n restarts is 1-(1-p)^n, which rapidly approaches 1",
      "It always halts in O(log n) steps",
    ],
    answer: 2,
    explanation: "Because each restart is independent, even a low per-run success probability becomes near-certain after enough restarts. The expected number of restarts is 1/p, making random-restart hill climbing complete with probability approaching 1.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "How does local beam search with k states fundamentally differ from running k independent random-restart hill climbers?",
    options: [
      "Beam search uses a temperature schedule like simulated annealing",
      "Beam search shares information: it pools the successors of all k states and keeps the k best overall, so promising regions can attract multiple states",
      "Beam search runs each of the k states completely sequentially",
      "Beam search never uses an objective/fitness function",
    ],
    answer: 1,
    explanation: "In local beam search the k chosen successors can all descend from one fruitful parent, because selection is over the pooled set of k*N successors. Independent hill climbers, by contrast, never share information across runs.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which sequence correctly orders the basic steps of a generational genetic algorithm (per AIMA)?",
    options: [
      "Mutation -> Crossover -> Selection -> Evaluation",
      "Selection of parents (by fitness) -> Crossover -> Mutation -> Evaluation of offspring",
      "Crossover -> Selection -> Mutation -> Evaluation",
      "Evaluation -> Mutation -> Selection -> Crossover",
    ],
    answer: 1,
    explanation: "Each generation: (1) score individuals with the fitness function, (2) select parents (e.g., roulette/tournament), (3) recombine via crossover, (4) apply mutation to offspring, then evaluate the new generation.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which statement best describes a key difference between simulated annealing (SA) and a genetic algorithm (GA)?",
    options: [
      "SA maintains a population of candidate solutions; GA maintains only one current state",
      "SA uses crossover between two parents; GA uses a temperature schedule",
      "SA explores from a single state guided by a temperature schedule, while a GA maintains a population and combines solutions via crossover and mutation",
      "SA is guaranteed optimal; GA is guaranteed complete",
    ],
    answer: 2,
    explanation: "SA is a single-state stochastic method whose exploration is controlled by temperature. GA is a population-based method whose key operator is crossover (sexual recombination), with mutation providing diversity.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "For continuous optimization problems, which local search technique uses ∇f(x) to update the current state via x <- x + α∇f(x)?",
    options: [
      "Simulated annealing",
      "Genetic algorithm",
      "Gradient ascent (a continuous form of hill climbing)",
      "Local beam search",
    ],
    answer: 2,
    explanation: "Gradient ascent (and its descent counterpart) is the continuous analogue of hill climbing: it follows the gradient of the objective with step size α. AIMA presents this as the standard continuous local-search method, with Newton-Raphson as a second-order refinement.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "In simulated annealing, a candidate move has ΔE = -2 and the current temperature is T = 4. What is the probability of accepting this move?",
    options: [
      "exp(-2) ≈ 0.135",
      "exp(-0.5) ≈ 0.607",
      "exp(0.5) ≈ 1.649",
      "1 (always accepted)",
    ],
    answer: 1,
    explanation: "P(accept) = exp(ΔE/T) = exp(-2/4) = exp(-0.5) ≈ 0.607. ΔE is negative, so the move is downhill and accepted only probabilistically.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Simulated annealing is considering a worsening move with ΔE = -3 at temperature T = 1. What is P(accept)?",
    options: [
      "exp(-3) ≈ 0.0498",
      "exp(3) ≈ 20.09",
      "exp(-1/3) ≈ 0.717",
      "0 (never accepted)",
    ],
    answer: 0,
    explanation: "P = exp(ΔE/T) = exp(-3/1) = exp(-3) ≈ 0.0498. At low T, downhill moves of this magnitude are only rarely accepted.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Two SA candidate moves are considered: Move A has ΔE = -1, T = 2; Move B has ΔE = -6, T = 3. Which move is MORE likely to be accepted, and what are the two probabilities?",
    options: [
      "Move A: exp(-0.5) ≈ 0.607; Move B: exp(-2) ≈ 0.135 — A more likely",
      "Move B is more likely because it has a larger |ΔE|",
      "Both equal because both ratios reduce to the same value",
      "Move A: exp(-2) ≈ 0.135; Move B: exp(-0.5) ≈ 0.607 — B more likely",
    ],
    answer: 0,
    explanation: "Move A: exp(-1/2) = exp(-0.5) ≈ 0.607. Move B: exp(-6/3) = exp(-2) ≈ 0.135. The smaller |ΔE/T| ratio gives the higher acceptance probability, so Move A is more likely.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Single-point crossover at position 3 (cut after bit 3) is applied to parents P1 = 11010 and P2 = 00111. What are the two children?",
    options: [
      "11011 and 00110",
      "11000 and 00111",
      "00010 and 11111",
      "11111 and 00010",
    ],
    answer: 0,
    explanation: "Cut after bit 3 splits each parent into [first 3 | last 2]: P1 = 110|10, P2 = 001|11. Child1 = 110+11 = 11011, Child2 = 001+10 = 00110.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Apply single-point crossover at position 2 (cut after bit 2) to P1 = 10110 and P2 = 01001. What are the resulting children?",
    options: [
      "10001 and 01110",
      "10110 and 01001",
      "11001 and 00110",
      "10101 and 01010",
    ],
    answer: 0,
    explanation: "Cut after bit 2: P1 = 10|110, P2 = 01|001. Child1 = 10+001 = 10001, Child2 = 01+110 = 01110.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Hill climbing on 8-queens reaches a configuration with h = 1 (one pair of queens still attacks). Every single-queen move either keeps h = 1 or increases it. This situation is best described as a:",
    options: [
      "Global maximum",
      "Local maximum / local optimum trap",
      "Shoulder",
      "Random restart point",
    ],
    answer: 1,
    explanation: "A local maximum (in terms of fitness; local minimum of conflicts) is a state better than every neighbor but not globally optimal. Steepest-ascent HC halts here. This is exactly why plain HC solves only ~14% of random 8-queens starts.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Standard local beam search with k = 4 generates 4 successors from each of its 4 current states. Out of the resulting pool, what does the algorithm do next?",
    options: [
      "Run hill climbing independently on each of the 16 successors",
      "Keep the 4 best successors of each state separately (16 states total)",
      "Pool all 16 successors and keep the overall 4 best to form the next state set",
      "Apply crossover between pairs of successors",
    ],
    answer: 2,
    explanation: "Local beam search pools the successors of all k states and selects the top k overall. The chosen k may all descend from a single fruitful parent — that is the key difference from k independent hill climbers.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "A hill climber reaches a plateau where every neighbor has exactly the same value as the current state. Which strategy is LEAST likely to escape this plateau?",
    options: [
      "Allow a bounded number of sideways moves to neighbors with equal value",
      "Random-restart from a new state",
      "Switch to simulated annealing so worse/equal moves can be accepted",
      "Strict steepest-ascent HC that halts when no neighbor strictly improves",
    ],
    answer: 3,
    explanation: "Strict steepest-ascent HC terminates as soon as no neighbor strictly improves, so a flat plateau halts it immediately. Allowing sideways moves, random restarts, and SA all give a chance to walk off the plateau.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which property best characterizes problems suitable for local search?",
    options: [
      "The path from the start state to the goal must be traceable",
      "Only the final state matters; the path is irrelevant",
      "The state space must be finite and small",
      "The heuristic must be admissible",
    ],
    answer: 1,
    explanation: "Local search is designed for optimization problems where only the final configuration matters (e.g., n-queens, TSP, scheduling). It does not track paths, frontiers, or path costs.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "What is the memory complexity of standard hill climbing?",
    options: [
      "O(1)",
      "O(k) where k is the beam width",
      "O(n log n)",
      "O(b^d)",
    ],
    answer: 0,
    explanation: "Hill climbing keeps only the current state in memory, so its space complexity is O(1). Beam search uses O(k) and GA uses O(population size).",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "A 'ridge' in the state-space landscape is best described as:",
    options: [
      "A flat region where all neighbors have the same value",
      "The single highest peak in the landscape",
      "A sequence of local maxima where each single step appears downhill, even though the overall direction is upward",
      "A randomly generated starting state",
    ],
    answer: 2,
    explanation: "A ridge is a sequence of local maxima oriented such that each individual move appears to go downhill, even though following the ridge would go up overall. Hill climbing struggles with ridges.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which hill climbing variant is preferred when a state has very many successors?",
    options: [
      "Steepest ascent",
      "Random-restart hill climbing",
      "Stochastic hill climbing",
      "First-choice hill climbing",
    ],
    answer: 3,
    explanation: "First-choice hill climbing generates successors at random and accepts the first one that improves on the current state. This avoids the expense of evaluating all neighbors when the branching factor is large.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "In simulated annealing, given a worse move with ΔE = -4 and current temperature T = 2, what is the probability of accepting that move?",
    options: [
      "exp(2)",
      "exp(-4)",
      "exp(4/2) = exp(2)",
      "exp(-2)",
    ],
    answer: 3,
    explanation: "P = exp(ΔE/T) = exp(-4/2) = exp(-2). Since ΔE is negative for worse moves, the exponential is less than 1, giving a small but non-zero chance of acceptance.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "When the temperature T in simulated annealing is very high, the algorithm behaves like:",
    options: [
      "Greedy hill climbing",
      "Breadth-first search",
      "A random walk that accepts almost any move",
      "A genetic algorithm",
    ],
    answer: 2,
    explanation: "At very high T, exp(ΔE/T) approaches 1 even for large negative ΔE, so almost every move is accepted. This is the exploration phase, behaving like a random walk.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which selection method picks k random individuals and keeps the fittest of them?",
    options: [
      "Tournament selection",
      "Roulette-wheel selection",
      "Rank-based selection",
      "Elitism",
    ],
    answer: 0,
    explanation: "Tournament selection samples k individuals at random and selects the fittest among them. The parameter k controls selection pressure: larger k means stronger pressure toward elite individuals.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "In single-point crossover, given parents P1 = 1010000000 and P2 = 1001011111 with cut after bit 3, what is the child?",
    options: [
      "1011011111",
      "1010011111",
      "1001000000",
      "1000011111",
    ],
    answer: 0,
    explanation: "Single-point crossover takes the first 3 bits of P1 ('101') and the remaining 7 bits of P2 ('1011111'). Concatenation gives 1011011111.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Why is mutation considered essential in a genetic algorithm?",
    options: [
      "It increases convergence speed by exploiting good solutions",
      "It combines genetic material from two parents",
      "It guarantees the algorithm reaches the global optimum",
      "It introduces alleles that may be missing from the initial population, maintaining diversity",
    ],
    answer: 3,
    explanation: "Without mutation, alleles absent from the initial population can never appear via crossover alone. Mutation is the only mechanism that introduces new genetic material, preventing stagnation.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Local beam search with k states differs from running k independent hill climbers in that:",
    options: [
      "It uses a temperature schedule to accept worse states",
      "The k best states across all successors are selected collectively, so information is shared",
      "It uses crossover between the k states",
      "It maintains no memory of previous states",
    ],
    answer: 1,
    explanation: "In beam search, all successors of all k states are pooled, and the top k overall are kept. The k 'best' could all come from a single state's successors, unlike independent hill climbers.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Is random-restart hill climbing complete?",
    options: [
      "No, it can never escape local optima",
      "Yes, with probability approaching 1 as the number of restarts grows",
      "Yes, deterministically on every run",
      "Only when combined with simulated annealing",
    ],
    answer: 1,
    explanation: "Each restart is an independent draw from the basin-of-attraction distribution. As restarts go to infinity, the probability that at least one start drains to the global optimum approaches 1.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which of the following is NOT a hill climbing variant?",
    options: [
      "Steepest-ascent",
      "First-choice",
      "Stochastic",
      "Roulette-wheel",
    ],
    answer: 3,
    explanation: "Roulette-wheel is a fitness-proportional selection method used in genetic algorithms, not a hill climbing variant. The hill climbing variants are steepest-ascent, first-choice, stochastic, and random-restart.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "What effect does setting the mutation rate too high have on a genetic algorithm?",
    options: [
      "The GA converges prematurely to a local optimum",
      "The GA behaves like a random walk and loses the ability to exploit good solutions",
      "The GA becomes deterministic",
      "The GA always finds the global optimum faster",
    ],
    answer: 1,
    explanation: "Excessive mutation destroys good building blocks faster than selection and crossover can exploit them. The search degenerates into a random walk with no convergence.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "In roulette-wheel selection with fitnesses [1,2,3,1,3,5,1,2] (sum = 18), which chromosome is picked when the random number R = 7?",
    options: [
      "Chromosome 3",
      "Chromosome 4",
      "Chromosome 5",
      "Chromosome 6",
    ],
    answer: 1,
    explanation: "Walking through cumulative sums: 1, 3, 6, 7, ... The first cumulative sum that reaches or exceeds 7 occurs at chromosome 4, so chromosome 4 is selected.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "What is elitism in a genetic algorithm?",
    options: [
      "Always carrying the top-N best individuals through to the next generation unchanged",
      "Selecting only the worst individuals for reproduction",
      "Discarding the best individuals each generation to maintain diversity",
      "Using uniform crossover instead of single-point",
    ],
    answer: 0,
    explanation: "Elitism preserves the best K individuals from one generation to the next without modification. This prevents losing the best-so-far solution due to unlucky crossover or mutation.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which statement about genetic algorithms is TRUE?",
    options: [
      "GAs are both complete and optimal",
      "GAs are complete but not optimal",
      "GAs are optimal but not complete",
      "GAs are neither complete nor optimal — only stochastic heuristics",
    ],
    answer: 3,
    explanation: "Genetic algorithms provide no guarantee of finding a solution (not complete) or finding the best solution (not optimal). They are stochastic search heuristics with no termination guarantees.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "When temperature T approaches 0 in simulated annealing, the algorithm:",
    options: [
      "Behaves like greedy hill climbing",
      "Becomes a random walk",
      "Accepts more worse moves",
      "Restarts from a new random state",
    ],
    answer: 0,
    explanation: "As T approaches 0, exp(ΔE/T) approaches 0 for any negative ΔE, so worse moves are virtually never accepted. The algorithm becomes pure greedy ascent.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which crossover type picks each gene independently from either parent with probability 0.5?",
    options: [
      "Single-point crossover",
      "Two-point crossover",
      "3-way crossover",
      "Uniform crossover",
    ],
    answer: 3,
    explanation: "Uniform crossover decides per-gene which parent contributes, each with probability 0.5. Single-point uses one cut index; multi-point alternates segments between k cuts.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Plain steepest-ascent hill climbing solves what fraction of random 8-queens instances?",
    options: [
      "About 14%",
      "About 50%",
      "About 86%",
      "100%",
    ],
    answer: 0,
    explanation: "From a random start, plain hill climbing solves only about 14% of 8-queens instances; the rest get stuck at local minima such as configurations with h = 1 conflict remaining.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "A good fitness function for a GA should:",
    options: [
      "Be constant across all individuals to ensure fairness",
      "Always return integer values",
      "Differentiate between candidate solutions so that fitter individuals are favored by selection",
      "Be identical to the mutation operator",
    ],
    answer: 2,
    explanation: "The fitness function must provide a gradient of quality so that selection can preferentially reproduce better individuals. A flat or poorly designed fitness function gives selection no signal.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "In simulated annealing, an improving move (ΔE > 0) is accepted with what probability?",
    options: [
      "exp(ΔE/T)",
      "1 - exp(-ΔE/T)",
      "T / ΔE",
      "1 (always accepted)",
    ],
    answer: 3,
    explanation: "SA always accepts moves that improve the objective. The probabilistic acceptance rule exp(ΔE/T) only applies to worsening moves where ΔE is negative.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "The 'shoulder' in a state-space landscape refers to:",
    options: [
      "A peak that is below the global maximum",
      "A sharp drop in the landscape",
      "A flat plateau that has an uphill edge, so the search can eventually leave it",
      "The lowest point in the basin of attraction",
    ],
    answer: 2,
    explanation: "A shoulder is a plateau adjacent to an uphill slope. Unlike a 'flat' plateau where the algorithm has no gradient, the search can eventually walk off the shoulder and continue improving.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Stochastic beam search differs from standard local beam search in that:",
    options: [
      "It keeps only one state at a time",
      "It uses temperature schedules",
      "It does not use a fitness function",
      "It selects successors with probability proportional to their fitness, mimicking natural selection",
    ],
    answer: 3,
    explanation: "Stochastic beam search picks k successors with probabilities proportional to their values rather than deterministically taking the top k. This preserves diversity and bridges to genetic algorithms.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "In simulated annealing with ΔE = -1 and T = 10 vs. ΔE = -1 and T = 0.1, which acceptance probability is HIGHER and why?",
    options: [
      "T = 0.1, because lower temperature increases the exponent",
      "T = 10, because exp(-1/10) ≈ 0.905 while exp(-1/0.1) ≈ 0.00005",
      "Both are equal because ΔE is the same",
      "Neither move is ever accepted because ΔE is negative",
    ],
    answer: 1,
    explanation: "P = exp(ΔE/T). With T = 10, exp(-0.1) ≈ 0.905 (likely accepted). With T = 0.1, exp(-10) ≈ 0.00005 (rarely accepted). Higher T means more exploration, lower T means more exploitation.",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Path to goal is irrelevant — which class of search?",
    options: [
      "Informed",
      "Uninformed",
      "Local Search",
      "Both",
    ],
    answer: 2,
    explanation: "(verbatim sample question).",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "GA efficiency depends on:?",
    options: [
      "Initial conditions",
      "Population size",
      "Operators",
      "All of the above",
    ],
    answer: 3,
    explanation: "(verbatim sample question).",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Hill climbing gets stuck because:?",
    options: [
      "It is too slow",
      "It cannot accept worse moves (local optima)",
      "It uses too much memory",
      "It is not greedy",
    ],
    answer: 1,
    explanation: ".",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "In simulated annealing, when T → 0, the algorithm behaves like:?",
    options: [
      "Random walk",
      "Greedy hill climbing",
      "BFS",
      "Genetic algorithm",
    ],
    answer: 1,
    explanation: ".",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Random-restart hill climbing is complete because:?",
    options: [
      "It uses memory",
      "With enough restarts, probability of hitting the global max → 1",
      "It always finds the optimum in one run",
      "It uses crossover",
    ],
    answer: 1,
    explanation: ".",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Which is NOT a typical GA operator?",
    options: [
      "Crossover",
      "Mutation",
      "Selection",
      "Backtracking",
    ],
    answer: 3,
    explanation: ".",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Roulette-wheel selection assigns higher selection probability to individuals with:?",
    options: [
      "Lower fitness",
      "Higher fitness",
      "Random fitness",
      "Equal probability",
    ],
    answer: 1,
    explanation: ".",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Mutation in a GA is needed primarily to:?",
    options: [
      "Speed up convergence",
      "Combine parents",
      "Maintain genetic diversity / introduce missing alleles",
      "Reduce population size",
    ],
    answer: 2,
    explanation: ".",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Local beam search differs from k parallel hill climbs in that:?",
    options: [
      "It uses crossover",
      "It shares information between the k states (selects top k from all successors collectively)",
      "It uses temperature",
      "It has no fitness function",
    ],
    answer: 1,
    explanation: ".",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "For n-queens with n=8, the maximum number of non-attacking pairs is:?",
    options: [
      "8",
      "16",
      "28",
      "64",
    ],
    answer: 2,
    explanation: "(n(n-1)/2 = 28).",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "A \"plateau\" in the state-space landscape is:?",
    options: [
      "A unique global maximum",
      "A flat region where all neighbors have equal value",
      "A downhill ridge",
      "A randomly generated state",
    ],
    answer: 1,
    explanation: ".",
  },
  {
    week: 5,
    topic: "Local Search",
    question: "Typical GA crossover rate vs mutation rate:?",
    options: [
      "c ≈ 0.001, m ≈ 0.9",
      "c ≈ 0.9, m ≈ 0.05",
      "Both 0.5",
      "Both 1.0",
    ],
    answer: 1,
    explanation: ".",
  },
];

export default l05;
