import type { Question } from "../../types";

const l12: Question[] = [
  {
    week: 12,
    topic: "Clustering",
    question: "According to AIMA, k-means clustering can be viewed as a special case of which more general probabilistic algorithm?",
    options: [
      "Gradient descent on a logistic loss",
      "Expectation-Maximization (EM) for a Gaussian mixture with isotropic, equal-variance components",
      "Markov chain Monte Carlo sampling",
      "Variational inference for a Dirichlet process",
    ],
    answer: 1,
    explanation: "AIMA notes that k-means is EM for a Gaussian mixture in which every component has the same spherical covariance σ²I and the assignment step is hardened to argmax (rather than soft responsibilities).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Points A=(1,1), B=(2,1), C=(4,3), D=(5,4) are clustered with k-means using initial centroids μ1=(1,1) and μ2=(5,4). What are the centroids after one full iteration?",
    options: [
      "μ1=(1.5,1), μ2=(4.5,3.5)",
      "μ1=(1,1), μ2=(5,4)",
      "μ1=(2,1.5), μ2=(4,3)",
      "μ1=(3,2.25), μ2=(3,2.25)",
    ],
    answer: 0,
    explanation: "A and B are closest to μ1; C and D are closest to μ2. New μ1 = ((1+2)/2, (1+1)/2) = (1.5, 1). New μ2 = ((4+5)/2, (3+4)/2) = (4.5, 3.5).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Points (0,0), (1,0), (0,1), (7,7), (8,8) are clustered with k-means. Initial centroids: μ1=(0,0), μ2=(8,8). What are the centroids after one iteration?",
    options: [
      "μ1=(1/3, 1/3), μ2=(7.5, 7.5)",
      "μ1=(0.5, 0.5), μ2=(7.5, 7.5)",
      "μ1=(1,1), μ2=(7,7)",
      "μ1=(0, 0), μ2=(8, 8)",
    ],
    answer: 0,
    explanation: "(0,0), (1,0), (0,1) assign to μ1; (7,7), (8,8) assign to μ2. New μ1 = ((0+1+0)/3, (0+0+1)/3) = (1/3, 1/3). New μ2 = ((7+8)/2, (7+8)/2) = (7.5, 7.5).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Points (0,0), (4,0), (0,3), (4,3) and initial centroids μ1=(0,0), μ2=(4,3) are given. After one k-means iteration with Euclidean distance, what are the new centroids?",
    options: [
      "μ1=(0, 1.5), μ2=(4, 1.5)",
      "μ1=(2, 0), μ2=(2, 3)",
      "μ1=(2, 1.5), μ2=(2, 1.5)",
      "μ1=(0, 0), μ2=(4, 3)",
    ],
    answer: 0,
    explanation: "Distances: (0,0) is 0 from μ1 vs 5 from μ2 → C1. (4,0) is 4 vs 3 → C2. (0,3) is 3 vs 4 → C1. (4,3) is 5 vs 0 → C2. C1={(0,0),(0,3)} → mean (0, 1.5). C2={(4,0),(4,3)} → mean (4, 1.5).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the Manhattan (L1) distance between the 3D points (2, -1, 4) and (5, 3, 0).",
    options: [
      "11",
      "7",
      "√41",
      "9",
    ],
    answer: 0,
    explanation: "L1 distance = |2-5| + |-1-3| + |4-0| = 3 + 4 + 4 = 11.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the cosine similarity between vectors u=(1, 0, 1) and v=(0, 1, 1).",
    options: [
      "0.0",
      "0.5",
      "1.0",
      "-0.5",
    ],
    answer: 1,
    explanation: "u·v = 1·0 + 0·1 + 1·1 = 1. ‖u‖ = √2, ‖v‖ = √2. cos = 1 / (√2·√2) = 1/2 = 0.5.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Which clustering algorithm does NOT require the user to specify the number of clusters k in advance and can identify outliers as noise?",
    options: [
      "k-means",
      "k-means++",
      "Gaussian Mixture Model with fixed k components",
      "DBSCAN",
    ],
    answer: 3,
    explanation: "DBSCAN takes ε and MinPts (not k); it discovers the number of clusters from connectivity, finds arbitrarily shaped clusters, and labels low-density points as noise/outliers.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "With DBSCAN parameters Eps=1.5 and MinPts=3, consider the points A=(0,0), B=(1,0), C=(0,1), D=(5,5). Within Eps of A only A, B (d=1), C (d=1) lie. Within Eps of D only D lies. Classify D.",
    options: [
      "Core point",
      "Border point of A's cluster",
      "Noise point",
      "Border point of its own cluster",
    ],
    answer: 2,
    explanation: "D has only 1 point (itself) within Eps, fewer than MinPts=3, so D is not core. D is also not within Eps of any core point (A, B, or C). Hence D is noise.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "A point has mean intra-cluster distance a=6 and mean distance to the nearest other cluster b=2. What is its silhouette score, and what does it suggest?",
    options: [
      "s = +0.67, point is well-clustered",
      "s = -0.67, point is likely assigned to the wrong cluster",
      "s = 0, point is on a boundary",
      "s = -0.33, point is borderline",
    ],
    answer: 1,
    explanation: "s = (b - a) / max(a, b) = (2 - 6) / max(6, 2) = -4/6 ≈ -0.67. A strongly negative silhouette indicates the point is closer on average to a neighboring cluster than to its own — likely misassigned.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "In agglomerative hierarchical clustering with complete linkage, the distance between two clusters Ci and Cj is defined as:",
    options: [
      "min over x in Ci, y in Cj of d(x, y)",
      "max over x in Ci, y in Cj of d(x, y)",
      "The average of d(x, y) over all pairs",
      "The distance between the cluster centroids",
    ],
    answer: 1,
    explanation: "Complete (MAX) linkage uses the maximum pairwise distance between members of the two clusters. This produces compact, roughly spherical clusters and is less prone to chaining than single linkage.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Points (0,0), (0,1), (10,10), (10,11) are clustered with k-means. Initial centroids are μ1=(0,0) and μ2=(10,10). What are the updated centroids after one full iteration?",
    options: [
      "μ1=(0, 0.5), μ2=(10, 10.5)",
      "μ1=(0,0), μ2=(10,10)",
      "μ1=(5, 5.5), μ2=(5, 5.5)",
      "μ1=(0, 1), μ2=(10, 11)",
    ],
    answer: 0,
    explanation: "(0,0) and (0,1) are closest to μ1; (10,10) and (10,11) are closest to μ2. New μ1 = ((0+0)/2, (0+1)/2) = (0, 0.5). New μ2 = ((10+10)/2, (10+11)/2) = (10, 10.5).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Points (2,0), (3,1), (8,7), (9,8), (10,9) are clustered with k-means. Initial centroids are μ1=(2,0) and μ2=(10,9). What are the updated centroids after one iteration?",
    options: [
      "μ1=(2.5, 0.5), μ2=(9, 8)",
      "μ1=(2.5, 0.5), μ2=(9, 8.5)",
      "μ1=(2, 0), μ2=(10, 9)",
      "μ1=(3, 1), μ2=(8.5, 7.5)",
    ],
    answer: 0,
    explanation: "Points (2,0) and (3,1) are closest to μ1; (8,7), (9,8), (10,9) are closest to μ2. New μ1 = ((2+3)/2, (0+1)/2) = (2.5, 0.5). New μ2 = ((8+9+10)/3, (7+8+9)/3) = (9, 8).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Points (0,0), (2,0), (0,2), (6,6), (8,6) are clustered with k-means. Initial centroids are μ1=(0,0) and μ2=(8,6). What are the updated centroids after one iteration?",
    options: [
      "μ1=(0.67, 0.67), μ2=(7, 6)",
      "μ1=(1, 1), μ2=(7, 6)",
      "μ1=(0.67, 0.67), μ2=(7.33, 6)",
      "μ1=(2, 2), μ2=(8, 6)",
    ],
    answer: 0,
    explanation: "(0,0), (2,0), (0,2) are closest to μ1; (6,6) and (8,6) are closest to μ2. New μ1 = ((0+2+0)/3, (0+0+2)/3) = (2/3, 2/3) ≈ (0.67, 0.67). New μ2 = ((6+8)/2, (6+6)/2) = (7, 6).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Points (1,1), (2,2), (3,1), (8,8), (9,9), (10,8) are clustered with k-means. Initial centroids are μ1=(1,1) and μ2=(10,8). What are the updated centroids after one iteration?",
    options: [
      "μ1=(2, 1.33), μ2=(9, 8.33)",
      "μ1=(2, 2), μ2=(9, 9)",
      "μ1=(2.5, 1.5), μ2=(8.5, 8.5)",
      "μ1=(1, 1), μ2=(10, 8)",
    ],
    answer: 0,
    explanation: "(1,1), (2,2), (3,1) are closest to μ1; (8,8), (9,9), (10,8) are closest to μ2. New μ1 = ((1+2+3)/3, (1+2+1)/3) = (2, 4/3) ≈ (2, 1.33). New μ2 = ((8+9+10)/3, (8+9+8)/3) = (9, 25/3) ≈ (9, 8.33).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the Euclidean distance between P=(2,3) and Q=(5,7).",
    options: [
      "5",
      "7",
      "√7",
      "25",
    ],
    answer: 0,
    explanation: "d = √((2-5)² + (3-7)²) = √(9 + 16) = √25 = 5.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the Manhattan (L1) distance between P=(1,5) and Q=(4,1).",
    options: [
      "5",
      "7",
      "25",
      "√7",
    ],
    answer: 1,
    explanation: "Manhattan distance = |1-4| + |5-1| = 3 + 4 = 7.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the Euclidean distance between the 3D points (0,0,0) and (2,3,6).",
    options: [
      "7",
      "11",
      "√11",
      "49",
    ],
    answer: 0,
    explanation: "d = √((0-2)² + (0-3)² + (0-6)²) = √(4 + 9 + 36) = √49 = 7.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "With DBSCAN parameters Eps=2 and MinPts=3, classify point A=(1,1) given the dataset A=(1,1), B=(2,1), C=(3,1), D=(2,2), E=(10,10).",
    options: [
      "Noise",
      "Border",
      "Core",
      "Cannot be determined",
    ],
    answer: 2,
    explanation: "Distances from A within Eps=2: A itself, B (d=1), C (d=2), D (d=√2≈1.41). That gives 4 points within Eps, which is ≥ MinPts=3, so A is a core point.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "With DBSCAN Eps=1.5 and MinPts=4, given points A=(0,0), B=(1,0), C=(0,1), D=(1,1), E=(2,1), classify E. Note: D has 5 within-Eps neighbors (A, B, C, D, E) and is therefore a core point.",
    options: [
      "Core",
      "Border",
      "Noise",
      "Unreachable",
    ],
    answer: 1,
    explanation: "Within Eps=1.5 of E: E itself, B (d=√2≈1.41), D (d=1) → 3 neighbors < MinPts=4, so E is not core. However, E lies within Eps=1.5 of the core point D (d=1), so E is a border point that joins D's cluster.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "A point has mean intra-cluster distance a=3 and mean distance to the nearest other cluster b=4. Compute its silhouette score.",
    options: [
      "0.25",
      "-0.25",
      "0.33",
      "0.75",
    ],
    answer: 0,
    explanation: "s = (b - a) / max(a, b) = (4 - 3) / max(3, 4) = 1/4 = 0.25. Positive but small, indicating the point is only marginally closer to its own cluster than to the next.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "A k-means clustering yields two clusters: C1 = {(1,0), (3,0)} with centroid (2,0) and C2 = {(10,0), (12,0)} with centroid (11,0). What is the total WCSS (inertia)?",
    options: [
      "2",
      "4",
      "8",
      "16",
    ],
    answer: 1,
    explanation: "WCSS = Σ ‖x - μ_cluster(x)‖². C1: (1-2)² + (3-2)² = 1 + 1 = 2. C2: (10-11)² + (12-11)² = 1 + 1 = 2. Total inertia = 2 + 2 = 4.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "What is the defining characteristic of unsupervised learning, as used in clustering?",
    options: [
      "The algorithm uses labeled examples to predict a target variable",
      "The algorithm receives only feature vectors and must discover structure without labels",
      "The algorithm requires reinforcement signals from the environment",
      "The algorithm always knows the correct number of groups in advance",
    ],
    answer: 1,
    explanation: "Unsupervised learning operates with no target/label. The algorithm receives only feature vectors x_i and must discover structure such as groups, density, or hierarchy on its own.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the Euclidean distance between P=(3,4) and Q=(6,8).",
    options: [
      "5",
      "7",
      "25",
      "√7",
    ],
    answer: 0,
    explanation: "Euclidean distance = √((3-6)² + (4-8)²) = √(9 + 16) = √25 = 5.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the Manhattan (L1) distance between P=(1,2) and Q=(4,6).",
    options: [
      "5",
      "25",
      "7",
      "√7",
    ],
    answer: 2,
    explanation: "Manhattan distance = |1-4| + |2-6| = 3 + 4 = 7.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Which distance metric is most appropriate for high-dimensional sparse text data (e.g., TF-IDF vectors) where direction matters more than magnitude?",
    options: [
      "Euclidean (L2)",
      "Manhattan (L1)",
      "Cosine similarity",
      "Hamming",
    ],
    answer: 2,
    explanation: "Cosine similarity = (x·y)/(‖x‖‖y‖) ignores magnitude and measures the angle between vectors, which is ideal for high-dimensional sparse data such as text/TF-IDF.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "In k-means, after the assignment step assigns points to the nearest centroid, what does the update step do?",
    options: [
      "Re-randomizes centroid positions",
      "Recomputes each centroid as the mean of all points currently assigned to it",
      "Removes the farthest point from each cluster",
      "Merges the two closest clusters",
    ],
    answer: 1,
    explanation: "The update step recomputes each centroid as μ_j = mean of all x_i with c(i) = j. The algorithm repeats assign → update until centroids/labels stop changing.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Given points A=(2,2), B=(3,2), C=(8,8), D=(9,9) and initial centroids μ1=(2,2), μ2=(9,9), what are the updated centroids after one full iteration of k-means?",
    options: [
      "μ1=(2.5,2), μ2=(8.5,8.5)",
      "μ1=(2,2), μ2=(9,9)",
      "μ1=(3,3), μ2=(8,8)",
      "μ1=(2.5,2.5), μ2=(8,8.5)",
    ],
    answer: 0,
    explanation: "A and B are closest to μ1, C and D to μ2. New μ1 = ((2+3)/2,(2+2)/2) = (2.5, 2). New μ2 = ((8+9)/2,(8+9)/2) = (8.5, 8.5).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Given points (1,1), (1,2), (4,4), (5,5) and initial centroids μ1=(1,1), μ2=(5,5), what are the updated centroids after one k-means iteration?",
    options: [
      "μ1=(1,1.5), μ2=(4.5,4.5)",
      "μ1=(1,1), μ2=(5,5)",
      "μ1=(2.75,3), μ2=(2.75,3)",
      "μ1=(1.5,1), μ2=(4.5,4.5)",
    ],
    answer: 0,
    explanation: "(1,1) and (1,2) are nearest μ1; (4,4) and (5,5) are nearest μ2. New μ1 = ((1+1)/2,(1+2)/2) = (1, 1.5). New μ2 = ((4+5)/2,(4+5)/2) = (4.5, 4.5).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the centroid (mean) of the points (1,2), (3,4), and (5,0).",
    options: [
      "(4,3)",
      "(3,3)",
      "(3,2)",
      "(9,6)",
    ],
    answer: 2,
    explanation: "Centroid = ((1+3+5)/3, (2+4+0)/3) = (9/3, 6/3) = (3, 2).",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Compute the Euclidean distance between the 3D points (1,2,3) and (4,6,3).",
    options: [
      "7",
      "5",
      "√7",
      "25",
    ],
    answer: 1,
    explanation: "d = √((1-4)² + (2-6)² + (3-3)²) = √(9 + 16 + 0) = √25 = 5.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "What is the main purpose of k-means++ initialization?",
    options: [
      "To make k-means converge in exactly one iteration",
      "To choose initial centroids spread out from each other, with later centroids chosen with probability proportional to squared distance from already-chosen centroids",
      "To eliminate the need to choose k",
      "To replace Euclidean distance with cosine similarity",
    ],
    answer: 1,
    explanation: "k-means++ picks the first centroid randomly, then each subsequent centroid with probability proportional to squared distance from already-chosen centroids. This spreads centroids apart and reduces sensitivity to initialization.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Using the elbow method to choose k, where do you pick k?",
    options: [
      "The k that gives the smallest inertia (WCSS)",
      "The k where the WCSS curve bends — adding another cluster gives diminishing returns",
      "The k equal to the number of features",
      "The k where silhouette equals 0",
    ],
    answer: 1,
    explanation: "Inertia always decreases as k increases, so its minimum is uninformative. The elbow is the bend where additional clusters yield only small further reductions in WCSS.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "A point has mean intra-cluster distance a=2 and mean distance to the nearest other cluster b=5. What is its silhouette score?",
    options: [
      "0.6",
      "-0.6",
      "0.4",
      "1.0",
    ],
    answer: 0,
    explanation: "s = (b - a) / max(a, b) = (5 - 2) / max(2, 5) = 3/5 = 0.6. Positive and reasonably high, so this point is well-clustered.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "What does a silhouette score of approximately 0 indicate for a point?",
    options: [
      "The point is perfectly clustered",
      "The point is likely misassigned to the wrong cluster",
      "The point lies on or near the boundary between two clusters (a ≈ b)",
      "The clustering has no structure",
    ],
    answer: 2,
    explanation: "Silhouette is in [-1, 1]. A value near 0 means a ≈ b — the point is roughly as close to its own cluster as to the nearest other cluster, i.e. on a boundary.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Which silhouette value corresponds to the strongest case that a point has been assigned to the WRONG cluster?",
    options: [
      "+1",
      "0",
      "-1",
      "+0.5",
    ],
    answer: 2,
    explanation: "Silhouette ranges over [-1, 1]: +1 means very well-clustered, 0 means on the boundary, and -1 means the point is much closer to a neighboring cluster than to its own — i.e. probably misassigned.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Which hierarchical linkage tends to produce long, chained (stringy) clusters and is sensitive to noise?",
    options: [
      "Complete (MAX)",
      "Ward",
      "Average",
      "Single (MIN)",
    ],
    answer: 3,
    explanation: "Single linkage uses the minimum pairwise distance between clusters, which allows chains of close points to glue distant clusters together, producing long stringy shapes and sensitivity to noise.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Which linkage is often called the 'hierarchical analogue of k-means' because it minimizes the increase in SSE at each merge?",
    options: [
      "Single linkage",
      "Complete linkage",
      "Ward linkage",
      "Average linkage",
    ],
    answer: 2,
    explanation: "Ward linkage merges the pair whose merge increases SSE the least, producing globular clusters and behaving like a hierarchical version of k-means' objective.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "On a dendrogram, how do you obtain a clustering with exactly k clusters?",
    options: [
      "Re-run the algorithm with a parameter k",
      "Make a horizontal cut at a height that crosses exactly k vertical lines",
      "Always cut at the median merge height",
      "Cut at the lowest merge",
    ],
    answer: 1,
    explanation: "A horizontal cut at height h defines a clustering whose number of clusters equals the number of vertical branches the line crosses. Natural cuts lie below the longest vertical edges.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "With DBSCAN parameters Eps=2 and MinPts=3, classify P=(10,10) given the dataset A=(0,0), B=(1,0), C=(0,1), D=(10,10), E=(10,11). Note D is just an alias for P.",
    options: [
      "Core point",
      "Border point",
      "Noise point",
      "Cannot be determined",
    ],
    answer: 2,
    explanation: "Within Eps=2 of D=(10,10) only D and E (distance 1) appear → 2 points < MinPts=3, so D is not core. D is also not in the ε-neighborhood of any core point (A, B, C are far away). Therefore D is noise.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "With DBSCAN Eps=1.5 and MinPts=4, classify A=(0,0) given the points A=(0,0), B=(1,0), C=(0,1), D=(1,1), E=(5,5).",
    options: [
      "Core point",
      "Border point",
      "Noise point",
      "Outlier (none of the DBSCAN labels)",
    ],
    answer: 0,
    explanation: "Within Eps=1.5 of A: A itself, B (d=1), C (d=1), D (d=√2≈1.41) → 4 points ≥ MinPts=4, so A is a core point.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "With DBSCAN Eps=1.5 and MinPts=4, point F=(2,1) has within-Eps neighbors {F, B=(1,0) at d=√2≈1.41, D=(1,1) at d=1}. Given that D is a core point, how is F classified?",
    options: [
      "Core point, because it has neighbors within Eps",
      "Border point, because it has <MinPts neighbors but lies in the ε-neighborhood of a core point",
      "Noise point, because it has <MinPts neighbors",
      "Core point, because D is core",
    ],
    answer: 1,
    explanation: "F has only 3 < MinPts=4 neighbors within Eps, so F is not core. But F is within Eps=1.5 of the core point D (distance 1), so F is a border point and joins D's cluster.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Why does the curse of dimensionality degrade k-means and DBSCAN in very high dimensions?",
    options: [
      "Because matrix multiplication becomes too slow",
      "Because almost every pair of points becomes roughly equidistant, so Euclidean distance and density both lose discriminative power",
      "Because labels are no longer unique",
      "Because the silhouette score becomes undefined",
    ],
    answer: 1,
    explanation: "In high dimensions, (max distance − min distance) / min distance → 0, so points look nearly equidistant. Euclidean distance loses contrast and density in a fixed-radius ball collapses, hurting both k-means and DBSCAN.",
  },
  {
    week: 12,
    topic: "Clustering",
    question: "Which evaluation metric requires ground-truth labels and measures cluster-assignment agreement corrected for chance?",
    options: [
      "WCSS / Inertia",
      "Silhouette coefficient",
      "Adjusted Rand Index (ARI)",
      "Cohesion",
    ],
    answer: 2,
    explanation: "ARI is an external metric that compares predicted clusters to ground-truth labels, correcting for chance: 1 means perfect agreement and 0 means random. WCSS and silhouette are internal metrics that need no labels.",
  },
];

export default l12;
