import type { Question } from "../../types";

const l09: Question[] = [
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In AIMA's umbrella HMM, the transition model is P(R_t=T|R_{t-1}=T)=0.7, P(R_t=T|R_{t-1}=F)=0.3, the sensor model is P(U_t=T|R_t=T)=0.9, P(U_t=T|R_t=F)=0.2, and the prior is P(R_0=T)=0.5. On day 1 the umbrella is observed. What is the filtered posterior P(R_1=T | u_1)?",
    options: [
      "0.500",
      "0.627",
      "0.818",
      "0.900",
    ],
    answer: 2,
    explanation: "Predict: P(R_1=T) = 0.7*0.5 + 0.3*0.5 = 0.5; P(R_1=F) = 0.5. Update with u_1=T: (0.5*0.9, 0.5*0.2) = (0.45, 0.10). Normalize: 0.45/(0.45+0.10) = 9/11 ≈ 0.818.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Continuing the AIMA umbrella HMM, on day 2 the umbrella is again observed. Given the filter estimate after day 1 is P(R_1=T|u_1)=0.818, what is the filtered posterior P(R_2=T | u_1, u_2)?",
    options: [
      "0.883",
      "0.818",
      "0.627",
      "0.945",
    ],
    answer: 0,
    explanation: "Predict from f_1=(0.818, 0.182): P(R_2=T) = 0.818*0.7 + 0.182*0.3 = 0.627; P(R_2=F) = 0.373. Update with u_2=T: (0.627*0.9, 0.373*0.2) = (0.5647, 0.0746). Normalize: 0.5647/0.6393 ≈ 0.883.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In the umbrella HMM (same parameters as AIMA), suppose no umbrella is observed on day 1 (u_1 = F). What is the filtered posterior P(R_1=T | ¬u_1)?",
    options: [
      "0.083",
      "0.111",
      "0.200",
      "0.500",
    ],
    answer: 1,
    explanation: "Predict: (0.5, 0.5). Update with ¬u_1: P(¬U|R=T)=0.1, P(¬U|R=F)=0.8, giving (0.5*0.1, 0.5*0.8) = (0.05, 0.40). Normalize: 0.05/(0.05+0.40) = 1/9 ≈ 0.111.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In the AIMA umbrella HMM, given f_1=(0.818, 0.182) after observing u_1, what is the one-day-ahead prediction P(R_2=T | u_1) (i.e., no observation on day 2 yet)?",
    options: [
      "0.500",
      "0.627",
      "0.818",
      "0.945",
    ],
    answer: 1,
    explanation: "Prediction applies only the transition model: P(R_2=T|u_1) = 0.7*0.818 + 0.3*0.182 = 0.573 + 0.0546 = 0.627. No sensor update is performed because no day-2 evidence is given.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In the umbrella HMM, you observe umbrellas on days 1 and 2 and want to SMOOTH the estimate of day 1: P(R_1 | u_1, u_2). The backward message from day 2 is b_{2:2}(R_1=T) = sum over r_2 of P(u_2|r_2)P(r_2|R_1=T). Compute b_{2:2}(R_1=T).",
    options: [
      "0.41",
      "0.69",
      "0.55",
      "0.90",
    ],
    answer: 1,
    explanation: "b_{2:2}(R_1=T) = P(u_2=T|R_2=T)P(R_2=T|R_1=T) + P(u_2=T|R_2=F)P(R_2=F|R_1=T) = 0.9*0.7 + 0.2*0.3 = 0.63 + 0.06 = 0.69.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Continuing the smoothing problem: the unnormalized forward message after day 1 is f_1=(0.45, 0.10) and the backward message is b_{2:2}=(0.69, 0.41). What is the smoothed posterior P(R_1=T | u_1, u_2)?",
    options: [
      "0.945",
      "0.818",
      "0.627",
      "0.883",
    ],
    answer: 3,
    explanation: "Smoothed posterior is proportional to f_1 * b_{2:2} elementwise: (0.45*0.69, 0.10*0.41) = (0.3105, 0.041). Normalize: 0.3105/(0.3105+0.041) = 0.3105/0.3515 ≈ 0.883.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Running Viterbi on the umbrella HMM with observations (u_1=T, u_2=T). Initialize m_1 = (P(R_0=T)P(u_1|R_1=T) summed over R_0) using transition predict-then-multiply form: m_1(R_1=T) = max over R_0 of P(R_0)*P(R_1=T|R_0)*P(u_1|R_1=T). With uniform P(R_0)=0.5 this reduces to 0.5*0.9=0.45 for T and 0.5*0.2=0.10 for F. What is m_2(R_2=T)?",
    options: [
      "0.3105",
      "0.135",
      "0.027",
      "0.2835",
    ],
    answer: 3,
    explanation: "m_2(R_2=T) = max(m_1(T)*0.7, m_1(F)*0.3) * P(u_2=T|R_2=T) = max(0.45*0.7, 0.10*0.3)*0.9 = max(0.315, 0.030)*0.9 = 0.315*0.9 = 0.2835.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Viterbi continued: m_2(R=T)=0.2835 and m_2(R=F)=0.027. On day 3 NO umbrella is observed (¬u_3). What are m_3(R=T) and m_3(R=F)?",
    options: [
      "m_3(T)=0.0198, m_3(F)=0.0680",
      "m_3(T)=0.1785, m_3(F)=0.0851",
      "m_3(T)=0.0851, m_3(F)=0.0198",
      "m_3(T)=0.2552, m_3(F)=0.0162",
    ],
    answer: 0,
    explanation: "m_3(T) = max(0.2835*0.7, 0.027*0.3)*P(¬U|R=T) = max(0.198, 0.0081)*0.1 = 0.0198. m_3(F) = max(0.2835*0.3, 0.027*0.7)*P(¬U|R=F) = max(0.0851, 0.0189)*0.8 = 0.0680. After day 3 the best path now switches to R_3=F.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In the matrix forward equation f_{1:t+1} = α · O_{t+1} · T^T · f_{1:t} from AIMA, what does the diagonal matrix O_{t+1} represent?",
    options: [
      "A diagonal matrix whose entries are P(e_{t+1} | X_{t+1}=x) for each state x",
      "The prior P(X_0)",
      "The transition probabilities P(X_{t+1} | X_t)",
      "The normalization constant",
    ],
    answer: 0,
    explanation: "O_{t+1} is a diagonal observation matrix with the sensor likelihoods P(e_{t+1}|X_{t+1}=x_i) on its diagonal. Multiplying T^T·f propagates belief forward, then O_{t+1} weights each state by how well it explains the new evidence.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Why are particle filters preferred over exact forward filtering for many real-world dynamic systems (e.g., robot localization with continuous pose)?",
    options: [
      "Particle filters give exact posteriors faster than the forward algorithm",
      "Particle filters do not require a transition model",
      "Exact filtering requires the observations to be deterministic",
      "The state space is continuous or very high-dimensional, so exact enumeration of states is infeasible; particles approximate the belief by samples",
    ],
    answer: 3,
    explanation: "Particle filtering represents the belief P(X_t|e_{1:t}) by a weighted sample of N particles. Each step: (1) propagate each particle through the transition model, (2) weight by the sensor model P(e_{t+1}|x), (3) resample. This scales to continuous/high-dim state spaces where summing over all states is impossible.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "HMM with states {Rain, Sun}, initial P(R)=0.5, P(S)=0.5, emission P(umbrella|R)=0.9, P(umbrella|S)=0.2. After observing 'umbrella' on day 1, what is the filtered posterior P(R_1 | u_1)?",
    options: [
      "0.45",
      "0.55",
      "0.818",
      "0.900",
    ],
    answer: 2,
    explanation: "alpha_1(R) = 0.5*0.9 = 0.45; alpha_1(S) = 0.5*0.2 = 0.10. P(u_1) = 0.45+0.10 = 0.55. P(R_1|u_1) = 0.45/0.55 = 9/11 approx 0.818.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Ice-cream HMM: pi_HOT=0.8, pi_COLD=0.2; b_HOT(3)=0.4, b_COLD(3)=0.1. After observing o_1 = 3, what is the unnormalized total likelihood P(o_1 = 3 | lambda) = alpha_1(HOT) + alpha_1(COLD)?",
    options: [
      "0.34",
      "0.50",
      "0.42",
      "0.30",
    ],
    answer: 0,
    explanation: "alpha_1(HOT) = 0.8*0.4 = 0.32; alpha_1(COLD) = 0.2*0.1 = 0.02. Sum = 0.32+0.02 = 0.34.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Continuing the ice-cream HMM with a_HH=0.6, a_HC=0.3, a_CH=0.4, a_CC=0.5; b_HOT(1)=0.2, b_COLD(1)=0.5. Given alpha_1(HOT)=0.32 and alpha_1(COLD)=0.02, what is alpha_2(COLD) after observing o_2 = 1?",
    options: [
      "0.0400",
      "0.0480",
      "0.0530",
      "0.1060",
    ],
    answer: 2,
    explanation: "alpha_2(COLD) = [alpha_1(HOT)*a_HC + alpha_1(COLD)*a_CC] * b_COLD(1) = [0.32*0.3 + 0.02*0.5]*0.5 = [0.096+0.010]*0.5 = 0.106*0.5 = 0.053.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Same ice-cream HMM as Q3. Given alpha_2(HOT)=0.040 and alpha_2(COLD)=0.053, what is the total likelihood P(o_1=3, o_2=1 | lambda)?",
    options: [
      "0.034",
      "0.093",
      "0.106",
      "0.200",
    ],
    answer: 1,
    explanation: "The total likelihood after T observations is the sum over the final forward column: P(o_1..o_T | lambda) = Sum_j alpha_T(j). Here 0.040 + 0.053 = 0.093.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Ice-cream HMM with a_HH=0.6, a_CH=0.4, b_HOT(3)=0.4. Given alpha_2(HOT)=0.040 and alpha_2(COLD)=0.053, compute alpha_3(HOT) after observing o_3 = 3.",
    options: [
      "0.01808",
      "0.00385",
      "0.04520",
      "0.02193",
    ],
    answer: 0,
    explanation: "alpha_3(HOT) = [alpha_2(HOT)*a_HH + alpha_2(COLD)*a_CH]*b_HOT(3) = [0.040*0.6 + 0.053*0.4]*0.4 = [0.024 + 0.0212]*0.4 = 0.0452*0.4 = 0.01808.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Rain/Sun HMM: a_RR=0.7, a_RS=0.3, a_SR=0.3, a_SS=0.7; b_R(u)=0.9, b_S(u)=0.2; pi_R=pi_S=0.5. After observing umbrella on day 1 then umbrella on day 2, what is alpha_2(Rain)?",
    options: [
      "0.3105",
      "0.3550",
      "0.4050",
      "0.2835",
    ],
    answer: 0,
    explanation: "alpha_1(R)=0.5*0.9=0.45, alpha_1(S)=0.5*0.2=0.10. alpha_2(R) = [0.45*0.7 + 0.10*0.3]*0.9 = [0.315 + 0.030]*0.9 = 0.345*0.9 = 0.3105.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Continuing the Rain/Sun HMM from Q6: alpha_2(Rain)=0.3105 and alpha_2(Sun)=0.041. What is the filtered posterior P(Rain_2 | u_1, u_2)?",
    options: [
      "0.620",
      "0.755",
      "0.883",
      "0.910",
    ],
    answer: 2,
    explanation: "alpha_2(S) = [0.45*0.3 + 0.10*0.7]*0.2 = [0.135+0.070]*0.2 = 0.205*0.2 = 0.041. P(R_2|u_1,u_2) = 0.3105/(0.3105+0.041) = 0.3105/0.3515 approx 0.883.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Viterbi for ice-cream HMM with a_HH=0.6, a_HC=0.3, a_CH=0.4, a_CC=0.5; b_HOT(1)=0.2, b_COLD(1)=0.5. Given v_1(HOT)=0.32 and v_1(COLD)=0.02, what are v_2(COLD) and bp_2(COLD)?",
    options: [
      "v_2(COLD)=0.0480, bp_2(COLD)=HOT",
      "v_2(COLD)=0.0530, bp_2(COLD)=COLD",
      "v_2(COLD)=0.0100, bp_2(COLD)=COLD",
      "v_2(COLD)=0.0960, bp_2(COLD)=HOT",
    ],
    answer: 0,
    explanation: "v_2(COLD) = max(v_1(H)*a_HC, v_1(C)*a_CC) * b_COLD(1) = max(0.32*0.3, 0.02*0.5)*0.5 = max(0.096, 0.010)*0.5 = 0.096*0.5 = 0.048. The argmax was HOT (0.096 > 0.010), so bp_2(COLD) = HOT.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Viterbi continued: v_2(HOT)=0.0384, v_2(COLD)=0.0480; a_HH=0.6, a_CH=0.4; b_HOT(3)=0.4. What are v_3(HOT) and bp_3(HOT) after observing o_3 = 3?",
    options: [
      "v_3(HOT)=0.01808, bp_3(HOT)=HOT",
      "v_3(HOT)=0.00922, bp_3(HOT)=HOT",
      "v_3(HOT)=0.00922, bp_3(HOT)=COLD",
      "v_3(HOT)=0.01920, bp_3(HOT)=COLD",
    ],
    answer: 1,
    explanation: "v_3(HOT) = max(v_2(H)*a_HH, v_2(C)*a_CH) * b_HOT(3) = max(0.0384*0.6, 0.0480*0.4)*0.4 = max(0.02304, 0.01920)*0.4 = 0.02304*0.4 = 0.009216. The argmax came from HOT (0.02304 > 0.01920), so bp_3(HOT) = HOT.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "A meteorologist wants to estimate P(Weather_3 | umbrella_1, umbrella_2, umbrella_3, umbrella_4, umbrella_5) using all five days of observations. Which inference task is this?",
    options: [
      "Filtering",
      "Prediction",
      "Smoothing",
      "Most likely explanation (Viterbi)",
    ],
    answer: 2,
    explanation: "Estimating a PAST state (t=3) given evidence up to a LATER time (t=5) is smoothing. It uses the forward-backward algorithm. Filtering would query the current state X_t with e_{1:t}; prediction queries future states; MLE returns the best whole path.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "A speech recognizer must output the single most probable phoneme sequence given the acoustic signal. Which HMM problem / algorithm applies?",
    options: [
      "Evaluation, solved by Forward",
      "Decoding, solved by Viterbi",
      "Learning, solved by Baum-Welch",
      "Filtering, solved by forward normalization",
    ],
    answer: 1,
    explanation: "Returning argmax over the entire hidden sequence given the observations is the decoding problem, solved by Viterbi (using max with back-pointers). Forward only returns P(O|lambda); Baum-Welch learns parameters; filtering gives only the current state.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Which statement about the first-order Markov assumption in an HMM is TRUE?",
    options: [
      "It states P(q_t | q_1,...,q_{t-1}) = P(q_t | q_{t-1}, q_{t-2}), depending on the last two states",
      "It states P(o_t | q_t) does not depend on prior observations",
      "It states P(q_t | q_1,...,q_{t-1}) = P(q_t | q_{t-1}), so the current state depends only on the immediately previous state",
      "It states that the transition matrix A changes over time",
    ],
    answer: 2,
    explanation: "The first-order Markov assumption is exactly P(q_t | q_1..q_{t-1}) = P(q_t | q_{t-1}). Option A describes a second-order model, B is the output-independence (sensor) assumption (a separate HMM assumption), and D contradicts the stationarity assumption.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In a Hidden Markov Model, which of the following is NOT directly observed?",
    options: [
      "The emission symbols o_t",
      "The hidden states q_t",
      "The observation sequence O",
      "The evidence at each time step",
    ],
    answer: 1,
    explanation: "The defining property of an HMM is that the underlying states q_t are hidden; we only observe the emissions o_t produced by those states. This contrasts with a Markov chain where the states themselves are observable.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "The first-order Markov assumption states that:",
    options: [
      "P(q_t) is independent of all past states",
      "P(o_t | q_t) = P(o_t | q_{t-1})",
      "P(q_t | q_{t-1}) changes over time",
      "P(q_t | q_1,...,q_{t-1}) = P(q_t | q_{t-1})",
    ],
    answer: 3,
    explanation: "The first-order Markov assumption says the current state depends only on the immediately previous state, not on the entire history. This is what makes efficient dynamic programming (Forward/Viterbi) possible.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "The output-independence (sensor) assumption of an HMM is:",
    options: [
      "P(o_t | q_t) = P(q_t | o_t)",
      "P(o_t | q_1..q_t, o_1..o_{t-1}) = P(o_t | q_t)",
      "Observations are independent of states",
      "P(o_t | o_{t-1}) = P(o_t)",
    ],
    answer: 1,
    explanation: "Output-independence says the current observation depends only on the current hidden state, not on any past state or observation. Together with the Markov assumption, it gives the HMM its tractable factored form.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "An HMM with N hidden states has a transition matrix A of what dimensions?",
    options: [
      "N x T where T is the sequence length",
      "N x M where M is the number of observation symbols",
      "N x N",
      "(N+2) x (N+2) always",
    ],
    answer: 2,
    explanation: "The transition matrix A has one row and one column per hidden state, so it is N x N. Entry a_{ij} = P(q_t = j | q_{t-1} = i), and each row sums to 1.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "If an HMM has N=4 hidden states and M=6 possible emission symbols, what is the size of the emission matrix B?",
    options: [
      "4 x 4",
      "6 x 6",
      "4 x 6",
      "6 x 4",
    ],
    answer: 2,
    explanation: "The emission matrix B is N x M, with entry b_j(o) = P(o_t = o | q_t = j). Each row corresponds to a hidden state and gives a probability distribution over the M possible observation symbols.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "What does the 'stationary' assumption in an HMM mean?",
    options: [
      "The hidden state never changes over time",
      "The distribution over states is uniform",
      "The transition and emission probabilities do not depend on t",
      "The system has converged to a stationary distribution",
    ],
    answer: 2,
    explanation: "Stationarity in HMMs means the parameters A and B are time-invariant: the same probabilities apply at every step. It does NOT mean the state distribution is constant or that the chain has reached its stationary distribution.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Which of the three basic HMM problems is solved by the Baum-Welch algorithm?",
    options: [
      "Filtering",
      "Decoding",
      "Evaluation / Likelihood",
      "Learning the parameters",
    ],
    answer: 3,
    explanation: "Baum-Welch is an Expectation-Maximization algorithm that learns the HMM parameters (A, B, pi) from observation sequences alone. Evaluation uses Forward, and decoding uses Viterbi.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Computing the posterior P(X_k | e_{1:t}) where k < t is called:",
    options: [
      "Filtering",
      "Prediction",
      "Smoothing",
      "Most likely explanation",
    ],
    answer: 2,
    explanation: "Smoothing estimates a PAST state given all evidence up to a later time t, using the forward-backward algorithm. Filtering is for the current state (k=t), prediction is for future (k>t), and MLE is the best whole path.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "The query P(X_t | e_{1:t}) corresponds to which inference task?",
    options: [
      "Filtering",
      "Smoothing",
      "Prediction",
      "Decoding",
    ],
    answer: 0,
    explanation: "Filtering computes the belief about the CURRENT state X_t given all evidence observed so far. It uses the same forward recursion as the evaluation problem, but normalizes the result at each step.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Consider an HMM with states {Rain, Sun}, pi_R = 0.5, pi_S = 0.5, and emission probabilities b_R(umbrella) = 0.9 and b_S(umbrella) = 0.2. What is alpha_1(Rain) after observing 'umbrella' at t=1?",
    options: [
      "0.10",
      "0.18",
      "0.45",
      "0.90",
    ],
    answer: 2,
    explanation: "alpha_1(Rain) = pi_R * b_R(umbrella) = 0.5 * 0.9 = 0.45. Initialization of the forward variable just multiplies the initial probability by the emission probability for the first observation.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Using the HMM from the previous question, suppose alpha_1(Rain) = 0.45 and alpha_1(Sun) = 0.10. With transition probabilities a_RR = 0.7, a_SR = 0.4 and emission b_R(umbrella) = 0.9, what is alpha_2(Rain) after a second 'umbrella' observation?",
    options: [
      "0.3195",
      "0.3550",
      "0.4050",
      "0.2835",
    ],
    answer: 0,
    explanation: "alpha_2(Rain) = [alpha_1(R)*a_RR + alpha_1(S)*a_SR] * b_R(umbrella) = [0.45*0.7 + 0.10*0.4] * 0.9 = [0.315 + 0.040] * 0.9 = 0.355 * 0.9 = 0.3195.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In the ice-cream HMM (a_HH=0.6, a_CH=0.4, b_H(1)=0.2), given alpha_1(HOT)=0.32 and alpha_1(COLD)=0.02, what is alpha_2(HOT) after observing 1 ice cream?",
    options: [
      "0.0400",
      "0.0530",
      "0.0464",
      "0.0200",
    ],
    answer: 0,
    explanation: "alpha_2(HOT) = [alpha_1(HOT)*a_HH + alpha_1(COLD)*a_CH] * b_H(1) = [0.32*0.6 + 0.02*0.4] * 0.2 = [0.192 + 0.008] * 0.2 = 0.200 * 0.2 = 0.0400.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In the Viterbi recursion v_t(j) = [max_i v_{t-1}(i) * a_{i,j}] * b_j(o_t), why is b_j(o_t) placed OUTSIDE the max?",
    options: [
      "Because max requires summing emission probabilities first",
      "Because Viterbi never uses emission probabilities inside the max",
      "Because b_j(o_t) is always equal to 1",
      "Because b_j(o_t) does not depend on the previous state i, so it can be factored out",
    ],
    answer: 3,
    explanation: "Since b_j(o_t) depends only on the current state j and current observation, not on the predecessor i, multiplying it inside or outside the max gives the same result. Factoring it out saves redundant multiplications.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Given v_1(HOT) = 0.32, v_1(COLD) = 0.02, a_HH = 0.6, a_CH = 0.4, and b_H(1) = 0.2, what is v_2(HOT) and its back-pointer bp_2(HOT)?",
    options: [
      "v_2(HOT) = 0.0384, bp_2(HOT) = HOT",
      "v_2(HOT) = 0.0400, bp_2(HOT) = HOT",
      "v_2(HOT) = 0.0480, bp_2(HOT) = COLD",
      "v_2(HOT) = 0.0464, bp_2(HOT) = HOT",
    ],
    answer: 0,
    explanation: "v_2(HOT) = max(0.32*0.6, 0.02*0.4) * 0.2 = max(0.192, 0.008) * 0.2 = 0.192 * 0.2 = 0.0384. The maximum came from HOT (0.192 > 0.008), so bp_2(HOT) = HOT.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Suppose after running Viterbi to time T=3, you have v_3(HOT) = 0.009216, v_3(COLD) = 0.0024, bp_3(HOT)=HOT, bp_3(COLD)=COLD, bp_2(HOT)=HOT, bp_2(COLD)=HOT. What is the most likely state sequence?",
    options: [
      "COLD, HOT, HOT",
      "HOT, COLD, HOT",
      "HOT, HOT, HOT",
      "COLD, COLD, COLD",
    ],
    answer: 2,
    explanation: "Backtrace from argmax(v_3) = HOT (since 0.009216 > 0.0024). Then q_3* = HOT, bp_3(HOT)=HOT gives q_2* = HOT, bp_2(HOT)=HOT gives q_1* = HOT. The path is HOT, HOT, HOT.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "Why would naively summing over all hidden state sequences to compute P(O | lambda) be intractable for long observation sequences?",
    options: [
      "Because there are N*T sequences, which is too many",
      "Because there are N^T possible hidden state sequences (exponential in T)",
      "Because probabilities become too small to represent",
      "Because the transition matrix must be inverted",
    ],
    answer: 1,
    explanation: "With N hidden states and T time steps, there are N^T possible hidden sequences. The Forward algorithm uses dynamic programming to exploit the Markov property and reduce this to O(N^2 * T).",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In the AIMA matrix forward equation f_{1:t+1} = alpha * O_{t+1} * T^T * f_{1:t}, what is the role of T^T (the transpose of the transition matrix)?",
    options: [
      "It propagates the belief one step forward by predicting the next state",
      "It normalizes the message to sum to 1",
      "It applies the emission likelihood",
      "It reverses time for smoothing",
    ],
    answer: 0,
    explanation: "Multiplying the current belief by T^T performs the predict step, mapping P(X_t | e_{1:t}) to the prior P(X_{t+1} | e_{1:t}). Then O_{t+1} (diagonal of sensor probabilities) weights by evidence, and alpha renormalizes.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "In the forward-backward algorithm for smoothing, the smoothed posterior P(q_k = i | O, lambda) is proportional to:",
    options: [
      "alpha_k(i) only",
      "alpha_k(i) + beta_k(i)",
      "beta_k(i) only",
      "alpha_k(i) * beta_k(i)",
    ],
    answer: 3,
    explanation: "Smoothing combines the forward message alpha_k(i) = P(o_1..o_k, q_k=i) with the backward message beta_k(i) = P(o_{k+1}..o_T | q_k=i). Their product (after normalization) gives the posterior given all evidence.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "A particle filter is most appropriate when:",
    options: [
      "The state space is small and discrete with exact inference feasible",
      "The state space is large or continuous, requiring an approximate sample-based belief",
      "The model is linear-Gaussian, making Kalman filtering exact",
      "We only care about the maximum-likelihood path",
    ],
    answer: 1,
    explanation: "Particle filters approximate the belief state by a weighted set of samples (particles), each propagated by the transition model and reweighted by observation likelihood. They are used when exact filtering is intractable due to large or continuous state spaces.",
  },
  {
    week: 9,
    topic: "Hidden Markov Models",
    question: "The ONLY structural difference between the Forward and Viterbi algorithms is:",
    options: [
      "Forward uses max while Viterbi uses sum over previous states",
      "Viterbi uses max (with back-pointers) while Forward uses sum over previous states",
      "Viterbi runs right-to-left while Forward runs left-to-right",
      "Forward uses log probabilities while Viterbi uses raw probabilities",
    ],
    answer: 1,
    explanation: "Forward sums probabilities of all paths reaching state j at time t (giving the total likelihood). Viterbi takes the max instead and stores back-pointers so the best path can be reconstructed. Both run left-to-right with O(N^2 * T) complexity.",
  },
];

export default l09;
