import type { Question } from "../../types";

const l11: Question[] = [
  {
    week: 11,
    topic: "Regression",
    question: "According to AIMA, univariate linear regression fits a hypothesis h_w(x) = w_1 x + w_0 by minimizing the empirical loss. Which loss function is used for ordinary least squares?",
    options: [
      "L_1(y, h_w(x)) = |y - h_w(x)|",
      "L_2(y, h_w(x)) = (y - h_w(x))^2",
      "L_0/1(y, h_w(x)) = 1 if y != h_w(x) else 0",
      "Cross-entropy loss",
    ],
    answer: 1,
    explanation: "AIMA Ch. 19 defines OLS via the squared-error (L2) loss summed over examples: Loss(h_w) = Σ (y_j - h_w(x_j))^2. Minimizing this yields the normal equations.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given y = [4, 6, 8, 10] and predictions ŷ = [5, 5, 9, 9], what is the MSE?",
    options: [
      "0.50",
      "1.00",
      "2.00",
      "4.00",
    ],
    answer: 1,
    explanation: "Residuals: 4-5=-1, 6-5=1, 8-9=-1, 10-9=1. Squared: 1,1,1,1. Sum=4. MSE = 4/4 = 1.00.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given y = [2, 4, 6, 8, 10] (mean ȳ = 6) and predictions ŷ = [3, 3, 7, 7, 10], what is R² (rounded to 2 decimals)?",
    options: [
      "0.50",
      "0.78",
      "0.90",
      "0.95",
    ],
    answer: 2,
    explanation: "SSres = (2-3)^2+(4-3)^2+(6-7)^2+(8-7)^2+(10-10)^2 = 1+1+1+1+0 = 4. SStot = (2-6)^2+(4-6)^2+(6-6)^2+(8-6)^2+(10-6)^2 = 16+4+0+4+16 = 40. R² = 1 - 4/40 = 0.90.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "The normal equation for ordinary least squares is w* = (X^T X)^(-1) X^T y. Which condition must hold for this closed-form solution to exist as written?",
    options: [
      "The data must be normally distributed",
      "X^T X must be invertible (features linearly independent, n ≥ d)",
      "The learning rate must be small",
      "The targets y must be non-negative",
    ],
    answer: 1,
    explanation: "AIMA Ch. 19: the normal equation requires X^T X to be non-singular (invertible). With perfectly collinear features or n < d this fails, motivating Ridge regression which adds λI.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Starting from w_1 = 0, w_0 = 0, η = 0.1, fit on a single example (x, y) = (3, 6) using L_2 loss. AIMA gives the update w_1 := w_1 + η (y - h_w(x)) x. What is the new w_1 after one step?",
    options: [
      "0.6",
      "1.8",
      "3.6",
      "6.0",
    ],
    answer: 1,
    explanation: "h_w(x) = 0·3 + 0 = 0. Error y - h_w(x) = 6 - 0 = 6. w_1 := 0 + 0.1·6·3 = 1.8. (AIMA's update absorbs the factor of 2 into η.)",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given y = [1, 2, 3, 4] and predictions ŷ = [2, 3, 4, 5], what is the RMSE?",
    options: [
      "0.50",
      "1.00",
      "1.41",
      "2.00",
    ],
    answer: 1,
    explanation: "Residuals all equal -1, squared = 1 each. MSE = 4/4 = 1. RMSE = √1 = 1.00. Notice the predictions are systematically biased by +1.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "In stochastic gradient descent (SGD) for linear regression, how does it differ from batch gradient descent?",
    options: [
      "SGD computes the gradient over the entire dataset before each update",
      "SGD updates weights using the gradient from one randomly chosen example at a time, giving noisier but cheaper updates",
      "SGD always converges faster to the exact minimum than batch GD",
      "SGD only works for classification, not regression",
    ],
    answer: 1,
    explanation: "AIMA Ch. 19: SGD picks one (or a few) examples per step, making each step O(d) instead of O(nd). The noise can help escape shallow plateaus but requires a decaying learning rate to converge.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Starting with w = [1, 2], b = 0, η = 0.1, predict on the point (x_1, x_2, y) = (1, 1, 5) with squared loss. Using w := w - η · 2 (ŷ - y) x for each component, what is the new w_1?",
    options: [
      "0.6",
      "1.0",
      "1.4",
      "2.0",
    ],
    answer: 2,
    explanation: "ŷ = 1·1 + 2·1 + 0 = 3. Error ŷ - y = 3 - 5 = -2. Gradient w.r.t. w_1 = 2·(-2)·1 = -4. Update: w_1 := 1 - 0.1·(-4) = 1.4.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "AIMA notes that L_1 regularization (Lasso) tends to produce sparse weight vectors, while L_2 (Ridge) merely shrinks them. Why?",
    options: [
      "Because L_1 uses absolute value, whose subgradient at 0 allows w_j = 0 to be optimal for a range of data",
      "Because L_2 is non-differentiable at 0",
      "Because L_1 is computed only on the bias term",
      "Because L_2 is exponentially larger than L_1",
    ],
    answer: 0,
    explanation: "The L_1 penalty |w_j| has a kink at 0 whose subgradient interval [-λ, λ] can absorb the data gradient, making w_j = 0 an optimum. L_2 is smooth at 0, so weights are merely pulled toward but rarely equal 0.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "A linear regression on a held-out test set reports SSres = 120 and SStot = 100. What is R², and what does it mean?",
    options: [
      "R² = 1.2; the model is excellent",
      "R² = -0.2; the model is worse than predicting the mean of y",
      "R² = 0.2; the model explains 20% of variance",
      "R² is undefined because SSres > SStot",
    ],
    answer: 1,
    explanation: "R² = 1 - SSres/SStot = 1 - 120/100 = -0.20. Negative R² on a test set means the model's squared error exceeds that of the constant mean predictor — it generalizes poorly.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given true values y = [2, 4, 6] and predictions y_hat = [1, 5, 8], what is the MSE?",
    options: [
      "1.33",
      "2.00",
      "6.00",
      "3.00",
    ],
    answer: 1,
    explanation: "Residuals (y - y_hat): 2-1=1, 4-5=-1, 6-8=-2. Squared: 1, 1, 4. Sum = 6. MSE = (1/n) * sum = 6/3 = 2.00.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given y = [5, 10, 15, 20] and y_hat = [7, 9, 14, 22], what is the RMSE (rounded to 3 decimals)?",
    options: [
      "1.500",
      "2.500",
      "1.581",
      "2.236",
    ],
    answer: 2,
    explanation: "Residuals: -2, 1, 1, -2. Squared: 4, 1, 1, 4. Sum = 10. MSE = 10/4 = 2.5. RMSE = sqrt(2.5) ≈ 1.581.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given y = [8, 6, 4, 2] and y_hat = [7, 7, 5, 1], what is the MAE?",
    options: [
      "0.50",
      "1.00",
      "2.00",
      "4.00",
    ],
    answer: 1,
    explanation: "Absolute residuals: |8-7|=1, |6-7|=1, |4-5|=1, |2-1|=1. Sum = 4. MAE = 4/4 = 1.00.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given y = [1, 3, 5, 7, 9] (mean = 5) and y_hat = [2, 3, 5, 7, 8], what is R²?",
    options: [
      "0.85",
      "0.90",
      "0.95",
      "1.00",
    ],
    answer: 2,
    explanation: "SSE = (1-2)² + (3-3)² + (5-5)² + (7-7)² + (9-8)² = 1+0+0+0+1 = 2. SST = (1-5)² + (3-5)² + (5-5)² + (7-5)² + (9-5)² = 16+4+0+4+16 = 40. R² = 1 - SSE/SST = 1 - 2/40 = 0.95.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Starting with w = 0.5, b = 0.5, learning rate η = 0.1, and a single point (x, y) = (2, 3) under MSE loss L = (wx + b - y)², what is the new w after one gradient descent step?",
    options: [
      "0.50",
      "1.10",
      "0.80",
      "-0.10",
    ],
    answer: 1,
    explanation: "y_hat = 0.5·2 + 0.5 = 1.5. Error = y_hat - y = 1.5 - 3 = -1.5. ∂L/∂w = 2·(error)·x = 2·(-1.5)·2 = -6. Update: w = 0.5 - 0.1·(-6) = 0.5 + 0.6 = 1.10.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Starting with w = 1, b = 0, learning rate η = 0.05, and a point (x, y) = (4, 6) (MSE on one point), what is the new b after one gradient descent step?",
    options: [
      "0.10",
      "0.20",
      "-0.20",
      "0.40",
    ],
    answer: 1,
    explanation: "y_hat = 1·4 + 0 = 4. Error = 4 - 6 = -2. ∂L/∂b = 2·(error) = 2·(-2) = -4. Update: b = 0 - 0.05·(-4) = 0.20.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Batch gradient descent with two points (x, y) = (1, 2) and (3, 4). Current w = 0, b = 0, η = 0.1. Using MSE = (1/n) Σ (wx_i + b - y_i)², what is the new w after one step?",
    options: [
      "0.70",
      "1.40",
      "2.80",
      "0.14",
    ],
    answer: 1,
    explanation: "Predictions: y_hat = [0, 0]. Errors: [-2, -4]. ∂L/∂w = (2/n) Σ error_i·x_i = (2/2)·((-2)·1 + (-4)·3) = 1·(-2 - 12) = -14. Update: w = 0 - 0.1·(-14) = 1.40.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "A regression analysis reports SST = 200 and SSE = 50. What are SSR and R²?",
    options: [
      "SSR = 250, R² = 0.25",
      "SSR = 150, R² = 0.75",
      "SSR = 50, R² = 0.25",
      "SSR = 150, R² = 0.25",
    ],
    answer: 1,
    explanation: "By definition SST = SSE + SSR, so SSR = SST - SSE = 200 - 50 = 150. R² = 1 - SSE/SST = 1 - 50/200 = 0.75 (equivalently SSR/SST = 150/200 = 0.75).",
  },
  {
    week: 11,
    topic: "Regression",
    question: "If a regression model explains SSR = 80 units of variability out of a total SST = 100, what is R²?",
    options: [
      "0.20",
      "0.80",
      "1.25",
      "0.50",
    ],
    answer: 1,
    explanation: "R² = SSR/SST = 80/100 = 0.80. Equivalently, since SSE = SST - SSR = 20, R² = 1 - SSE/SST = 1 - 20/100 = 0.80. The model explains 80% of the total variance in y.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "A fitted simple linear regression is y_hat = 2x + 3. What is the predicted value when x = 5, and what does the coefficient 2 mean?",
    options: [
      "y_hat = 10; coefficient is the y-intercept",
      "y_hat = 13; a 1-unit increase in x increases y by 2 (holding all else fixed)",
      "y_hat = 13; coefficient is the MSE",
      "y_hat = 8; coefficient is the p-value",
    ],
    answer: 1,
    explanation: "y_hat = 2·5 + 3 = 13. The slope (coefficient on x) represents the expected change in y for a 1-unit increase in x. The intercept 3 is the predicted y when x = 0.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given true values y = [3, 5, 7] and predictions ŷ = [2, 5, 9], what is the MSE?",
    options: [
      "1.00",
      "1.67",
      "2.50",
      "5.00",
    ],
    answer: 1,
    explanation: "Residuals are 3-2=1, 5-5=0, 7-9=-2. Squared: 1, 0, 4. Sum = 5. MSE = (1/n) Σ (y_i - ŷ_i)² = 5/3 ≈ 1.67.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given y = [3, 5, 7] and ŷ = [2, 5, 9] (so MSE = 5/3), what is the RMSE?",
    options: [
      "0.83",
      "1.67",
      "2.50",
      "1.29",
    ],
    answer: 3,
    explanation: "RMSE = √MSE = √(5/3) = √1.667 ≈ 1.29. RMSE puts the error back in the original units of y.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given true values y = [10, 20, 30] and predictions ŷ = [12, 18, 33], what is the MAE?",
    options: [
      "1.67",
      "3.00",
      "7.00",
      "2.33",
    ],
    answer: 3,
    explanation: "Absolute residuals: |10-12|=2, |20-18|=2, |30-33|=3. Sum = 7. MAE = (1/n) Σ |y_i - ŷ_i| = 7/3 ≈ 2.33.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given y = [2, 4, 6, 8] (mean ȳ = 5) and ŷ = [2.5, 3.5, 6.5, 7.5], what is R²?",
    options: [
      "0.50",
      "0.75",
      "0.95",
      "1.00",
    ],
    answer: 2,
    explanation: "SSE = 0.25 + 0.25 + 0.25 + 0.25 = 1.0. SST = 9 + 1 + 1 + 9 = 20. R² = 1 - SSE/SST = 1 - 1/20 = 0.95.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given true values y = [4, 4, 4] (all equal to the mean) and predictions ŷ = [3, 4, 5], what is R²?",
    options: [
      "Undefined or −∞ (because SST = 0)",
      "0",
      "1",
      "0.5",
    ],
    answer: 0,
    explanation: "SST = Σ(y_i - ȳ)² = 0 since all values equal the mean. R² = 1 - SSE/SST has a zero denominator, so it is undefined. Without variance in y, R² cannot be computed.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Starting with w = 0, b = 0, learning rate η = 0.1, and a single data point (x, y) = (2, 4) under MSE loss L = (wx + b − y)², what is the new value of w after one gradient descent step?",
    options: [
      "1.6",
      "0.8",
      "0.4",
      "16.0",
    ],
    answer: 0,
    explanation: "ŷ = 0·2 + 0 = 0. Error = ŷ - y = -4. ∂L/∂w = 2·(error)·x = 2·(-4)·2 = -16. Update: w := w - η·∂L/∂w = 0 - 0.1·(-16) = 1.6.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Starting with w = 0, b = 0, η = 0.1, point (x, y) = (2, 4), what is the new value of b after one gradient descent step?",
    options: [
      "0.4",
      "1.6",
      "-0.8",
      "0.8",
    ],
    answer: 3,
    explanation: "Error = ŷ - y = 0 - 4 = -4. ∂L/∂b = 2·(error) = 2·(-4) = -8. Update: b := b - η·∂L/∂b = 0 - 0.1·(-8) = 0.8.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Starting with w = 1, b = 0, η = 0.01, and a point (x, y) = (3, 5), what is the new w after one gradient descent step (MSE on one point)?",
    options: [
      "0.88",
      "1.00",
      "1.12",
      "1.24",
    ],
    answer: 2,
    explanation: "ŷ = 1·3 + 0 = 3. Error = 3 - 5 = -2. ∂L/∂w = 2·(-2)·3 = -12. Update: w := 1 - 0.01·(-12) = 1 + 0.12 = 1.12.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "If the learning rate η in gradient descent is set too high, the most likely outcome is:",
    options: [
      "The loss converges faster than usual to the global minimum",
      "The closed-form normal equation must be used instead",
      "The model becomes regularized automatically",
      "The loss oscillates or diverges (blows up)",
    ],
    answer: 3,
    explanation: "A large η causes parameter updates to overshoot the minimum. Loss can oscillate around the minimum or grow without bound (diverge to infinity).",
  },
  {
    week: 11,
    topic: "Regression",
    question: "If the learning rate η in gradient descent is set too small:",
    options: [
      "The loss diverges to infinity",
      "Convergence is extremely slow and may not finish in the available training budget",
      "The model overfits automatically",
      "The gradient becomes zero",
    ],
    answer: 1,
    explanation: "A tiny step size means each update moves the weights only slightly. Many more epochs are needed, and within a fixed training budget the optimum may not be reached.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "What does R² = 0 mean?",
    options: [
      "The model perfectly predicts every target",
      "The model is worse than predicting the mean",
      "The MSE is zero",
      "The model is no better than always predicting the mean of y",
    ],
    answer: 3,
    explanation: "R² = 1 - SSE/SST. R² = 0 means SSE = SST, i.e., the model's squared error equals that of the constant-mean predictor. Always predicting ȳ gives R² = 0.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "What does a negative R² value (e.g., on a test set) indicate?",
    options: [
      "The model is better than the mean predictor",
      "The model is worse than just predicting the mean of y",
      "R² can never be negative",
      "The features are perfectly correlated",
    ],
    answer: 1,
    explanation: "R² < 0 means SSE > SST, so the model's predictions have larger squared error than simply predicting the mean. This can happen on held-out test data.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Which statement about Ridge (L2) vs Lasso (L1) regularization is correct?",
    options: [
      "Ridge drives many weights exactly to zero; Lasso only shrinks them",
      "Both produce equally sparse solutions",
      "Lasso drives many weights exactly to zero; Ridge only shrinks them (rarely exactly zero)",
      "Ridge uses MAE; Lasso uses MSE",
    ],
    answer: 2,
    explanation: "Lasso's L1 penalty λΣ|w_j| has a non-smooth kink at 0 that produces sparse solutions (many w_j = 0 exactly), giving automatic feature selection. Ridge's L2 penalty λΣw_j² shrinks weights smoothly but rarely to exactly zero.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Which of these is the main advantage of Ridge regression's closed-form (XᵀX + λI)⁻¹ Xᵀy over plain OLS?",
    options: [
      "It removes the need for any matrix inversion",
      "It guarantees R² = 1 on training data",
      "It produces a sparse weight vector",
      "The +λI term makes the matrix invertible even when XᵀX is singular (fixing multicollinearity)",
    ],
    answer: 3,
    explanation: "Adding λI shifts every eigenvalue of XᵀX up by λ > 0, ensuring invertibility even when features are perfectly correlated or when d > n. This is why Ridge handles multicollinearity gracefully.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Polynomial regression ŷ = w₀ + w₁x + w₂x² + w₃x³ is considered a linear model because:",
    options: [
      "The relationship between x and y is a straight line",
      "It uses MSE as a loss",
      "The model is linear in the parameters w₀, w₁, w₂, w₃ even though it is nonlinear in x",
      "It cannot overfit",
    ],
    answer: 2,
    explanation: "‘Linear regression' means linear in the weights, not linear in the inputs. Since ŷ is a linear combination of the features [1, x, x², x³], the same training algorithms (normal equation, gradient descent) apply.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Fitting a degree-12 polynomial to only 14 data points typically gives train R² ≈ 0.99 but test R² ≈ 0.3-0.6. What is this called and what is a good cure?",
    options: [
      "Underfitting; use a higher-degree polynomial",
      "Multicollinearity; drop a feature",
      "Convergence failure; increase the learning rate",
      "Overfitting; use a simpler model, more data, or regularization",
    ],
    answer: 3,
    explanation: "A large gap between high training performance and low test performance is the hallmark of overfitting. Cures include reducing model complexity (lower degree), adding regularization (Ridge/Lasso), getting more data, or cross-validating.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Regularization (Ridge or Lasso) affects the bias-variance tradeoff how?",
    options: [
      "Decreases variance but increases bias",
      "Decreases both bias and variance",
      "Increases both bias and variance",
      "Eliminates bias entirely",
    ],
    answer: 0,
    explanation: "Penalizing weight magnitudes makes the model less flexible (higher bias) but also less sensitive to noise in the training data (lower variance). The tradeoff is tuned via λ, ideally with cross-validation.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "A fitted model is Sales = 51.849 + 7.527 × Advertising. What are the predicted sales when Advertising = 10?",
    options: [
      "127.119",
      "75.27",
      "102.62",
      "587.97",
    ],
    answer: 0,
    explanation: "ŷ = b + w·x = 51.849 + 7.527·10 = 51.849 + 75.27 = 127.119.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "The normal equation w* = (XᵀX)⁻¹ Xᵀ y is preferred over gradient descent when:",
    options: [
      "The number of features d is huge (thousands or more)",
      "Features are perfectly collinear",
      "The loss is non-differentiable",
      "The dataset has few features and XᵀX is well-conditioned and invertible",
    ],
    answer: 3,
    explanation: "Computing (XᵀX)⁻¹ is O(d³), so it is fast when d is small but prohibitive for large d. It also requires XᵀX to be invertible (no perfect multicollinearity, n ≥ d).",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Starting with w = 2, b = 1, η = 0.1, and a single data point (x, y) = (1, 4) under MSE on one point, what are the updated values of (w, b) after one step?",
    options: [
      "(1.8, 0.8)",
      "(2.4, 1.4)",
      "(2.2, 1.2)",
      "(2.0, 1.0)",
    ],
    answer: 2,
    explanation: "ŷ = 2·1 + 1 = 3. Error = 3 - 4 = -1. ∂L/∂w = 2·(-1)·1 = -2; ∂L/∂b = 2·(-1) = -2. Updates: w := 2 - 0.1·(-2) = 2.2; b := 1 - 0.1·(-2) = 1.2.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Which evaluation metric is most robust to outliers in y?",
    options: [
      "MSE (Mean Squared Error)",
      "RMSE (Root Mean Squared Error)",
      "MAE (Mean Absolute Error)",
      "R²",
    ],
    answer: 2,
    explanation: "MAE treats all residuals linearly with |y_i - ŷ_i|, so a single huge residual contributes only its absolute value. MSE/RMSE square the residual, so outliers dominate. R² is based on squared error and is therefore also outlier-sensitive.",
  },
  {
    week: 11,
    topic: "Regression",
    question: "Given true values y = [1, 2, 3] and predictions ŷ = [3, 4, 5], what is the MAE?",
    options: [
      "2.0",
      "1.0",
      "3.0",
      "4.0",
    ],
    answer: 0,
    explanation: "Absolute residuals: |1-3|=2, |2-4|=2, |3-5|=2. Sum = 6. MAE = 6/3 = 2.0. The model is systematically off by 2.",
  },
];

export default l11;
