import type { Question } from "../../types";

const l10: Question[] = [
  {
    week: 10,
    topic: "ML Classification",
    question: "Which of the following best characterizes reinforcement learning, distinguishing it from supervised and unsupervised learning?",
    options: [
      "The agent is given labeled (x, y) pairs and must learn a mapping f(x) -> y",
      "The agent must discover hidden structure in unlabeled data, such as clusters",
      "The agent interacts with an environment and learns a policy from a scalar reward signal, with no labels of the 'correct' action",
      "The agent must memorize the training data and look up the nearest example at test time",
    ],
    answer: 2,
    explanation: "Per AIMA Ch. 19, reinforcement learning learns from a reward signal received through interaction with an environment. Supervised learning uses (x,y) labels and unsupervised learning finds structure in unlabeled data.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Compute the entropy (in bits) of a node with class distribution (3 positives, 1 negative).",
    options: [
      "0.500",
      "0.722",
      "0.811",
      "0.918",
    ],
    answer: 2,
    explanation: "H = -(3/4)log2(3/4) - (1/4)log2(1/4) = -0.75*(-0.415) - 0.25*(-2) = 0.311 + 0.500 = 0.811 bits.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Parent node has 16 records (8 positive, 8 negative), so entropy H(parent) = 1.0 bit. A candidate split yields child A = (7,1) and child B = (1,7), each with 8 records. What is the Information Gain (using entropy) of this split, approximately?",
    options: [
      "0.456 bits",
      "0.544 bits",
      "0.811 bits",
      "1.000 bits",
    ],
    answer: 0,
    explanation: "H(child A) = -(7/8)log2(7/8) - (1/8)log2(1/8) = 0.169 + 0.375 = 0.544. By symmetry H(child B) = 0.544. Weighted child entropy = 0.5*0.544 + 0.5*0.544 = 0.544. Gain = 1.000 - 0.544 = 0.456 bits.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A node has 20 records with class distribution (6 positive, 14 negative). What is the misclassification error of this node?",
    options: [
      "0.20",
      "0.30",
      "0.42",
      "0.70",
    ],
    answer: 1,
    explanation: "Misclassification error = 1 - max_i p_i = 1 - max(6/20, 14/20) = 1 - 0.70 = 0.30. Labeling the node by its majority class (negative) would misclassify 6 of 20 records.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Confusion matrix: TP=50, FP=10, FN=20, TN=120. What is the accuracy?",
    options: [
      "0.70",
      "0.80",
      "0.85",
      "0.90",
    ],
    answer: 2,
    explanation: "Accuracy = (TP+TN)/N = (50+120)/(50+10+20+120) = 170/200 = 0.85.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Confusion matrix: TP=40, FP=10, FN=20, TN=130. What is the F1-score (approximately)?",
    options: [
      "0.667",
      "0.727",
      "0.800",
      "0.850",
    ],
    answer: 1,
    explanation: "Precision = 40/(40+10) = 0.800. Recall = 40/(40+20) = 0.667. F1 = 2*P*R/(P+R) = 2*0.8*0.667/(0.8+0.667) = 1.067/1.467 approximately 0.727.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A spam filter is evaluated as: TP=70, FP=30, FN=30, TN=870. What is the specificity (true negative rate)?",
    options: [
      "0.700",
      "0.778",
      "0.900",
      "0.967",
    ],
    answer: 3,
    explanation: "Specificity = TN/(TN+FP) = 870/(870+30) = 870/900 approximately 0.967.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A disease screening test sees 100 sick and 900 healthy patients. The classifier returns TP=80, FP=90, FN=20, TN=810. What is the precision, and why might it be a concern despite a high accuracy of 0.89?",
    options: [
      "Precision approximately 0.471; many positive predictions are false alarms, which matters in screening",
      "Precision approximately 0.800; accuracy is the only metric needed",
      "Precision approximately 0.900; recall is the real problem",
      "Precision approximately 0.978; the classifier is essentially perfect",
    ],
    answer: 0,
    explanation: "Precision = TP/(TP+FP) = 80/(80+90) = 80/170 approximately 0.471. Although accuracy is (80+810)/1000 = 0.89, more than half the positive predictions are false positives, an important issue under class imbalance.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "In k-Nearest Neighbors classification, what is the effect of using a very large k (e.g., k equal to the size of the training set)?",
    options: [
      "The model overfits and has high variance",
      "The model becomes lazy and stores no information",
      "The decision boundary becomes very smooth and the model underfits with high bias, predicting the majority class everywhere",
      "The model exactly memorizes the training data",
    ],
    answer: 2,
    explanation: "Large k averages over many neighbors, smoothing the decision boundary. In the extreme k=N, every query is classified as the overall majority class, giving high bias and low variance (underfitting). Small k gives high variance (overfitting).",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A decision tree learning algorithm considers a split on a binary attribute. Parent node has 40 records (20 positive, 20 negative), Gini = 0.5. The split produces child A = (18, 2) and child B = (2, 18), each with 20 records. What is the Information Gain (using Gini)?",
    options: [
      "0.18",
      "0.32",
      "0.36",
      "0.50",
    ],
    answer: 1,
    explanation: "Gini(A) = 1 - (18/20)^2 - (2/20)^2 = 1 - 0.81 - 0.01 = 0.18. By symmetry Gini(B) = 0.18. Weighted child Gini = (20/40)*0.18 + (20/40)*0.18 = 0.18. Information Gain = 0.50 - 0.18 = 0.32.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A node contains 10 samples: 6 positive and 4 negative. What is the Gini index of this node?",
    options: [
      "0.36",
      "0.48",
      "0.52",
      "0.60",
    ],
    answer: 1,
    explanation: "Gini = 1 - (6/10)^2 - (4/10)^2 = 1 - 0.36 - 0.16 = 0.48.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A node contains 10 samples: 6 positive and 4 negative. What is the entropy (in bits) of this node, approximately?",
    options: [
      "0.722",
      "0.811",
      "0.971",
      "1.000",
    ],
    answer: 2,
    explanation: "Entropy = -0.6*log2(0.6) - 0.4*log2(0.4) = -0.6*(-0.737) - 0.4*(-1.322) = 0.442 + 0.529 approximately 0.971 bits.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Parent node has 20 records (10 pos, 10 neg), Gini=0.5. A split produces child A=(8,2) with 10 records and child B=(2,8) with 10 records. What is the Information Gain (using Gini)?",
    options: [
      "0.18",
      "0.20",
      "0.32",
      "0.50",
    ],
    answer: 0,
    explanation: "Gini(A) = 1 - (8/10)^2 - (2/10)^2 = 1 - 0.64 - 0.04 = 0.32. Gini(B) = 1 - (2/10)^2 - (8/10)^2 = 0.32. Weighted Gini = (10/20)(0.32) + (10/20)(0.32) = 0.32. Gain = 0.5 - 0.32 = 0.18.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Consider two candidate splits on a parent node with Gini=0.5 (16 records, 8 pos/8 neg). Split A: child1=(6,2) and child2=(2,6), each with 8 records. Split B: child1=(7,1) and child2=(1,7), each with 8 records. Which split is preferred and why?",
    options: [
      "Split A, because its weighted Gini is 0.375 (lower)",
      "Split B, because its weighted Gini is 0.21875 (lower)",
      "Both are equally good (same gain)",
      "Split A, because it has higher entropy",
    ],
    answer: 1,
    explanation: "Split A: Gini(child)=1-(6/8)^2-(2/8)^2=1-0.5625-0.0625=0.375. Weighted=0.375. Split B: Gini(child)=1-(7/8)^2-(1/8)^2=1-0.766-0.016=0.21875. Weighted=0.21875. Split B has lower weighted impurity (higher gain), so it is preferred.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Confusion matrix: TP=60, FP=15, FN=25, TN=100. What is the accuracy?",
    options: [
      "0.70",
      "0.75",
      "0.80",
      "0.85",
    ],
    answer: 2,
    explanation: "Accuracy = (TP+TN)/(TP+TN+FP+FN) = (60+100)/(60+100+15+25) = 160/200 = 0.80.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Confusion matrix: TP=60, FP=15, FN=25, TN=100. What is the F1-score (approximately)?",
    options: [
      "0.706",
      "0.750",
      "0.800",
      "0.857",
    ],
    answer: 1,
    explanation: "Precision = 60/(60+15) = 0.80. Recall = 60/(60+25) = 60/85 approximately 0.7059. F1 = 2*0.80*0.7059/(0.80+0.7059) = 1.1294/1.5059 approximately 0.750.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A binary classifier produces: TP=45, FP=5, FN=15, TN=135. What is the precision and recall?",
    options: [
      "Precision=0.75, Recall=0.90",
      "Precision=0.90, Recall=0.75",
      "Precision=0.90, Recall=0.90",
      "Precision=0.75, Recall=0.75",
    ],
    answer: 1,
    explanation: "Precision = TP/(TP+FP) = 45/(45+5) = 45/50 = 0.90. Recall = TP/(TP+FN) = 45/(45+15) = 45/60 = 0.75.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Training points (with class): A=(1,1)+, B=(2,2)+, C=(3,3)-, D=(6,6)-, E=(7,7)-. Classify query point Q=(2.5, 2.5) using 3-NN with Euclidean distance.",
    options: [
      "Positive (+), because the 3 nearest neighbors are A, B, C (2 positive, 1 negative)",
      "Negative (-), because the 3 nearest neighbors are C, D, E",
      "Positive (+), because the 3 nearest neighbors are A, B, D",
      "Tie - cannot decide",
    ],
    answer: 0,
    explanation: "Euclidean distances from Q=(2.5,2.5): to A=sqrt(1.5^2+1.5^2)=2.12; to B=sqrt(0.5^2+0.5^2)=0.71; to C=sqrt(0.5^2+0.5^2)=0.71; to D=sqrt(3.5^2+3.5^2)=4.95; to E=sqrt(4.5^2+4.5^2)=6.36. The 3 nearest are B(+), C(-), A(+). Majority = positive (2 vs 1).",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Training set with class labels: P1=(0,0)A, P2=(4,0)A, P3=(0,3)B, P4=(3,4)B. For query Q=(1,1), what is the 1-NN prediction using Euclidean distance?",
    options: [
      "Class A (nearest is P1 at distance sqrt(2))",
      "Class B (nearest is P3 at distance sqrt(5))",
      "Class A (nearest is P2 at distance sqrt(10))",
      "Class B (nearest is P4 at distance sqrt(13))",
    ],
    answer: 0,
    explanation: "Distances from Q=(1,1): P1=sqrt(1+1)=sqrt(2) approximately 1.41 (A); P2=sqrt(9+1)=sqrt(10) approximately 3.16 (A); P3=sqrt(1+4)=sqrt(5) approximately 2.24 (B); P4=sqrt(4+9)=sqrt(13) approximately 3.61 (B). Nearest is P1 (class A).",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Parent node has class counts (4, 4), Gini=0.5. A split produces child1=(4,0) with 4 records and child2=(0,4) with 4 records. What is the entropy gain (information gain using entropy)?",
    options: [
      "0.0",
      "0.5",
      "0.75",
      "1.0",
    ],
    answer: 3,
    explanation: "Parent entropy = -(0.5)log2(0.5) - (0.5)log2(0.5) = 1.0. Both children are pure so their entropy is 0. Weighted child entropy = 0. Gain = 1.0 - 0 = 1.0 bit (maximum possible).",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Consider a node with class distribution (3 pos, 5 neg), 8 records total. What is the misclassification error of this node?",
    options: [
      "0.125",
      "0.375",
      "0.469",
      "0.625",
    ],
    answer: 1,
    explanation: "Misclassification error = 1 - max_i P(i|t) = 1 - max(3/8, 5/8) = 1 - 0.625 = 0.375. This means if we labeled the node by its majority class (negative), we would misclassify 3 out of 8 records.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Which of the following is an example of an unsupervised learning task?",
    options: [
      "Predicting house prices from features",
      "Classifying emails as spam or not spam",
      "Grouping customers into segments without using labels",
      "Training a robot to walk via reward signals",
    ],
    answer: 2,
    explanation: "Unsupervised learning operates on unlabeled data to find structure. Clustering customers into segments without using any labels is the canonical example. The other options describe regression, classification, and reinforcement learning.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "What is the primary purpose of a validation set (separate from the test set)?",
    options: [
      "To tune hyperparameters without contaminating the final unbiased test evaluation",
      "To train the model's main parameters",
      "To replace the training set when it is too small",
      "To compute the confusion matrix",
    ],
    answer: 0,
    explanation: "The validation set is used to tune hyperparameters (e.g., tree depth, k for kNN) while keeping the test set untouched until the final evaluation. This prevents test-set leakage and gives an unbiased estimate of generalization.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Compute the Gini index of a node with class counts (C1=1, C2=3).",
    options: [
      "0.250",
      "0.444",
      "0.375",
      "0.500",
    ],
    answer: 2,
    explanation: "Gini = 1 - (1/4)^2 - (3/4)^2 = 1 - 0.0625 - 0.5625 = 0.375.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Compute the entropy (in bits) of a node with class counts (C1=2, C2=2).",
    options: [
      "0.0",
      "0.5",
      "1.0",
      "2.0",
    ],
    answer: 2,
    explanation: "Entropy = -(2/4)log_2(2/4) - (2/4)log_2(2/4) = -0.5(-1) - 0.5(-1) = 1.0 bit. A 50/50 binary split has maximum entropy of log_2(2) = 1.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A parent node has Gini=0.5 (e.g., 4 positives, 4 negatives). A candidate split produces two children: child A=(4,0) and child B=(0,4), each with 4 records. What is the Information Gain (using Gini) of this split?",
    options: [
      "0.0",
      "0.25",
      "0.375",
      "0.5",
    ],
    answer: 3,
    explanation: "Both children are pure (Gini=0). Weighted child Gini = (4/8)(0) + (4/8)(0) = 0. Gain = 0.5 - 0 = 0.5. This is the maximum possible gain because the split perfectly separates the classes.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Confusion matrix: TP=80, FP=20, FN=10, TN=90. What is the precision?",
    options: [
      "0.80",
      "0.889",
      "0.90",
      "0.842",
    ],
    answer: 0,
    explanation: "Precision = TP/(TP+FP) = 80/(80+20) = 80/100 = 0.80.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Confusion matrix: TP=80, FP=20, FN=10, TN=90. What is the F1-score (approximately)?",
    options: [
      "0.80",
      "0.842",
      "0.85",
      "0.889",
    ],
    answer: 1,
    explanation: "Precision=0.80, Recall=0.889. F1 = 2*P*R/(P+R) = 2*0.80*0.889/(0.80+0.889) = 1.4222/1.689 approximately 0.842.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Confusion matrix: TP=80, FP=20, FN=10, TN=90. What is the specificity?",
    options: [
      "0.80",
      "0.818",
      "0.90",
      "0.95",
    ],
    answer: 1,
    explanation: "Specificity = TN/(TN+FP) = 90/(90+20) = 90/110 approximately 0.818.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A medical test on 1000 patients: 990 healthy and 10 sick. A trivial classifier predicts 'healthy' for all 1000 patients. What problem does this illustrate?",
    options: [
      "Underfitting due to insufficient training data",
      "The curse of dimensionality",
      "High accuracy (99%) is misleading under class imbalance because the model catches no sick patients (recall = 0)",
      "The model has too many parameters",
    ],
    answer: 2,
    explanation: "The classifier achieves 99% accuracy but recall = 0/10 = 0% on the positive (sick) class. Under heavy class imbalance, accuracy is misleading; precision, recall, and F1 must be inspected instead.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Confusion matrix for a fraud detector: TP=90, FP=10, FN=30, TN=870. What is the F1-score (approximately)?",
    options: [
      "0.75",
      "0.80",
      "0.818",
      "0.90",
    ],
    answer: 2,
    explanation: "Precision = 90/(90+10) = 0.90. Recall = 90/(90+30) = 0.75. F1 = 2*0.9*0.75/(0.9+0.75) = 1.35/1.65 approximately 0.818.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "In k-Nearest Neighbors classification, what typically happens if k is set to 1?",
    options: [
      "The model becomes very smooth and underfits",
      "The model cannot make predictions",
      "The distance metric is ignored",
      "The model becomes very sensitive to noise and tends to overfit",
    ],
    answer: 3,
    explanation: "With k=1, the prediction for any point depends only on its single nearest neighbor, making the decision boundary highly sensitive to noise and individual training points. This leads to high variance and overfitting. Larger k smooths the boundary.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Why should features generally be scaled (standardized or normalized) before using kNN?",
    options: [
      "kNN cannot handle negative numbers",
      "Scaling speeds up the training phase of kNN",
      "Scaling is required to make kNN deterministic",
      "Distance computations are dominated by features with the largest numeric ranges, so unscaled features bias the neighbor selection",
    ],
    answer: 3,
    explanation: "kNN relies on distances (e.g., Euclidean). A feature like 'salary' (range 0-100000) will dominate a feature like 'age' (range 0-100) unless scaled. Standardization or min-max normalization equalizes their contribution.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "What is the 'naive' assumption in Naive Bayes?",
    options: [
      "All classes have equal prior probability",
      "The data is normally distributed",
      "The decision boundary is always linear",
      "The features are conditionally independent given the class",
    ],
    answer: 3,
    explanation: "Naive Bayes assumes that, given the class label, all features are independent of one another. This rarely holds in practice but greatly simplifies computation and often still yields good baselines (especially in text classification).",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Which of the following best describes logistic regression?",
    options: [
      "A regression algorithm that predicts continuous outputs",
      "A classification algorithm that models P(y=1|x) using a sigmoid and produces a linear decision boundary",
      "A tree-based ensemble method",
      "A lazy learner that stores training data for prediction time",
    ],
    answer: 1,
    explanation: "Despite its name, logistic regression is a classifier. It models P(y=1|x) = sigma(w*x + b), and the decision boundary w*x + b = 0 is linear. Predict class 1 when the sigmoid output is at least 0.5.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "What is the role of support vectors in a Support Vector Machine?",
    options: [
      "They are the training points closest to the decision boundary; they alone determine the maximum-margin hyperplane",
      "They are the misclassified training examples",
      "They are randomly sampled subsets of features used at each split",
      "They are the cluster centroids in the feature space",
    ],
    answer: 0,
    explanation: "Support vectors are the points lying on or closest to the margin. The SVM optimization maximizes the margin between the two classes, and only those points define the hyperplane; removing non-support training points does not change it.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "A decision tree achieves 100% accuracy on the training set but only 60% accuracy on the test set. Which technique most directly addresses this?",
    options: [
      "Increase the depth of the tree further",
      "Remove the validation set",
      "Pre-prune (e.g., reduce max_depth) or post-prune the tree",
      "Use a smaller training set",
    ],
    answer: 2,
    explanation: "The huge train/test gap is classic overfitting. Pruning (either pre-pruning via max_depth, min_samples_leaf, etc., or post-pruning) reduces tree complexity and improves generalization. Increasing depth would worsen the problem.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Which statement about the bias-variance tradeoff is correct?",
    options: [
      "Underfit models have high variance and low bias",
      "Overfit models have high bias and low variance",
      "Overfit models have high variance (sensitive to training data) and low bias",
      "Bias and variance are independent and cannot both be reduced",
    ],
    answer: 2,
    explanation: "Overfit models fit the training noise, so they have low bias but high variance (change a lot with different training samples). Underfit models have high bias and low variance. The goal is to minimize total error = bias^2 + variance + irreducible noise.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "In k-fold cross-validation with k=5, how is the data used?",
    options: [
      "The data is split into 5 equal folds; the model is trained on 4 folds and validated on the remaining fold, rotating until each fold has been the validation set once, and scores are averaged",
      "The model is trained 5 times on the same training set with different random seeds",
      "The data is split into 5 disjoint test sets that are never used for training",
      "The model uses 5 different algorithms and votes on the result",
    ],
    answer: 0,
    explanation: "k-fold CV partitions the data into k folds. For each fold, the model is trained on the other k-1 folds and evaluated on the held-out fold. The k scores are averaged to give a more stable estimate of model performance than a single split.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Which of the following is a key property of Hunt's algorithm for decision tree induction?",
    options: [
      "It uses gradient descent to update tree weights",
      "It builds the tree top-down by clustering similar records",
      "It recursively partitions the records: if all records at a node share a class, it becomes a leaf; otherwise pick an attribute test and recurse on the resulting subsets",
      "It only works on continuous features",
    ],
    answer: 2,
    explanation: "Hunt's algorithm is the foundational recursive procedure: pure nodes become leaves, empty nodes get a default class, and impure nodes are split by an attribute test, recursing on the children. CART, ID3 and C4.5 build on this skeleton.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Parent node has 100 records with class distribution (50, 50), Gini = 0.5. A split yields child A with 60 records and Gini 0.4, and child B with 40 records and Gini 0.25. What is the weighted Gini of the children and the Information Gain?",
    options: [
      "Weighted Gini = 0.325, Gain = 0.175",
      "Weighted Gini = 0.34, Gain = 0.16",
      "Weighted Gini = 0.50, Gain = 0.00",
      "Weighted Gini = 0.65, Gain = -0.15",
    ],
    answer: 1,
    explanation: "Weighted Gini = (60/100)(0.4) + (40/100)(0.25) = 0.24 + 0.10 = 0.34. Information Gain = 0.5 - 0.34 = 0.16. The split with the largest gain is chosen.",
  },
  {
    week: 10,
    topic: "ML Classification",
    question: "Which combination of observations is the strongest sign of overfitting?",
    options: [
      "Training accuracy and test accuracy are both low",
      "Training accuracy is high and test accuracy is approximately equal to training accuracy",
      "Training accuracy is very high while test accuracy is much lower, with a large gap between them",
      "Both training and test accuracy increase as the model becomes more complex",
    ],
    answer: 2,
    explanation: "The hallmark of overfitting is a model that fits the training data nearly perfectly but generalizes poorly: high training accuracy plus much lower test accuracy. A large train-test gap is the diagnostic signal.",
  },
];

export default l10;
